### ISSUE TITLE
Removing support for Rubinius

### ISSUE THREAD

**Issue by eregon** [ruby/setup-ruby#101]
Rubinius was never fully supported (it only built successfully on ubuntu-18.04, on other platforms it segfaults), but it got worse as it seems the latest Rubinius, Rubinius 5.0, segfaults on every single platform:
https://github.com/ruby/ruby-builder/runs/1338771610?check_suite_focus=true

Also I doubt any realistic workload runs on Rubinius nowadays, given that even Bundler does not work.

So, I plan to remove that single Rubinius build.
I will try to take the opportunity to see if it's possible to deprecate builds before removal.

**Comment by hsbt** [comment]
I'm +1 for this. The last commit of rubinius is 6 months ago.

**Comment by eregon** [comment]
Deprecation warning added in https://github.com/ruby/setup-ruby/commit/c49deecea1c29e10ae751dfc04898cd4368ce591
