### ISSUE TITLE
Cache saving fails on Windows

### ISSUE THREAD

**Issue by eregon** [ruby/setup-ruby#102]
See https://github.com/ruby/setup-ruby/runs/1370892940?check_suite_focus=true
```
  Saving cache
  C:\msys64\usr\bin\tar.exe --posix --use-compress-program "zstd -T0" -cf cache.tzst -P -C D:/a/setup-ruby/setup-ruby --files-from manifest.txt --force-local
  /usr/bin/tar: vendor\bundle: Cannot stat: No such file or directory
  /usr/bin/tar: Exiting with failure status due to previous errors
  Warning: Tar failed with error: The process 'C:\msys64\usr\bin\tar.exe' failed with exit code 2
```
I guess this is due to using MSYS's `tar` and not one of the other `tar`.

It seems we get in this branch:
https://github.com/actions/toolkit/blob/e7eb2c741847a05686a1b8df93dea4b244640b17/packages/cache/src/internal/tar.ts#L16-L18
when probably we should be in this branch:
https://github.com/actions/toolkit/blob/e7eb2c741847a05686a1b8df93dea4b244640b17/packages/cache/src/internal/tar.ts#L20
or use the GNU tar but not MSYS's one.

cc @MSP-Greg

**Comment by eregon** [comment]
One possible solution would be to save/restore the `PATH` around saving the cache, but it seems rather inconvenient.

**Comment by MSP-Greg** [comment]
As you can see, there are a few utilities that exist both in 'Windows' and in MSYS2.  I know they're trying to sort it out in the 'virtual-environments' repo, have to go look.  I wish they'd hard coded the paths when that happens so the correct tool is chosen, rather then depending on `Path`...

**Comment by eregon** [comment]
On https://github.com/eregon/setup-ruby/runs/1392737782?check_suite_focus=true#step:3:100 we can see the cache paths written to manifest.txt is `["vendor\\bundle"]` but it should most likely uses `/` as separator for GNU tar.

**Comment by MSP-Greg** [comment]
Sorry, I forgot to mention the backslashes.  Almost all the MSFT programs/commands one would use in a shell (PowerShell or cmd) accept forward slashes...

**Comment by eregon** [comment]
I filed an issue upstream: https://github.com/actions/toolkit/issues/632

**Comment by eregon** [comment]
Fixed upstream, and dependency updated, it works now in https://github.com/ruby/setup-ruby/releases/tag/v1.59.1
