### ISSUE TITLE
v1.50.0 Fails gem install (can't find the ruby)

### ISSUE THREAD

**Issue by mrGrazy** [ruby/setup-ruby#104]
The most recent release seems to have broken the install of ruby.

The setup ruby action is failing with 
```
/home/runner/_work/_tool/Ruby/2.6.3/x64/bin/gem install bundler -v ~> 1 --no-document
  Took   0.00 seconds
Error: There was an error when attempting to execute the process '/home/runner/_work/_tool/Ruby/2.6.3/x64/bin/gem'. This may indicate the process failed to start. Error: spawn /home/runner/_work/_tool/Ruby/2.6.3/x64/bin/gem ENOENT
```

When I try running that command again on the runners I see this error:

```
runner@runner-pool-pod-bp4zt:~$ /home/runner/_work/_tool/Ruby/2.6.3/x64/bin/gem install bundler -v ~> 1 --no-document
bash: /home/runner/_work/_tool/Ruby/2.6.3/x64/bin/gem: /opt/hostedtoolcache/Ruby/2.6.3/x64/bin/ruby: bad interpreter: No such file or directory
```

So it looks like the recent change to related to hostedtoolcache is affecting the paths to ruby, but I don't know if we're supposed to be doing something different.

**Comment by mrGrazy** [comment]
Sorry after reading #98 we've worked out that this is because of RUNNER_TOOL_CACHE is not present on our self hosted runners. 
Haven't worked out how to set that correctly in a way that doesn't just crash the runner agent, but that's our problem. 🤦

**Comment by MSP-Greg** [comment]
By chance, how about AGENT_TOOLSDIRECTORY?  It has the same value on the GH Ubuntu runners...

**Comment by eregon** [comment]
The action actually checks that the env var is defined:
https://github.com/ruby/setup-ruby/blob/0592d01dc33dc78e27db0a11061c976d1d552cf7/common.js#L67-L70

Maybe it is set incorrectly in your case, or not set?
The value will need to be the same as on GitHub runners, since Ruby captures the absolute paths in various places when it's built:
https://github.com/ruby/setup-ruby/issues/98#issuecomment-722346384

**Comment by eregon** [comment]
Maybe we should hardcode the path for the 3 platforms?
Then it should work no matter what `$RUNNER_TOOL_CACHE` is set to.
Then `tc.find()` from https://github.com/actions/toolkit/tree/main/packages/tool-cache, which we will use in the future, would look in `$RUNNER_TOOL_CACHE` and potentially find custom builds of Ruby, and if not, the prebuilt ruby would be downloaded under the right path and work fine.

**Comment by shoukoo** [comment]
Just want to share some info, I need do the following in order to make the latest setup-ruby works in our self-hosted runners.
- Changed the owner from root to runner for the /opt/hostedtoolcache dir 
- Set RUNNER_TOOL_CACHE in the runner's .env file.

**Comment by eregon** [comment]
After some thoughts, I don't want to deal with RUNNER_TOOL_CACHE not being the same as on GitHub-hosted runners, as it brings a lot of complications.

I documented these requirements in 8e77d9e0fadc95adffe83ba8c1df1316aa9a617f, feel free to improve the docs with a PR.

**Comment by eregon** [comment]
I changed my mind, and hardcoded the paths in https://github.com/ruby/setup-ruby/commit/ba761ba8ff71a9113d3207595ceadac55aa09cef and update the requirements in the README.
That should work better if `$RUNNER_TOOL_CACHE` is set to another value, and result in a clearer error if e.g. the directory is not writable.
