### ISSUE TITLE
Add support for version range, using semvers version range syntax

### ISSUE THREAD

**Issue by normanr** [ruby/setup-ruby#110]
[actions/setup-ruby](https://github.com/actions/setup-ruby) allows ruby-version to be a "Version range or exact version of a Ruby version to use, using semvers version range syntax", e.g: ">= 2.7" is supported. Please could you support this in [ruby/setup-ruby](https://github.com/ruby/setup-ruby) too.

**Comment by eregon** [comment]
What's a concrete use case?

`>= 2.7` just means latest Ruby, including new major releases.
For that case, you can simply use `ruby-version: ruby`.

https://github.com/actions/setup-ruby doesn't support `ruby-version: ">= 2.7"` as far as I know, only `2.7` or `2.7.x`.
This action supports `2.7` and `2.7.2`, and not `2.7.x` (doesn't seem useful).
All details in https://github.com/ruby/setup-ruby#supported-version-syntax

**Comment by eregon** [comment]
`ruby-version: ">= 2.7"` appears to work for https://github.com/actions/setup-ruby (https://github.com/eregon/setup-ruby-test/runs/1402242516?check_suite_focus=true), although I'm not sure if it was intended.
Probably because toolcache supports such version constraints: https://github.com/actions/toolkit/tree/main/packages/tool-cache#find

Still, there seems to be very limited usefulness to specify a Ruby version that way.

**Comment by normanr** [comment]
I didn't realize that `"ruby"` was a valid option. Upon re-reading the supported syntax, this is now "obviously" (not to me at first reading) covered by the "engine only" item. (Is there a reason why this isn't the default if `.ruby-version` and `.tool-versions` don't exist?)

A slightly more realistic example might be something like Jekyll requires Ruby version 2.5.0 or higher, so `">=2.5"` would be a valid option for that if you wanted to allow using non-latest stable (for caching reasons).

**Comment by normanr** [comment]
I tried `ruby-version: ruby`, and it installed ruby-3.0.0-preview1. I found it surprising and not "the latest stable release". Is that expected?

**Comment by eregon** [comment]
For Jekyll and literally any application, it's much safer to pin down at least to a minor version (e.g., 2.5).
There is no compatibility guarantee between Ruby minor versions, and in fact Jekyll e.g. was broken/emitted many warnings when Ruby 2.7 came out, and this is pretty much expected.
So I'm against a default of latest version, that would just be unstable.
Also, having a `.ruby-version` is useful to communicate which Ruby version is compatible with a project for other developers.

> I tried `ruby-version: ruby`, and it installed ruby-3.0.0-preview1. I found it surprising and not "the latest stable release". Is that expected?

That's not intended, will try to fix.

**Comment by eregon** [comment]
I fixed `ruby-version: ruby` (which now resolves to 2.7.2) in https://github.com/ruby/setup-ruby/releases/tag/v1.51.2

So `ruby-version: ruby` should work fine now for "latest stable CRuby release".
