### ISSUE TITLE
The environment variable ImageOS must be set

### ISSUE THREAD

**Issue by shoukoo** [ruby/setup-ruby#111]
Hello there,

We're getting the following error message when using the latest setup-ruby ( v1.51.1) on our self-hosted runners. Is this something we have to set at our end onward?

![image](https://user-images.githubusercontent.com/34999291/99228512-d4509180-2840-11eb-8b25-484c58461093.png)

We were able to workaround this issue by setting `ImageOS` var to `ubuntu18` or using the older version (`v1.49.0`)

Thanks,
Andy

**Comment by eregon** [comment]
Yes, please set this variable, otherwise it's too complicated to guess the platform and version.

**Comment by eregon** [comment]
Added in the README in https://github.com/ruby/setup-ruby/commit/34fbbc1d36fbeb08e98a6bdb591cac5eed7effa8

**Comment by shoukoo** [comment]
Great, thanks for maintaining this action!
