### ISSUE TITLE
Support Ruby 2.7.2?

### ISSUE THREAD

**Issue by soumyaray** [ruby/setup-ruby#114]
The latest version supported by setup-ruby is 2.7.1, whereas 2.7.2 is the latest stable ruby

**Comment by MSP-Greg** [comment]
Are you using this action (ruby/setup-ruby) or [actions/setup-ruby](https://github.com/actions/setup-ruby)?

This action supported 2.7.2 soon after its release...

**Comment by soumyaray** [comment]
My bad -- seems to be a common mistake (looking at the issues of actions/setup-ruby).

I switched to this action and have another issue I'll start.
