### ISSUE TITLE
Log Ruby, gem and bundler version info

### ISSUE THREAD

**Issue by XhmikosR** [ruby/setup-ruby#116]
This was implemented on https://github.com/actions/setup-node/pull/137 sometime ago, and I think it'd be very handy to have this info in the log, maybe in a new "Version Info" group.

Right now, I manually run `ruby --version`, `gem --version` and `bundle --version`.

**Comment by eregon** [comment]
The Ruby version is already logged as part of the download URL:
https://github.com/ruby/setup-ruby/runs/1487552093#step:3:8

And the Bundler version as part of the output of `gem install`:
https://github.com/ruby/setup-ruby/runs/1487552093#step:3:16

The builds use the RubyGems from the Ruby release, no `gem update --system`, so it is the well known versions from the Ruby releases.

Running these commands also take time, so it's actually slowing down builds by a few seconds if unneeded (probably more severe on e.g. JRuby), and the information is mostly redundant.
So I think this is best left to user workflows if wanted.

**Comment by XhmikosR** [comment]
True, but right now the info is sort of hidden is what I mean.

I thought maybe you could construct this info from ruby-builder-versions.js and the found bundler version the action is installing, so that it's grouped together and not hidden.

No worries if it's too much trouble, I just find it nice to be able to see the versions easily.

**Comment by eregon** [comment]
For now I think it's easy enough to print these 3 versions manually in a workflow if desired.
Doing it by default would slow down CI by [several seconds](https://gist.github.com/eregon/e3a9bebe60f41c0502a88f651cb50f38) in some cases, so I think it's not a trade-off I want to make in this action.
Adding a new input to do that not by default does not seem worth it, it's very easy in a workflow to:
```yaml
- run: |
    ruby --version
    gem --version
    bundle --version
```

The Ruby version and the Bundler version is already clearly shown in the log.
The gem version is just whatever RubyGems version shipped with that Ruby.
So in fact from a log we can already be sure of which versions are used for a run, even though that might require knowing which RubyGems version shipped with a given Ruby release.

So I'd like to close this. I might reconsider based on new input.
