### ISSUE TITLE
Add support for 3.0.0-preview2?

### ISSUE THREAD

**Issue by jrochkind** [ruby/setup-ruby#121]
Actually just released today I now realize! So perhaps it's already in the works. https://www.ruby-lang.org/en/news/2020/12/08/ruby-3-0-0-preview2-released/

```
Unknown version 3.0.0-preview2 for ruby on ubuntu-18.04 … 2.7.2, 3.0.0-preview1, head … File an issue at https://github.com/ruby/setup-ruby/issues if would like support for a new version
```

Filing an issue as invited in the error message, but perhaps you are already on top of it, or also understand if at this point you're just going to wait for 3.0.0 final presumably on christmas, although it's good to have the prereleases to test in CI to find any problems.

**Comment by eregon** [comment]
I'll trigger builds for it on Linux & macOS.

**Comment by eregon** [comment]
Done: https://github.com/ruby/setup-ruby/releases/tag/v1.58.0

**Comment by jrochkind** [comment]
Thanks!

My CI build trying to use ruby 3.0.0-preview2 is weirdly failing with a message:

```
File does not exist: rexml/parsers/streamparser

rake aborted!
Command failed with status (1)
/opt/hostedtoolcache/Ruby/3.0.0-preview2/x64/bin/bundle:23:in `load'
/opt/hostedtoolcache/Ruby/3.0.0-preview2/x64/bin/bundle:23:in `<main>'
```

I don't believe my project uses or mentions rexml at all, grep'ing through the source I find no mention of "rexml". Although I may be missing something. So confused what's going on. 

It may have nothing to do with ruby-setup, but is it possible it does?  I wonder if any attempt to use 3.0.0-preview2 via ruby/setup-ruby would raise this error? Which still might be an actual ruby bug of some kind, not ruby-setup's issue? Just kind of confused what's going on. 

Curious to have anyone else confirm if they can use 3.0.0-preview2 without getting that error.

**Comment by eregon** [comment]
Could you try locally?
https://www.ruby-lang.org/en/news/2020/12/08/ruby-3-0-0-preview2-released/ says rexml became a default gem, so now it might need to be part of the Gemfile more explicitly if required.

The build https://github.com/ruby/setup-ruby/runs/1519056182 passed so it must something somehow triggered from your project.

**Comment by jrochkind** [comment]
OK thanks, that's good background.  As far as I know I am *not* requiring rexml... but a gem I am using might itself be, that's probably it.
