### ISSUE TITLE
Authenticate with Github gem registry

### ISSUE THREAD

**Issue by sandstrom** [ruby/setup-ruby#125]
It seems like the Github action `actions/setup-ruby` handles authentication with the Github gem repository automatically. Is that something that this action could support too?

**Comment by eregon** [comment]
Where did you see that? AFAIK both actions/setup-ruby and this action don't do anything with the GitHub package registry.

**Comment by sandstrom** [comment]
My mistake, sorry @eregon (I closed the issue as soon as I realized I was wrong)
