### ISSUE TITLE
Known third-party issues

### ISSUE THREAD

**Issue by eregon** [ruby/setup-ruby#128]
* Ruby 2.3 + Bundler 2: https://github.com/rubygems/rubygems/issues/3570
  * Bundler 1 is used instead on Ruby 2.3 automatically in ruby/setup-ruby (Ruby 2.3 is EOL and uses a very old RubyGems)
* JRuby 9.1 + Bundler 2: https://github.com/ruby/setup-ruby/issues/108
  * Bundler 1 is used  instead on JRuby 9.1 automatically in ruby/setup-ruby (Ruby 2.3 is EOL and uses a very old RubyGems)

---

Fixed upstream, simply use a newer Bundler release:
* JRuby + Bundler 2.1.4 + Windows + `bundle exec rake`: https://github.com/rubygems/rubygems/issues/3256 and https://github.com/ruby/setup-ruby/issues/18, fixed in Bundler 2.2.0
* JRuby + Bundler 2.2.0 + Windows: https://github.com/rubygems/rubygems/issues/4129, fixed in Bundler 2.2.2
* Bundler 2.2.0 + Gemfile.lock created with older version: https://github.com/rubygems/rubygems/issues/4123, fixed in Bundler 2.2.1

**Comment by deivid-rodriguez** [comment]
For completeness, the fix for rubygems/rubygems#3570 was released with bundler 2.2.0.rc.1, and regarding #108 we never got a report about it :shrug:.

**Comment by eregon** [comment]
Regarding #108, I was hoping @JonRowe would report it to Bundler or JRuby in https://github.com/ruby/setup-ruby/issues/108#issuecomment-726009156, but I probably wasn't clear enough. @JonRowe Could you do that?

Maybe I should write this in the issue template: only file a bug here after you've filed a bug upstream, but it's hard to make a general rule that's still correct in all cases.

**Comment by deivid-rodriguez** [comment]
Yeah, no problem at all! It might be a bug in jruby, but since bundler 1 works, I guess we could probably do something to workaround it. I think it could be due to us stopping using `Dir.chdir` there and instead the `:chdir` parameter of `Kernel.system` and family.

If that was the issue, we could easily workaround it by using `git -C` which I'm sure has been supported for many many years.

**Comment by eregon** [comment]
Marking this issue as closed as there is outstanding 3rd party issue, that is not already worked around.
