### ISSUE TITLE
Ruby 3 on Windows

### ISSUE THREAD

**Issue by stevecheckoway** [ruby/setup-ruby#134]
I'm sure this is already on your radar, but supporting Ruby 3.0 on Windows would be helpful.

**Comment by MSP-Greg** [comment]
It's being worked on, another party handles the Windows Ruby releases.  For the time being, ruby-mingw or ruby-head are virtually the same as 3.0.0.

**Comment by eregon** [comment]
See https://github.com/oneclick/rubyinstaller2/issues/202

**Comment by eregon** [comment]
https://github.com/ruby/setup-ruby/releases/tag/v1.61.1
