### ISSUE TITLE
Running `bundle exec rake build` in JRuby on Windows fails

### ISSUE THREAD

**Issue by jcouball** [ruby/setup-ruby#137]
I am receiving an error when running a step that runs `bundle exec rake build` when specifying `runs-on: windows-latest` and `ruby-version: jruby-head` (I haven't tried other JRuby versions).  I think this is an issue with the `ruby/set-ruby` action not setting up the JRuby environment correctly on Windows.  I do not have a windows system so I am not able to effectively debug this issue myself. Apologies if this issue is my error.

The error I receive indicates that `bundle exec rake build` was run, but the `gem` executable can not be found:
```
IOError: Cannot run program "gem" (in directory "D:\a\jruby_test\jruby_test"): CreateProcess error=2, The system cannot find the file specified
```

I have created a sample project that shows the problem at: https://github.com/jcouball/jruby_test. 

In the sample project, a matrix build is defined that runs jobs for a combination of `[2.7, jruby-head]` Rubies and `[unbuntu-latest, windows-latest]` operating systems.

To run the GitHub actions for yourself to see the error, you might need to fork my sample repository and add a commit to the `main` branch to trigger the GitHub action.

The only combination that fails is `ruby-head` and `windows-latest`.

The expected result that that all four jobs in this matrix build succeed without any change.

**Comment by eregon** [comment]
The `Run Build` step runs on `pwsh`: https://github.com/jcouball/jruby_test/runs/1638104520?check_suite_focus=true#step:4:3

Probably using `shell: bash` would solve/workaround that issue.

Maybe the `rake` executable does not support being executed by pwsh. That seems possible, finding and choosing executables is complex on Windows, and probably JRuby or RubyGems forgets to add an extra `.bat` or so.

Since it works on CRuby though, and the logic to add the Ruby's `bin/` dir to PATH is the same, I'm pretty sure it's not an issue of ruby/setup-ruby though.

I think the future policy should be "if it fails on JRuby but works on CRuby, then it's most likely a JRuby bug, so report it there first".
Could you report it to https://github.com/jruby/jruby?

**Comment by eregon** [comment]
`shell: bash` doesn't help, it must be something else.

`bundle exec rake build` tries to build a gem, that works on CRuby, but fails on JRuby, so it must be a bug of JRuby or of RubyGems/Bundler.

**Comment by eregon** [comment]
The error from the original run is:
```
$ bundle exec rake build
rake aborted!
IOError: Cannot run program "gem" (in directory "D:\a\jruby_test\jruby_test"): CreateProcess error=2, The system cannot find the file specified
D:/a/jruby_test/jruby_test/vendor/bundle/jruby/2.6.0/gems/rake-12.3.3/exe/rake:27:in `<main>'
D:\a\jruby_test\jruby_test\vendor\bundle\jruby\2.6.0\bin\rake:23:in `<main>'
Tasks: TOP => build
(See full trace by running task with --trace)
```

So you should use `--trace` to know more, and that gives:
```
bundle exec rake build --trace
** Invoke build (first_time)
** Execute build
rake aborted!
IOError: Cannot run program "gem" (in directory "D:\a\jruby_test\jruby_test"): CreateProcess error=2, The system cannot find the file specified
org/jruby/RubyIO.java:4092:in `popen'
D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.2.4/lib/bundler/gem_helper.rb:212:in `block in sh_with_status'
org/jruby/RubyDir.java:445:in `chdir'
D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.2.4/lib/bundler/shared_helpers.rb:52:in `block in chdir'
D:/jruby-head/lib/ruby/stdlib/monitor.rb:235:in `mon_synchronize'
D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.2.4/lib/bundler/shared_helpers.rb:51:in `chdir'
D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.2.4/lib/bundler/gem_helper.rb:211:in `sh_with_status'
D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.2.4/lib/bundler/gem_helper.rb:201:in `sh'
D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.2.4/lib/bundler/gem_helper.rb:83:in `build_gem'
D:/jruby-head/lib/ruby/gems/shared/gems/bundler-2.2.4/lib/bundler/gem_helper.rb:47:in `block in install'
D:/a/jruby_test/jruby_test/vendor/bundle/jruby/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `block in execute'
org/jruby/RubyArray.java:1822:in `each'
D:/a/jruby_test/jruby_test/vendor/bundle/jruby/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `execute'
D:/a/jruby_test/jruby_test/vendor/bundle/jruby/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
D:/jruby-head/lib/ruby/stdlib/monitor.rb:235:in `mon_synchronize'
D:/a/jruby_test/jruby_test/vendor/bundle/jruby/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:194:in `invoke_with_call_chain'
D:/a/jruby_test/jruby_test/vendor/bundle/jruby/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:183:in `invoke'
D:/a/jruby_test/jruby_test/vendor/bundle/jruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:160:in `invoke_task'
D:/a/jruby_test/jruby_test/vendor/bundle/jruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `block in top_level'
org/jruby/RubyArray.java:1822:in `each'
D:/a/jruby_test/jruby_test/vendor/bundle/jruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `block in top_level'
D:/a/jruby_test/jruby_test/vendor/bundle/jruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:125:in `run_with_threads'
D:/a/jruby_test/jruby_test/vendor/bundle/jruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:110:in `top_level'
D:/a/jruby_test/jruby_test/vendor/bundle/jruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:83:in `block in run'
D:/a/jruby_test/jruby_test/vendor/bundle/jruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:186:in `standard_exception_handling'
D:/a/jruby_test/jruby_test/vendor/bundle/jruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:80:in `run'
D:/a/jruby_test/jruby_test/vendor/bundle/jruby/2.6.0/gems/rake-12.3.3/exe/rake:27:in `<main>'
org/jruby/RubyKernel.java:1049:in `load'
D:\a\jruby_test\jruby_test\vendor\bundle\jruby\2.6.0\bin\rake:23:in `<main>'
Tasks: TOP => build
```
Sounds likely the bug of JRuby not handling chdir + subprocesses very well.

**Comment by jcouball** [comment]
Thanks @eregon!

I added further tests to narrow down what was going on.  I found that in JRuby on Windows, `popen` does not respect PATHEXT at all. I opened jruby/jruby#6516 so the JRuby team is aware of the issue.

**Comment by jcouball** [comment]
@eregon in order to get the fix for this issue from JRuby, I need the ruby/jruby-dev-builder GitHub Action build to be re-enabled.  The daily scheduled GitHub Action to rebuild the JRuby artifacts have been suspended because of inactivity in the repository.

[This link](https://github.com/ruby/jruby-dev-builder/actions?query=workflow%3A%22JRuby+Dev+Builds%22) shows the message.

**Comment by eregon** [comment]
@jcouball Done, thanks for the notification. It's annoying that GitHub disables those every 60 days :/
