### ISSUE TITLE
Newer Bundler patch version is installed

### ISSUE THREAD

**Issue by manuelmeurer** [ruby/setup-ruby#138]
I noticed that not the exact Bundler version specified in Gemfile.lock is installed, but a newer patch version, if available.

In my case, I am using Bundler 2.2.3, then 2.2.4 is released, installed by `setup-ruby`, and then Rspec complains because it expects 2.2.3.

![pdf file might be nil · uplinkhq:app@f39eba7 2021-01-04 17-49-03](https://user-images.githubusercontent.com/16672/103558679-4e061280-4eb5-11eb-8f32-a8cba7443317.png)

I think the fix should be to run `gem install bundler -v 2.2.3` instead of `gem install bundler -v ~> 2.2.3`, so that the exact version is installed.

Happy to submit a PR! 😸

**Comment by eregon** [comment]
Good catch, yes PR welcome :)

Note that we still want values like `bundler: 1` or `bundler: 2` to work, so I guess we should use `-v 2.2.3` only if it's an exact version (3 digits).

**Comment by eregon** [comment]
Released in https://github.com/ruby/setup-ruby/releases/tag/v1.61.2
