### ISSUE TITLE
How to get the path to the installed ruby?

### ISSUE THREAD

**Issue by cmaughan** [ruby/setup-ruby#140]
The sonic-pi build uses a symlink to the ruby folder.  So I need a way to get the path to 'C:\ruby26-x64', or similar.  Is there an environment variable I can check, or some other way to get the path?

**Comment by eregon** [comment]
See https://github.com/ruby/setup-ruby/blob/324b8ce0e9717c5d0beb1c5ed6d7f2300f01cbbc/action.yml#L27-L29

**Comment by eregon** [comment]
You could also use `ruby -rrbconfig -e 'puts RbConfig::CONFIG["prefix"]'`.

**Comment by cmaughan** [comment]
so ${{env.ruby-prefix}} would be the path?

**Comment by eregon** [comment]
No, it's an output of the action, not an env var, see https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#steps-context

**Comment by cmaughan** [comment]
This is my attempt to use the 'step'.  It doesn't work; and I can't find any examples of how to use steps like this.  I label the setup-ruby with an id: which I hope gives it a step id, then I refer to ${{steps.ruby-inst.ruby-prefix}}, but this returns nothing.  Just a single example of how to get at the path would really help me here - has anyone done it before?
    - uses: ruby/setup-ruby@v1
      id: ruby-inst
      with:
        ruby-version: 2.7

    - name: Setup Ruby
      working-directory: ${{github.workspace}}/app/gui/qt
      shell: cmd
      run: |
          gem install win32-process
          gem install rugged --version 0.27.1
          gem install ffi
          cd ..\..\server\native
          mklink /d ruby ${{steps.ruby-inst.ruby-prefix}}

**Comment by eregon** [comment]
`${{ steps.ruby-inst.outputs.ruby-prefix }}`

Such questions should be asked on https://github.community/c/code-to-cloud/github-actions/41, though, this is not the right place to ask how to use GitHub Actions.

**Comment by cmaughan** [comment]
Apologies for wasting your time.  Your 1 line solution sorted it, thanks :)
