### ISSUE TITLE
Allow reading ruby version from gemspec

### ISSUE THREAD

**Issue by donv** [ruby/setup-ruby#147]
Hi!

Gem repositories typically do not use `.ruby-version` to set the required ruby version.  Rather they use the `required_ruby_version` setting in the gemspec file.

Could you read this ruby version from the gemspec as a secondary source when `.ruby-version` is not present?  This is what `rubocop` now does and enforces.

It would spare us from storing the required ruby version in a duplicate location (.github/workflows/ruby.yml).

**Comment by eregon** [comment]
For a gem, most people seem to want to test multiple Ruby versions, and I think that wouldn't be useful in that most common case.
Also the gemspec is a Ruby file, so there seem to be no good and reliable way to parse it.

**Comment by donv** [comment]
The case you mention is common, but it is also more advanced and complex.  It would be nice to be able to start simpler and then advance later.

The common case you mentioned also assumes open source.  For closed source gems the number of rubies to test against is often just one.

The required ruby version in a gemspec can be complex to parse with perfect semantics, but a simple regex like Rubocop does it should suffice.

In my case I can create a `.ruby-version` with with content `2.5` and then read this into the gemspec with

```ruby
spec.required_ruby_version = "~>#{File.read('.ruby-version').chomp}"
```

but this is more complex than just having the version in the gemspec.

No biggie.  😄

**Comment by eregon** [comment]
For curiosity, do you have a link the Rubocop's Regexp handling that?

I think this feature is too niche and fundamentally unreliable (parsing Ruby code with a regexp, guessing the gemspec name, etc) to be worth it at this time, so I'd like to close this.
Having the version also in the CI workflow doesn't seem a big issue, e.g. when supporting a new Ruby version it seems sensible to me to update the workflow too and of course test that it works with the new version.
Thanks for filing this issue though.
