### ISSUE TITLE
Ruby 2.3.0 bundler failing after PR #146 just merged

### ISSUE THREAD

**Issue by waltjones** [ruby/setup-ruby#148]
https://github.com/ruby/setup-ruby/pull/146 is failing for me on Ruby 2.3.0:

```
Run ruby/setup-ruby@v1
Downloading Ruby
Extracting Ruby
Installing Bundler
  /opt/hostedtoolcache/Ruby/2.3.0/x64/bin/gem install bundler -v ~> 2 --no-document
  ERROR:  Error installing bundler:
  	bundler requires RubyGems version >= 2.5.2. Try 'gem update --system' to update RubyGems itself.
  Took   0.39 seconds
Error: The process '/opt/hostedtoolcache/Ruby/2.3.0/x64/bin/gem' failed with exit code 1
```

My github action is straightforward:
```
uses: ruby/setup-ruby@v1
with:
  ruby-version: 2.3.0
```

**Comment by bpinto** [comment]
@waltjones Could it be that your Gemfile.lock does not have a bundler version specified? If that's the case you could force it to use version 1 as it was previously with:

```
        with:
          ruby-version: 2.3
          bundler: '1' # Force ruby version
```

**Comment by bpinto** [comment]
Looking at `https://github.com/rollbar/rollbar-gem/blob/master/.github/workflows/ci.yml` I think of two ways to handle it.

1. Split step `Setup Ruby > 2.0` one for ruby >= 2.4 and other for lower versions.
2. [Including](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-including-additional-values-into-combinations) bundler version in matrix. I see you are already using `include` there, so you would use it to add `bundler: '2'` or `bundler: '1'`.

**Comment by bpinto** [comment]
This patch tries to implement (2) above. I haven't tested it.

```
diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
index b1736dd..f0ba947 100644
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -12,6 +12,7 @@ jobs:
     strategy:
       matrix:
         ruby-version: [2.2.10, 2.3.0, 2.3.8, 2.4.5, 2.5.3, 2.6.0]
+        bundler-version: 'default'
         gemfile:
           - gemfiles/rails42.gemfile
           - gemfiles/rails50.gemfile
@@ -32,6 +33,9 @@ jobs:
           - gemfile: gemfiles/rails60.gemfile
             ruby-version: 2.4.5
         include:
+          - gemfile: gemfiles/rails52.gemfile
+            ruby-version: 2.3.0
+            bundler-version: '1'
           - gemfile: gemfiles/rails41.gemfile
             ruby-version: 2.3.0
           - gemfile: gemfiles/rails41.gemfile
@@ -67,6 +71,7 @@ jobs:
         uses: ruby/setup-ruby@v1
         if: ${{ matrix.ruby-version != '2.0.0' }}
         with:
+          bundler: ${{ matrix.bundler-version }}
           ruby-version: ${{ matrix.ruby-version }}
 
       - name: Setup Ruby 2.0.0
```

**Comment by bpinto** [comment]
Meanwhile, I'm trying to figure out if it's only ruby 2.3.0 that's failing, I have confirmed it works on ruby 2.3.3.

**Comment by waltjones** [comment]
@bpinto Many thanks. I agree this looks like it would work. I'll try it.

**Comment by eregon** [comment]
Right, it sounds like Ruby 2.3.0 shipped with a too old RubyGems.

Please use Ruby 2.3.3 in Windows (https://github.com/ruby/setup-ruby/blob/a358e49b568cae818fdbc8e6fdf70c8f9400e413/windows-versions.js#L6) and Ruby 2.3.8 on Linux/macOS, or simply use `ruby-version: 2.3`.

**Comment by bpinto** [comment]
@eregon I haven't been able to confirm ruby 2.3.0 is the only affected yet, but do you want me to submit another PR with forcing bundler: '1' on ruby 2.3.0 specifically?

**Comment by eregon** [comment]
I'll test here to see which 2.3.x versions are affected:
https://github.com/eregon/setup-ruby/actions/runs/512656033
https://github.com/eregon/setup-ruby/actions/runs/512658078

**Comment by eregon** [comment]
Yes, indeed, could you make a PR with that?

**Comment by eregon** [comment]
Fixed and released in https://github.com/ruby/setup-ruby/releases/tag/v1.64.1
