### ISSUE TITLE
Providing ruby-head builds

### ISSUE THREAD

**Issue by eregon** [ruby/setup-ruby#15]
@MSP-Greg, @larskanis (https://github.com/eregon/use-ruby-action/issues/10#issuecomment-576031376) and @ioquatix (https://github.com/actions/setup-ruby/issues/44#issuecomment-570372526) have already mentioned interest in this.

I recently added support for `truffleruby-head` so it shouldn't be too hard.

Current plan is:
* https://github.com/eregon/ruby-dev-builder builds for Ubuntu & macOS
* Use https://github.com/oneclick/rubyinstaller2/releases/tag/rubyinstaller-head for Windows

**Comment by MSP-Greg** [comment]
Good idea.  It would certainly be helpful to run all the test suites, and also a CLI check on the install folder, as there was a time when the included gem binstubs broke on Windows...

I'm working on moving ruby-loco to a GitHub release, along with an mswin build, so that's also an option.

**Comment by eregon** [comment]
> Good idea. It would certainly be helpful to run all the test suites, and also a CLI check on the install folder, as there was a time when the included gem binstubs broke on Windows...

I'm running `test-all` and `test-spec` currently:
https://github.com/eregon/ruby-dev-builder/blob/fcbf2cda653d3c34ba405c1e9bb291c87e79ab9d/.github/workflows/build.yml#L79-L80
What do you mean by a CLI check on the install folder ?

**Comment by MSP-Greg** [comment]
> What do you mean by a CLI check on the install folder ?

Check that `gem`, `rake`, `bundle`, etc commands work, I just check to see if they work with a `--version` argument.

That's one issue with the normal CI, it really doesn't check that the install folder is set up correctly.  Most of time, everything is ok, but there have been times...

> I'm running test-all and test-spec currently

Re test-spec, I think it will run from the install folder (without make).

**Comment by eregon** [comment]
Implemented in f5483241dbda2b55868af79144ee5c0cc16cc599, it was fairly easy.

https://github.com/eregon/ruby-dev-builder needs a way to build ~daily and remove old releases, that's still to do, currently it's triggered manually.

**Comment by eregon** [comment]
I now got the automated daily (or rather nightly) builds: https://github.com/eregon/ruby-dev-builder/commit/88794dda64e36a60eb515f340024aaf0916135f9

So now the only thing missing is some cleanup to remove older releases.

**Comment by MSP-Greg** [comment]
I've now got fully tested mingw & mswin builds in ruby-loco, stored in a release.  Since ruby/ruby tests against mswin, having one available for CI might be helpful.  I have not changed it to run cron jobs yet.

Re the single release (vs multiple releases), I messed around with it, and if one uploads the new binary with a different name, then delete the old binary, then renames the new one, the delete/rename typically takes around 300 to 400 mS, with an occasional peak time of around 900 mS.  

Using one release allows for a single stable URI, so I think I'll take the risk.

I used an embedded action, as it also updates `ruby -v` and the SHA512 checksum in the release notes.

**Comment by MSP-Greg** [comment]
@eregon

While working on OpenSSL & mswin, got the following, running a rake script to install a few gems, Ubuntu-18.04 ruby-head.

The workflow ran Ubuntu-18.04 & macOS, Rubies 2.3 thru ruby-head.  Ubuntu-18.04 ruby-head was the only job with the failure...

```
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
rake-compiler not installed. Run 'rake install_dependencies' to install testing dependency gems.
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/x86_64-linux-gnu/ruby/2.5.0/openssl.so: warning: already initialized constant OpenSSL::VERSION
/home/runner/work/ruby-openssl/ruby-openssl/lib/openssl/version.rb:4: warning: previous definition of VERSION was here
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
rake aborted!
Gem::FilePermissionError: You don't have write permissions for the /var/lib/gems/2.5.0 directory.
/home/runner/work/ruby-openssl/ruby-openssl/Rakefile:40:in `block (2 levels) in <top (required)>'
/home/runner/work/ruby-openssl/ruby-openssl/Rakefile:36:in `each'
/home/runner/work/ruby-openssl/ruby-openssl/Rakefile:36:in `block in <top (required)>'
Tasks: TOP => install_dependencies
(See full trace by running task with --trace)
Installing rake (>= 0) ... (found 12.3.1)
Installing rake-compiler (>= 0) ... 
##[error]Process completed with exit code 1.
```

**Comment by eregon** [comment]
That's the default `ruby`, not a bug of this action.
Probably you installed a system ruby with `apt-get`?

**Comment by eregon** [comment]
ruby-head builds work fine now (AFAIK).

In https://github.com/ruby/ruby-dev-builder I'm creating a draft release, building on the various platforms, publishing the release, and cleaning old releases automatically.
So all is automated and there are also fixed links to download such as:
https://github.com/ruby/ruby-dev-builder/releases/latest/download/ruby-head-ubuntu-18.04.tar.gz

**Comment by MSP-Greg** [comment]
> Probably you installed a system ruby with apt-get?

Here's the [workflow](https://github.com/ruby/openssl/blob/5907419710eff1d9243ea59d74b461a5c3418dc4/.github/workflows/ubuntu-macos.yml) in ruby/openssl

I haven't looked at the rakefile, but it worked previously, and all other jobs are fine?  I'll have another 
 look, I was rushing out the door earlier...

**Comment by eregon** [comment]
@MSP-Greg It would be much more useful if you just point me to the PR and Action run:
https://github.com/ruby/openssl/pull/319

Let's discuss there or please open a new issue.
Not sure what's wrong at first sight.

**Comment by MSP-Greg** [comment]
I apologize.  I should have waited until I had time to look at it...

**Comment by eregon** [comment]
The problem is bundled gems were missing, fixed now in https://github.com/ruby/ruby-dev-builder/commit/7bc20bb53e658713c2c2144d9b3da5ce072b464d
https://github.com/ruby/openssl/pull/319#issuecomment-583783941
