### ISSUE TITLE
Naming of `ruby-head` version

### ISSUE THREAD

**Issue by ShockwaveNN** [ruby/setup-ruby#151]
I notice a little difference with how version numbering is formed for installing ruby head via `rvm` and using `ruby-head` as GitHub Actions

1. I compiled `ruby-head` locally with `rvm install ruby-head` command
This result this output for `ruby -v`
```
# ruby -v
ruby 3.1.0dev (2021-02-01T10:54:21Z master 1cdae49d39) [x86_64-linux]
```

2. While using `ruby-head` in GitHub actions - I'm not 100% sure, but if any additional check is needed - I assume its verison is
```
ruby 3.1.0p-1
```

I noticed this error because a lot of my projects test `ruby-head` just in case, and I noticed `nokogiri` is not installing on ruby-head on any of them with this error:
```
Fetching gem metadata from https://rubygems.org/.........
nokogiri-1.11.1-x86_64-linux requires ruby version < 3.1.dev, >= 2.5, which is
incompatible with the current version, ruby 3.1.0p-1
```

But `nokogiri` metadata seems correct
[`spec.required_ruby_version = ">= 2.5.0"`](https://github.com/sparklemotion/nokogiri/blob/main/nokogiri.gemspec#L40)

So, I'll assume this is differece in `3.1.0dev` and `3.1.0p-1` strings

**Comment by MSP-Greg** [comment]
> But nokogiri metadata seems correct

That's from the 'standard' gem.  All of the pre-compiled gems (like `nokogiri-1.11.1-x86_64-linux`) have an additional 'required_ruby_version' of "< 3.1.dev".

To install Nokogiri on Ruby head with RubyGems, you need to add '--platform=ruby', which forces the installation of `nokogiri-1.11.1`.

**Comment by ShockwaveNN** [comment]
@MSP-Greg Oh, thanks. In that case I'll close this issue

**Comment by eregon** [comment]
You can run `ruby -v` in your workflow, and you'll see it's the same as when compiled locally.
