### ISSUE TITLE
JRuby 9.2.16.0 

### ISSUE THREAD

**Issue by MSP-Greg** [ruby/setup-ruby#156]
[`JRuby 9.2.1.16.0`](https://www.jruby.org/2021/03/03/jruby-9-2-16-0.html) has been released, which adds back racc, which caused an issue with running RuboCop.

Not critical...

**Comment by eregon** [comment]
I'll add it tonight.

**Comment by MSP-Greg** [comment]
JFYI, MSYS2 can have chicken/egg issues (not sure how to phrase that), and I've had to do two releases for setup-ruby-pkgs in the last week.  Please feel free to ping me if you notice Actions Windows problems...

chicken/egg - what came first?  With MSYS2, the package database is secure, but they also release updates to the approved GPG keys.  So, the current Actions database doesn't contain the updated key package, so it can't be installed, and one can't update the database because it's secured with a new GPG key.  So, I have to install the new keys manually until Actions updates their Windows' images with the new files.  I think that made sense...

**Comment by eregon** [comment]
Done: https://github.com/ruby/setup-ruby/commit/034294ac9150f471c8dd554f05f0685312e7f7bd
