### ISSUE TITLE
Old Windows Rubies - BinTray

### ISSUE THREAD

**Issue by MSP-Greg** [ruby/setup-ruby#171]
@eregon,

Good afternoon/evening.  This morning, I was running some Actions and Windows Rubies 2.2 & 2.3 failed.  The failures were all downloads from BinTray.

I have a few of the files locally, the last versions of Ruby 2.1, 2.2, & 2.3, along with a DevKit that has ragel & openssl pre-installed.

I uploaded them to a repo of mine that I used long ago when Actions was still in beta.  With the changes, CI here passes.

Do you want a PR for the changes?  I pinged you with a thread in oneclick, this hopefully is just a temp fix until all the old Ruby files, MSYS packages, etc find a home on GitHub...

**Comment by eregon** [comment]
I would prefer to use release assets files from https://github.com/oneclick/rubyinstaller like newer releases if possible:
https://github.com/oneclick/rubyinstaller/issues/400#issuecomment-826974532
Do we need any file besides the ruby archives for those versions, and 
https://github.com/ruby/setup-ruby/blob/6f2028eda533117e2ab7a1108e3bb40b01f481bc/windows.js#L96
?

**Comment by MSP-Greg** [comment]
Understood.  This is just temporary.  Yes, we need the DevKit also.  See https://github.com/MSP-Greg/ruby-setup-ruby/tree/00-msys, the last two commits:

[windows-versions.js - change uri from BinTray for 2.1 thru 2.3](https://github.com/MSP-Greg/ruby-setup-ruby/commit/1f724dce3e93)
[windows.js - change old DevKit uri from BinTray](https://github.com/MSP-Greg/ruby-setup-ruby/commit/2d2a3e9a7fbc)

CI is [here](https://github.com/MSP-Greg/ruby-setup-ruby/actions/runs/786184808)
