### ISSUE TITLE
Regarding installing a downgraded version of ruby

### ISSUE THREAD

**Issue by Jassi10000** [ruby/setup-ruby#178]
I have followed the steps to setup ruby 
but the issue am facing is that , for some personal use , I had to use a lower version of ruby and for that I used "rvm' 
but am not able to degrade it  
even when I have installed all the necessary tools

**Comment by MSP-Greg** [comment]
@Jassi10000

This repo contains code that allows installation and configuration of Ruby when using the GitHub Actions cloud CI service.

You didn't mention Actions...

**Comment by eregon** [comment]
Seems unrelated.
Maybe you mean to file an issue to https://github.com/rvm/rvm? (With better details and reproduction instructions please!)
