### ISSUE TITLE
Cannot  find 3.0.1 for Ubuntu 20.04

### ISSUE THREAD

**Issue by JorgeDDW** [ruby/setup-ruby#180]
Hey there!
According to these images, it cannot find a ruby 3.0.1 for Ubuntu 20.04, any idea why?

![image](https://user-images.githubusercontent.com/811257/119721256-f30b9280-be38-11eb-96cf-f0ad33d43864.png)

**Comment by MSP-Greg** [comment]
@JorgeDDW

Please consider using `ruby/setup-ruby@v1`. The commit you're using was titled 'Add Ruby 3.0.0'...

**Comment by JorgeDDW** [comment]
Great!
Thanks for the tips! 
I fix my issues by updating the ruby.yml file.
