### ISSUE TITLE
Missing ruby 2.7.3 on ubuntu-latest (20.04) ?

### ISSUE THREAD

**Issue by kevinhq** [ruby/setup-ruby#183]
Any reason why it's skipped? is it possible to add it?

**Comment by MSP-Greg** [comment]
Support for Ubuntu 2.7.3 was added in commit d2f535c1eda on 05-Apr.

Without more information (Actions job log), can't help.  Maybe the same issue as #180?

**Comment by kevinhq** [comment]
close this. my bad: i don't read the readme carefully.
