### ISSUE TITLE
jruby-head does not include bundler

### ISSUE THREAD

**Issue by marcotc** [ruby/setup-ruby#186]
While trying to use jruby-head for the first time today I got this error:

```
Unable to locate executable file: bundle. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

with this (now reduced) job configuration:

```yaml
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - run: touch Gemfile
      - uses: ruby/setup-ruby@1328335dba6b565b31a0a3e39adb33d7b7470fbc
        with:
          ruby-version: jruby-head
          bundler-cache: true
```

My full output:

```
$ act -j test
[test.yaml/test] 🚀  Start image=catthehacker/ubuntu:act-20.04
[test.yaml/test]   🐳  docker run image=catthehacker/ubuntu:act-20.04 platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[test.yaml/test] ⭐  Run touch Gemfile
[test.yaml/test]   ✅  Success - touch Gemfile
[test.yaml/test] ⭐  Run ruby/setup-ruby@1328335dba6b565b31a0a3e39adb33d7b7470fbc
[test.yaml/test]   ☁  git clone 'https://github.com/ruby/setup-ruby' # ref=1328335dba6b565b31a0a3e39adb33d7b7470fbc
[test.yaml/test]   🐳  docker cp src=~/.cache/act/ruby-setup-ruby@1328335dba6b565b31a0a3e39adb33d7b7470fbc/ dst=~/work/dd-trace-rb/_actions/ruby-setup-ruby@1328335dba6b565b31a0a3e39adb33d7b7470fbc/
[test.yaml/test]   ❓  ::group::Downloading Ruby
| https://github.com/ruby/jruby-dev-builder/releases/latest/download/jruby-head-ubuntu-20.04.tar.gz
[test.yaml/test]   💬  ::debug::Downloading https://github.com/ruby/jruby-dev-builder/releases/latest/download/jruby-head-ubuntu-20.04.tar.gz
[test.yaml/test]   💬  ::debug::Destination /tmp/e3658fc6-4d84-46f5-aa02-1934f2778731
[test.yaml/test]   💬  ::debug::download complete
| Took   1.63 seconds
[test.yaml/test]   ❓  ::endgroup::
[test.yaml/test]   ❓  ::group::Extracting Ruby
| [command]/usr/bin/tar -xz -C /root/.rubies -f /tmp/e3658fc6-4d84-46f5-aa02-1934f2778731
| Took   0.30 seconds
[test.yaml/test]   ❓  ::endgroup::
[test.yaml/test]   ❓  ::group::Installing Bundler
| Using Bundler 2 shipped with jruby-head
| Took   0.00 seconds
[test.yaml/test]   ❓  ::endgroup::
[test.yaml/test]   ❓  ::group::bundle install
| Took   0.00 seconds
[test.yaml/test]   ❓  ::endgroup::
[test.yaml/test]   ❗  ::error::Unable to locate executable file: bundle. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
[test.yaml/test]   ❌  Failure - ruby/setup-ruby@1328335dba6b565b31a0a3e39adb33d7b7470fbc
```

This happens when running in GitHub actions as well.

I checked the downloaded jruby build, jruby-head-ubuntu-20.04.tar.gz, and it does not include `bin/bundle`. This seems intentional given this commit: https://github.com/ruby/jruby-dev-builder/commit/83acf48c1ee8b97dee640d6b8290669f263fd764

Interestingly, `setup-ruby` thinks that bundler 2 is installed (see output "Using Bundler 2 shipped with jruby-head" above).

Since the removal of `bin/bundle` from JRuby seems to have happened over [2 years ago (since version 9.2.8.0)](https://github.com/jruby/jruby/commit/bd67051add502b16744910c5897098ed589b6954), I'm not sure that this removal is the root cause.

Judging by the script that outputs ["Using Bundler 2 shipped with jruby-head"](https://github.com/ruby/setup-ruby/blob/b161cb92f0e2f28d992f04f38fff204d84132c47/bundler.js#L85-L88), and furthermore the list of [Ruby versions with Bundler 2 as default](https://github.com/ruby/setup-ruby/blob/b161cb92f0e2f28d992f04f38fff204d84132c47/common.js#L63-L64) I believe this is a miscategorization that JRuby head already ships with Bundler 2.

**Comment by marcotc** [comment]
I'm open to submitting a PR, but I'm not sure if the fix is in this repository or `ruby/jruby-dev-builder`. (I think it's unlikely that the issue is at `jruby/jruby`)

**Comment by MSP-Greg** [comment]
@marcotc

Please try using:
```
      - run: touch Gemfile
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: jruby-head
          bundler-cache: true
```


I think this is the fourth issue in as many days with people pinning to a commit of the repository.  The first three issues were essentially fixed by using `ruby/setup-ruby@v1`.

Might I ask, what led you to pin to a commit?

**Comment by eregon** [comment]
@headius Did JRuby stop shipping Bundler? In which release & commit?

**Comment by eregon** [comment]
> (I think it's unlikely that the issue is at `jruby/jruby`)

Why not? It seems a breaking change in JRuby master builds as far as I can tell.

**Comment by eregon** [comment]
Here is a build from 3 days ago, which seems to clearly indicate `bin/bundle` did exist then:
https://github.com/ruby/setup-ruby/runs/2756559281?check_suite_focus=true#step:3:18

**Comment by eregon** [comment]
I guess it might be related to https://github.com/jruby/jruby/pull/6687
That PR description is:

> Bundler is included as a default gem in 9.3+ so it is already available.

So the assumption here that Bundler is bundled for 9.3+ and dev builds seems still correct, but somehow the dev archive does not contain `bin/bundle` anymore.

**Comment by MSP-Greg** [comment]
JFYI,  I mentioned the bin/bundle file above, referring to the release 'builds-20210608-191714'.

Since bin files have been an issue from time to time, this is not that.  No Bundler files are in the build.  Or, it's not just the bin file that's missing...

**Comment by eregon** [comment]
BTW, the logic to rely on the head/9.3 Bundler comes from @enebo in https://github.com/ruby/setup-ruby/pull/164.

**Comment by MSP-Greg** [comment]
I also checked the macos build, no Bundler, so not OS specific...

**Comment by eregon** [comment]
I'd like to wait for @headius or @enebo's answer here.
But if it takes too long I guess we can just start installing Bundler for `jruby-head`, if `bin/bundle` does not exist.
The problem with latest Bundler + someruby-head is that the latest Bundler might not work on it, and so it seems generally best to use the Bundler shipped with someruby-head. But if there isn't one, nothing can be done about that.

**Comment by eregon** [comment]
It was an issue in the script to pick the latest jruby snapshot (https://github.com/ruby/jruby-dev-builder/blob/master/find-jruby-head-url.rb and https://github.com/jruby/jruby/issues/6713). Should be all good now.

**Comment by eregon** [comment]
CI passes now on `jruby-head`: https://github.com/ruby/setup-ruby/runs/2795846422
