### ISSUE TITLE
Detect ImageOS on self-hosted runners automatically

### ISSUE THREAD

**Issue by reichhartd** [ruby/setup-ruby#187]
We run our actions on a self-hosted macOS system or Ubuntu system, depending on which is currently underutilized. It would be handy if the `setup-ruby` action could automatically detect the running operating system.
This is possible if you look at this action: [GitHub Actions runner OS system information](https://github.com/kenchan0130/actions-system-info)

**Comment by eregon** [comment]
https://github.com/ruby/setup-ruby/blob/fd1a6a00ca9fbf3fb687b271c4d41a06e2222e2a/README.md#using-self-hosted-runners says that your runner should set `ImageOS`, just like GH-hosted runners do.
I guess other actions and things might rely on `ImageOS` being set too.

You'd want to detect that automatically? It seems difficult, and I wouldn't want to add a dependency for that.

**Comment by reichhartd** [comment]
Valid point, makes more sense.
I overread the "on the runner", and set the environment variable in the GitHub action file.
Sorry for the issue.
