### ISSUE TITLE
Control over bundle install

### ISSUE THREAD

**Issue by noraj** [ruby/setup-ruby#201]
In a gemspec file it's common to have `add_runtime_dependency` and `add_development_dependency` to create a `runtime` and `development` group in Gemfile. Following [this answer](https://stackoverflow.com/questions/64486486/how-to-work-with-gemspec-add-runtime-dependency-and-bundle-install), one that wan to only install runtime dependencies could do one of the following:

```bash
# Deprecated
bundle install --without development
# More future proof
bundle config set --local without 'development'
bundle install
```

Maybe the other way around work too

```bash
# Deprecated
bundle install --with runtime
# More future proof
bundle config set --local with 'runtime'
bundle install
```

The issue is that this template seems to do a classic `bundle install` and doesn't provide any way to configure it.

Also https://github.com/ruby/setup-ruby/issues/38 wouldn't have been an issue if we would have been able to run:

```
# Deprecated
bundle install --deployment
# More future proof
bundle config set --local deployment true
bundle install
```

**Comment by noraj** [comment]
I see at https://github.com/actions/starter-workflows/blob/master/ci/ruby.yml and https://docs.github.com/en/actions/guides/building-and-testing-ruby that the use a `bundle install` step after `ruby/setup-ruby`, does this mean it will overwrite the default made by `ruby/setup-ruby`?

**Comment by eregon** [comment]
> https://github.com/actions/starter-workflows/blob/master/ci/ruby.yml

That's an old master branch.

Here is the current state: https://github.com/actions/starter-workflows/blob/main/ci/ruby.yml

I believe https://github.com/ruby/setup-ruby#bundle-config already answers your questions.

**Comment by noraj** [comment]
> I believe https://github.com/ruby/setup-ruby#bundle-config already answers your questions.

Thanks, I'll give it a try.
