### ISSUE TITLE
setup-ruby step fails on `macos-10.15` using truffleruby-19.3.1

### ISSUE THREAD

**Issue by dentarg** [ruby/setup-ruby#206]
Code: https://github.com/dentarg/addressable/blob/2e9d46069232aa93c58f1f09859856fac2a64e68/.github/workflows/test.yml

Logs: https://github.com/dentarg/addressable/runs/3168625628?check_suite_focus=true#step:5:25

```
Installing Bundler
  /Users/runner/.rubies/truffleruby-19.3.1/bin/gem install bundler -v ~> 2 --no-document
  ERROR:  Loading command: install (RuntimeError)
  	the OpenSSL C extension was compiled against a different libssl than the one used on this system - recompile by running /Users/runner/.rubies/truffleruby-19.3.1/lib/truffle/post_install_hook.sh (Library "/usr/local/opt/openssl@1.0.2t/lib/libssl.1.0.0.dylib" does not exist.)
  ERROR:  While executing gem ... (NoMethodError)
      undefined method `invoke_with_build_args' for nil:NilClass
  Took   4.71 seconds
Error: The process '/Users/runner/.rubies/truffleruby-19.3.1/bin/gem' failed with exit code 1
```

**Comment by eregon** [comment]
> the OpenSSL C extension was compiled against a different libssl than the one used on this system - recompile by running /Users/runner/.rubies/truffleruby-19.3.1/lib/truffle/post_install_hook.sh (Library "/usr/local/opt/openssl@1.0.2t/lib/libssl.1.0.0.dylib" does not exist.)

I think the GitHub runners removed `/usr/local/opt/openssl@1.0.2t/lib/libssl.1.0.0.dylib` on macOS, which would explain this error.
We could try to recompile against whatever openssl version is available on macOS runners now.
TruffleRuby 19.3 is unsupported by now though, so maybe not worth it.

**Comment by eregon** [comment]
I rebuilt 19.3.0 and 19.3.1, should be good now: https://github.com/ruby/ruby-builder/runs/3171238099?check_suite_focus=true
