### ISSUE TITLE
setup-ruby step fails on ubuntu using truffleruby-19.3.1

### ISSUE THREAD

**Issue by dentarg** [ruby/setup-ruby#207]
Code: https://github.com/dentarg/addressable/blob/2e9d46069232aa93c58f1f09859856fac2a64e68/.github/workflows/test.yml

Logs: 

`ubuntu-18.04` https://github.com/dentarg/addressable/runs/3168625644?check_suite_focus=true#step:5:22

```
Installing Bundler
  /home/runner/.rubies/truffleruby-19.3.1/bin/gem install bundler -v ~> 2 --no-document
  ERROR:  Error installing bundler:
  	"bundle" from bundler conflicts with /home/runner/.rubies/truffleruby-19.3.1/bin/bundle
  Took  39.66 seconds
Error: The process '/home/runner/.rubies/truffleruby-19.3.1/bin/gem' failed with exit code 1
```

`ubuntu-20.04` https://github.com/dentarg/addressable/runs/3168625659?check_suite_focus=true#step:5:23

````
Installing Bundler
  /home/runner/.rubies/truffleruby-19.3.1/bin/gem install bundler -v ~> 2 --no-document
  ERROR:  Error installing bundler:
  	"bundle" from bundler conflicts with /home/runner/.rubies/truffleruby-19.3.1/bin/bundle
  Took  44.58 seconds
Error: The process '/home/runner/.rubies/truffleruby-19.3.1/bin/gem' failed with exit code 1
````

**Comment by eregon** [comment]
There is https://github.com/ruby/setup-ruby/blob/0c7e9c4d53d534e2c72b5b06535a3817d6d39fe1/bundler.js#L89-L90 so using `with: bundler: 1` should work with TruffleRuby 19.3.

Bundler 2 doesn't work on TruffleRuby 19.3 and I don't think it's fixable.
In short, TruffleRuby 19.3 is not supported anymore, please use more recent TruffleRuby versions.

**Comment by dentarg** [comment]
Should we update the README with something? (Remove TruffleRuby 19.3 or add caveat about `with: bundler: 1`?) Or did https://github.com/ruby/setup-ruby/commit/0997e21bf3d0273e9e73c4bd6e02ee5f772ea8fa fix this?
