### ISSUE TITLE
Cache not respected across branches with no Gemfile.lock changes

### ISSUE THREAD

**Issue by robzolkos** [ruby/setup-ruby#216]
I am confused about how the caching is meant to work.

If I do a PR in branch A,  then the gems will bundle,  and subsequent commits to the branch will use the cache
Once I merge PR into master/main  and branch off that with branch B when I do another PR (no Gemfile changes) then it will not use the cache.

Is this intended behavior?  I am basically wanting the cache to be used across all branches/builds unless the Gemfile.lock changes.

**Comment by eregon** [comment]
The branch is not part of the cache key in this action: https://github.com/ruby/setup-ruby/blob/57d46d78b7d959dc4a248024a29bb17d4e357e5c/bundler.js#L184
It is expected the cache is reused across branches, but it might not be reused across repository forks.
In any case, this is independent of this action, so I close this issue.
See https://github.com/actions/cache#cache-scopes

**Comment by robzolkos** [comment]
> It is expected the cache is reused across branches

This is my point.  It is *not* being reused across branches.

**Comment by eregon** [comment]
Feel free to report to actions/cache, nothing I can do here.
In any case, logs will be needed.

**Comment by robzolkos** [comment]
For those reading this the solution was to also have the cache installed in your master/main branch (mine wasnt). 

Here is SO post that helped https://stackoverflow.com/a/66632107
