### ISSUE TITLE
Remove binaries for Ubuntu 16.04

### ISSUE THREAD

**Issue by eregon** [ruby/setup-ruby#221]
Ubuntu 16.04 is no longer supported on GitHub Actions: https://github.com/actions/virtual-environments/issues/3287
So we can remove 16.04 binaries from https://github.com/ruby/ruby-builder/releases and remove any 16.04-specific code.
Will wait at least until October 18, 2021 as Azure DevOps might rely on those.

I guess self-hosted runners could rely on those if the self-hosted runner uses Ubuntu 16.04.
I think we should drop them, as new Rubies can't be built on 16.04 in GitHub Actions anyway, and supporting a platform we can't test is not reasonable.

**Comment by eregon** [comment]
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources says:
> Deprecated and limited to existing customers only. Migrate to Ubuntu 20.04.

Not sure what that means.

**Comment by hsbt** [comment]
I'm +1 to remove it after Oct 18, 2021. In fact, I removed Ubuntu 16.04 from https://rubyci.org/. Ruby core team are not guarantee to support the all versions of Ruby with Ubuntu 16.04.

**Comment by eregon** [comment]
Done, 375 builds -> 299 builds for https://github.com/ruby/ruby-builder/releases/tag/toolcache
