### ISSUE TITLE
Add support for Ruby 2.7.5 on Ubuntu-20.04

### ISSUE THREAD

**Issue by jlm** [ruby/setup-ruby#238]
Please add support for the latest Ruby versions in the 2.7 stream.

**Comment by hsbt** [comment]
We add it at https://github.com/ruby/setup-ruby/commit/cf1a6dd2d8563b59c7007e381836fd252ab2ac5b

**Comment by MSP-Greg** [comment]
@jlm

From one of your repos:

```
uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
```

Unless one has a very specific concern, one should not lock to a particular commit for most GitHub actions.  The preferred string is:
```
uses: ruby/setup-ruby@v1
```

**Comment by jlm** [comment]
> Unless one has a very specific concern, one should not lock to a particular commit for most GitHub actions. The preferred string is:
> 
> ```
> uses: ruby/setup-ruby@v1
> ```

Thanks. I'll change it.  FYI those version strings are generated by the Actions->New Workflow scripts, such as Publish Docker Container.  I wondered why it was using very specific versions rather than tagged releases.

**Comment by dentarg** [comment]
@jlm The maintainers know about that and have tried to change it, but GitHub does not (currently) want to, see https://github.com/actions/starter-workflows/pull/823
