### ISSUE TITLE
jruby-9.3.2.0 is released but not supported

### ISSUE THREAD

**Issue by klobuczek** [ruby/setup-ruby#240]
This issue https://github.com/ruby/setup-ruby/issues/220 still seems to be unresolved.
```
Run ruby/setup-ruby@v1
Error: Unknown version 9.3.2.0 for jruby on ubuntu-18.04
        available versions for jruby on ubuntu-18.04: 9.1.17.0, 9.2.9.0, 9.2.10.0, 9.2.11.0, 9.2.11.1, 9.2.12.0, 9.2.13.0, 9.2.14.0, 9.2.15.0, 9.2.16.0, 9.2.17.0, 9.2.18.0, 9.2.19.0, 9.2.20.0, 9.3.0.0, 9.3.1.0, head
        Make sure you use the latest version of the action with - uses: ruby/setup-ruby@v1
        File an issue at https://github.com/ruby/setup-ruby/issues if would like support for a new version
```

**Comment by eregon** [comment]
#220 is 9.3.0.0, unrelated.

**Comment by eregon** [comment]
Thanks for the reminder.
I'm a bit tired of doing those updates manually since there were many JRuby & CRuby releases recently.
Maybe more of it can be automated.

**Comment by eregon** [comment]
Done in https://github.com/ruby/setup-ruby/releases/tag/v1.89.0

**Comment by hsbt** [comment]
@eregon Thanks for your work. Can we help your work like https://github.com/ruby/setup-ruby/commit/471466b54cb9744f371b61fb5ca33975e116fefb ?
