### ISSUE TITLE
Ruby version not specified

### ISSUE THREAD

**Issue by ShariqT** [ruby/setup-ruby#241]
I'm running into an error that I cannot seem to triage. The action tells me that I have to specify the ruby version. I'm not using a `.ruby-version` file in the repo and am using the Github Action matrix to run the action across several versions of Ruby.

---------------------------------
name: Publish Gem

on:
  release:
    types: [published]

jobs:
  publish_gem:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['jruby-9.2.9.0', '2.6', '2.7', '3.0']
    steps:
    - uses: actions/checkout@v2
    - name: Setup
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Install Dependencies
      run: bundle install
    - name: Publish Gem
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"

**Comment by MSP-Greg** [comment]
@ShariqT

I believe this is working.  Do you have a link or Actions log output?

**Comment by ShariqT** [comment]
This is a link to the most recent job that failed. 

https://github.com/lob/lob-ruby/runs/4463860792?check_suite_focus=true

**Comment by MSP-Greg** [comment]
@ShariqT 

Thanks. This is strange, as I ran this [workflow](https://github.com/MSP-Greg/github-actions-ruby-info/blob/a1c863d7d540af28dbcd3ec5b3381f8187d2f3c9/.github/workflows/ruby.yml), which ran this [job](https://github.com/MSP-Greg/github-actions-ruby-info/runs/4464247296?check_suite_focus=true#step:3:3).

The only difference I'm seeing is your workflow uses `ruby-version` and mine uses `ruby`?

In the Action job log, if you 'open' the setup step, then open `Run ruby/setup-ruby@v1`, my log shows:
```yaml
  with:
    ruby-version: jruby-9.2.9.0
    bundler: default
```

your log shows the below (missing `ruby-version: jruby-9.2.9.0`):
```yaml
  with:
    bundler: default
```

**Comment by eregon** [comment]
From the log we there is a way to find the workflow which was used:
https://github.com/lob/lob-ruby/actions/runs/1551842099/workflow

`matrix.ruby-version` is not set, there is no matrix in that workflow, so that's a bug of that workflow.
