### ISSUE TITLE
Persisent failure of caching service with setup-ruby 

### ISSUE THREAD

**Issue by kingdonb** [ruby/setup-ruby#244]
Not sure if my private repo is the source of the problem, but since I haven't found mass hordes of reports about this issue I assume it must be uniquely affecting me and so caused by something unique about my repo.

I have `bundler-cache` enabled and receive `Warning: reserveCache failed: Cache service responded with 500` at the critical moment after bundle install when caches should be saved. I receive a similar error at the start of the `setup-ruby` step,

```
  Cache key: setup-ruby-bundler-cache-v3-ubuntu-20.04-ruby-2.7.5-cachever:1-Gemfile.lock-537b066776e2d9c61642f2be453fa20abb3b909f7215bf1bf5b2a8b502fd25a2
  Warning:  There was an error restoring the cache getCacheEntry failed: Cache service responded with 500
```

I have also seen 503s, and now I wonder if this is really a transient service issue. I've been trying this since yesterday and GH status page hasn't reported any outages, but maybe it's a temporary issue related to the caching service and will go away on its own? If there's something I need to do in order to enable the cache service I didn't find it in any of the docs for GHA or setup-ruby. (This is where I began to guess it might be an issue with the private repo.)

~I'm in the process of cleaning up my kuby_test repo and verifying I haven't leaked any important credentials without invalidating them, then I will publish it and try again;~

So it has nothing to do with the repo being private, it has now been published and the WIP example for kuby and setup-ruby is here: https://github.com/kingdonb/kuby_test – it still has the cache 500 errors after some time has passed and after going public. I will update the title since this issue is not about a private repo anymore...

```
Warning: reserveCache failed: Cache service responded with 500
```

 ~if publishing the repo solves the issue, that would solve the issue for me and substantiate the perhaps questionable root cause analysis here, but maybe this should still be reported somewhere (or~ maybe it's a transient issue ? ~.)~ I don't find any issue reports with this error in it. Maybe I am not the only one? (Edit:) it has nothing to do with the repo being private.

**Comment by opslevel-michael** [comment]
I'm also getting this error and a similar issue was filed in https://github.com/actions/cache/issues/698.

**Comment by kingdonb** [comment]
Thanks. It sounds unlikely to be a setup-ruby issue then.

**Comment by kingdonb** [comment]
There is a Root Cause analysis available at:

* https://github.com/actions/cache/issues/698#issuecomment-992565426
