### ISSUE TITLE
Question - do I need to update the action name?

### ISSUE THREAD

**Issue by zulhfreelancer** [ruby/setup-ruby#25]
I saw this in the README:

> Note: this action used to be at `eregon/use-ruby-action` and was moved to the `ruby` organization.

I have a running project using `eregon/use-ruby-action@v1`. Do I need to update it to `ruby/setup-ruby@v1`?

**Comment by MSP-Greg** [comment]
I've never checked for the duration, but GitHub redirects repo renames for some period, but I have no idea how long, could be forever.

> Do I need to update it to ruby/setup-ruby@v1?

It would be a good idea.

**Comment by hsbt** [comment]
Yes, do it.

**Comment by eregon** [comment]
https://github.com/ruby/setup-ruby/releases/tag/v1.13.0 clarifies that, in short it's recommended. I'll try to clarify the README.
