### ISSUE TITLE
`The specified module could not be found.` with Ruby 3.1 on Windows

### ISSUE THREAD

**Issue by ankane** [ruby/setup-ruby#256]
Hi, thanks for this great action!

When testing native extensions with the newly added Ruby 3.1 on Windows, the extensions compile, but error when loaded with `The specified module could not be found.`, even though the files appear to exist. I've tested with a few projects and they've all had the same error (all use rake-compiler to build, fwiw). The workflows succeed with Ruby 3.0 and 2.7 on Windows.

Details:

- [Workflow file](https://github.com/ankane/stl-ruby/blob/8f646cc44b0e54ae938e0738c56bcf58ac15ad40/.github/workflows/build.yml)
- [Failed job](https://github.com/ankane/stl-ruby/runs/4769793703?check_suite_focus=true)
- Command: `bundle exec rake test`
- Output:

```txt
D:/a/stl-ruby/stl-ruby/lib/stl.rb:2:in `require': 126: The specified module could not be found.   - D:/a/stl-ruby/stl-ruby/lib/stl/ext.so (LoadError)
	from D:/a/stl-ruby/stl-ruby/lib/stl.rb:2:in `<top (required)>'
	from D:/a/stl-ruby/stl-ruby/lib/stl-rb.rb:1:in `require'
	from D:/a/stl-ruby/stl-ruby/lib/stl-rb.rb:1:in `<top (required)>'
	from C:/hostedtoolcache/windows/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.4/lib/bundler/runtime.rb:60:in `require'
	from C:/hostedtoolcache/windows/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.4/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
	from C:/hostedtoolcache/windows/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.4/lib/bundler/runtime.rb:55:in `each'
	from C:/hostedtoolcache/windows/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.4/lib/bundler/runtime.rb:55:in `block in require'
	from C:/hostedtoolcache/windows/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.4/lib/bundler/runtime.rb:44:in `each'
	from C:/hostedtoolcache/windows/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.4/lib/bundler/runtime.rb:44:in `require'
	from C:/hostedtoolcache/windows/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.4/lib/bundler.rb:176:in `require'
	from D:/a/stl-ruby/stl-ruby/test/test_helper.rb:2:in `<top (required)>'
	from D:/a/stl-ruby/stl-ruby/test/stl_test.rb:1:in `require_relative'
	from D:/a/stl-ruby/stl-ruby/test/stl_test.rb:1:in `<top (required)>'
	from D:/a/stl-ruby/stl-ruby/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:21:in `require'
	from D:/a/stl-ruby/stl-ruby/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:21:in `block in <main>'
	from D:/a/stl-ruby/stl-ruby/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:6:in `select'
	from D:/a/stl-ruby/stl-ruby/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:6:in `<main>'
rake aborted!
Command failed with status (1)
D:/a/stl-ruby/stl-ruby/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Tasks: TOP => test
(See full trace by running task with --trace)
```

- Not a self-hosted runner

**Comment by MSP-Greg** [comment]
@ankane

Work is ongoing with Windows Ruby 3.1.0 (MSYS2 UCRT64) and windows-2022.

If you want to work with it now, replace `ruby/setup-ruby@v1` with `MSP-Greg/ruby-setup-ruby@win-ucrt-1`, which is being used in a few repos (ruby/ruby, Puma, Nokogiri, etc).  It you have issues, feel free to ping me.

At some point, this repo will work.  Sometime after that, I will stop updating the branch in my fork (updates are needed for new Ruby versions, Actions changes, package updates, etc)

**Comment by ankane** [comment]
Hey @MSP-Greg, thanks for the fast response! I'm seeing the error with `windows-latest` (which is `windows-2019`) rather than `windows-2022`.

**Comment by MSP-Greg** [comment]
Using `ruby/setup-ruby@v1` pr `MSP-Greg/ruby-setup-ruby@win-ucrt-1`?

**Comment by ankane** [comment]
Just tried `MSP-Greg/ruby-setup-ruby@win-ucrt-1` and it fixes the error. Thanks!

Will close this out since it's a known issue.
