### ISSUE TITLE
Remove support for windows-2016

### ISSUE THREAD

**Issue by eregon** [ruby/setup-ruby#257]
There is windows-2019 and windows-2022 now.

2016 is deprecated: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

Also the CI matrix is becoming too big (2 versions per OS is really the max we can reasonably support), so I think we just stop testing on windows-2016 now, and fully remove support after GitHub drops it: https://github.blog/changelog/2021-10-19-github-actions-the-windows-2016-runner-image-will-be-removed-from-github-hosted-runners-on-march-15-2022/

@MSP-Greg FYI

**Comment by MSP-Greg** [comment]
I don't think a lot of Ruby repos use windows-2016, and I don't recall any issues that were windows-2016 specific.

If anything, there are issues with the fact that MSYS2 mingw/ucrt gcc is at 11.2.0, and many older Ruby versions were compiled with much earlier gcc versions.  So hypothetically, maybe 2.5.9 would compile fine, but 2.5.0 or 2.5.1 would not.

Previously, I considered whether CI code could install older gcc versions, but decided it would be a maintenance mess.  At some point, supporting old OS's and Ruby versions is not our problem.  The people using them have to learn how to work with them, as we're more interested in helping make current/future Ruby better...
