### ISSUE TITLE
Bundler / RubyGems - upgrade just Bundler or both?

### ISSUE THREAD

**Issue by MSP-Greg** [ruby/setup-ruby#26]
There was just an odd CI failure in a Puma PR, with only 2.5.& 2.6 failing on Windows.  Ubuntu & macOS passed.

I tried to repo locally, using 2.6.5 as setup by Actions (with Bundler < 2), I had some odd issues.  I grabbed the Puma PR in my fork, and re-ran the CI, both with the `--seed` value that failed in Puma and without, and both passed.

While working with various repo's CI and Ruby < 2.6.0 (no included Bundler), I think people have had more 'success' by running `gem update --system` (Ruby >= 2.3), rather than `gem install bundler`.

IOW, this is about the distinction of whether available CI builds (Ruby >= 2.3) should have only Bundler installed, or whether they should have `gem update --system` done.

Wanted to have an open issue in case others have similar problems...

**Comment by eregon** [comment]
Thank you for the issue report.

As written in https://eregon.me/blog/2020/01/13/a-migration-path-to-bundler2.html I'm against updating RubyGems automatically in CI. I think it just introduces more variance and therefore less reliability and most importantly it shouldn't be needed.
Even Bundler 2 doesn't need to update RubyGems on Ruby >= 2.3 (and Bundler 2 doesn't support Ruby < 2.3).

I think users should update explicitly in their workflow if what they want to test is "does the latest RubyGems version works with my gem/app?"

One point open for consideration would be which version of Bundler to provide on Rubies which don't already ship Bundler. I think the current choice of Bundler 1 is the best and consistent with Ruby 2.6 shipping Bundler 1, so earlier versions should use Bundler 1 too.
