### ISSUE TITLE
Consider configuring `make` to parallelize installs with native extensions

### ISSUE THREAD

**Issue by bquorning** [ruby/setup-ruby#299]
I was recently made aware of [this blog post](https://build.betterup.com/one-weird-trick-that-will-speed-up-your-bundle-install/#the-make-environment-variable) which shows a 3x speedup of `bundle install` – presumably on a Gemfile with many native extensions.

> Well, it just so happens that most native extensions use the [rake-compiler](https://github.com/rake-compiler/rake-compiler) library, which uses [make](https://en.wikipedia.org/wiki/Make_(software)) under the hood, which also happens to support [a --jobs argument](https://linux.die.net/man/1/make):
>
>>
>>-j [jobs], --jobs[=jobs]
>>
>>Specifies the number of jobs (commands) to run simultaneously. If there is more than one `-j` option, the last one is effective. If the `-j` option is given without an argument, make will not limit the number of jobs that can run simultaneously.

Here are a few benchmarks on a “2,6 GHz 6-Core Intel Core i7” Macbook with the following Gemfile:

```rb
source "https://rubygems.org"
gem "bootsnap", "1.11.1"
gem "json", "2.6.1"
gem "mysql2", "0.5.3"
gem "oj", "3.13.11"
gem "rdkafka", "0.11.1"
gem "websocket-driver", "0.7.5"
```

Each benchmark is run in a fresh Docker container using the current `ruby:2.7` Docker image:

```
root@2f0421238588:/# time bundle install
real  1m31.471s
user  1m19.537s
sys 0m10.235s

root@c205b3e76d26:/# time bundle install --jobs 6
real  1m25.453s
user  1m15.589s
sys 0m9.443s

root@c011752ba5f3:/# time MAKE="make --jobs 6" bundle install
real  0m34.089s
user  1m31.538s
sys 0m10.857s

root@3d64edf25717:/# time MAKE="make --jobs 6" bundle install --jobs 6
real  0m33.315s
user  1m31.033s
sys 0m10.825s
```

As you can see, when a Gemfile contains just a few native extensions, it is much faster to `bundle install` when `make` is configured to run in parallel.

There will probably be some caveats regarding OS, platform, Ruby interpreter, how many cores/processors are available etc. 😬

**Comment by MSP-Greg** [comment]
> Well, it just so happens that most native extensions use the [rake-compiler](https://github.com/rake-compiler/rake-compiler) library

Not sure why rake-compiler was mentioned, as that normally isn't used with `bundle install`.

One can add the `--jobs` setting to the env in the Actions step yaml using `MAKE` or `MAKEFLAGS`.

Finally, as @eregon mentioned:
1. Hosted runners have 2 CPUs
2. Some C extensions might fail to build when built in parallel.  I have seen 'fail to build', don't recall with what gem.  It may be gcc version dependent.

On GitHub hosted runners, there probably won't be much of a speed increase.  If one had a self-hosted runner with a lot more cores, there could be an improvement.
