### ISSUE TITLE
Support Ruby 3.1

### ISSUE THREAD

**Issue by fundthmcalculus** [ruby/setup-ruby#303]
Ruby 3.1 has been out since December 2021, support for ruby 3.1 would be desirable.

Please provide:
* [the code of or a link to the workflow used](https://github.com/trinsic-id/sdk/actions/runs/2072136943/workflow#L28-L30)
* [the link to the log of a failed workflow job](https://github.com/trinsic-id/sdk/actions/runs/2072136943)
* the command and output of the step failing: SEE BELOW
* whether you are using a self-hosted runner: FALSE

```
Error: Unknown version 3.1 for ruby on ubuntu-20.04
        available versions for ruby on ubuntu-20.04: 2.0.0-p648, 2.1.[9](https://github.com/trinsic-id/sdk/runs/5774167183?check_suite_focus=true#step:3:9), 2.2.[10](https://github.com/trinsic-id/sdk/runs/5774167183?check_suite_focus=true#step:3:10), 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.4.7, 2.4.9, 2.4.10, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.5.6, 2.5.7, 2.5.8, 2.5.9, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.6.6, 2.6.7, 2.6.8, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.7.4, 3.0.0-preview1, 3.0.0-preview2, 3.0.0-rc1, 3.0.0, 3.0.1, 3.0.2, head, debug
        Make sure you use the latest version of the action with - uses: ruby/setup-ruby@v1
        File an issue at https://github.com/ruby/setup-ruby/issues if would like support for a new version
```

**Comment by eregon** [comment]
Yeah, let's close this kind of issue by just quoting the text, like:
> Make sure you use the latest version of the action with - uses: ruby/setup-ruby@v1
