### ISSUE TITLE
Provide cache-hit output

### ISSUE THREAD

**Issue by dhvcc** [ruby/setup-ruby#305]
I'd like to propose adding `cache-hit` output, since this action utilizes `actions/cache`. This proposal was originally made in https://github.com/actions/setup-python/issues/371, so full justification can be found here (this is for python, but I think it doesn't matter that much?)

**Comment by eregon** [comment]
Do you have a concrete example how this output would be useful?

From that linked issue:
> This would be helpful if, for example, we need add stuff to PATH if this cache was hit.

I don't see how that would apply here. No matter cache hit or not the PATH would be the same.

**Comment by dhvcc** [comment]
Sure, I'll try to find more ruby-related reasons and get back at you. Thanks for the response!

**Comment by dhvcc** [comment]
It seems like all use cases for this feature are really covered by this action, closing this
