### ISSUE TITLE
Add all the new Rubies

### ISSUE THREAD

**Issue by miharekar** [ruby/setup-ruby#308]
A bunch of versions were released today: 2.6.10, 2.7.6, 3.04, and 3.1.2.

https://www.ruby-lang.org/en/news/

I'd add them but I don't know how. Last time I saw it was done via bot in https://github.com/ruby/setup-ruby/pull/295

**Comment by eregon** [comment]
It's all automatic, and the first step is done every day or manually. Now we just wait for the builds (https://github.com/ruby/ruby-builder/commits/master).

**Comment by eregon** [comment]
Done

**Comment by miharekar** [comment]
Ah, thanks!
