### ISSUE TITLE
[Documentation] Mention `libgmp` to be installed for self hosted runners

### ISSUE THREAD

**Issue by soumyamahunt** [ruby/setup-ruby#313]
I tried running this action on self-hosted runner and faced [this](https://stackoverflow.com/questions/26555902/ruby-v-dyld-library-not-loaded-usr-local-lib-libgmp-10-dylib) error:
> [Ruby -v dyld: Library not loaded: /usr/local/lib/libgmp.10.dylib](https://stackoverflow.com/questions/26555902/ruby-v-dyld-library-not-loaded-usr-local-lib-libgmp-10-dylib)

Installing `gmp` fixed this error for me. Mentioning this along with `libyaml` will avoid confusion in future.

**Comment by eregon** [comment]
Could you make a PR to add this to the README?

**Comment by soumyamahunt** [comment]
@eregon just did #314:)
