### ISSUE TITLE
Add CRuby 3.2.0-preview1

### ISSUE THREAD

**Issue by a2ikm** [ruby/setup-ruby#318]
Hi, 

CRuby 3.2.0-preview1 was released at 3rd April.
https://www.ruby-lang.org/en/news/2022/04/03/ruby-3-2-0-preview1-released/

But now I'm having the following error on [my trial pull request](https://github.com/a2ikm/mongomapper/pull/15):

> Error: Unknown version 3.2.0-preview1 for ruby on ubuntu-20.04

Could you support it?

**Comment by eregon** [comment]
It's there in ruby-build so it shouldn't be too hard: https://github.com/rbenv/ruby-build/pull/1954
But it's also not picked by the automation so I'll probably need to adapt it.

I'd recommend to just use `ruby-head` instead in the meantime.

**Comment by eregon** [comment]
Notably there were a number of important changes after preview1, so I feel preview1 isn't really useful if you want to test compatibility with what will become Ruby 3.2. `ruby-head` is better for that.

**Comment by a2ikm** [comment]
Thanks, I understand the current status.

> I'd recommend to just use ruby-head instead in the meantime.

I’ll do that 😃

**Comment by eregon** [comment]
Done: https://github.com/ruby/setup-ruby/pull/323 and https://github.com/ruby/ruby-builder/commit/85c4299e73fddf415e2888b8b1aba7cfcf9ed950
