### ISSUE TITLE
Ruby gh action pins setup-ruby to 2yr old commit

### ISSUE THREAD

**Issue by 0atman** [ruby/setup-ruby#319]
The default github action ruby template references this old commit which doesn't have any modern rubies https://github.com/ruby/setup-ruby/commit/473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e

### Solution
We fixed this by updating the pinned version to the latest release https://github.com/alphagov/forms-api/pull/3/commits/e3c8ad2759088a12ba9f3040d2c47c23799c8455

I think the template that github is using should either be unpinned to just v1, or regularly updated to the latest release hash.

Thank you

---

### the code of or a link to the workflow used
"Ruby" from https://github.com/alphagov/forms-api/actions/new?category=none&query=ruby

### the link to the log of a failed workflow job
https://github.com/alphagov/forms-api/runs/6093152207?check_suite_focus=true

### the command and output of the step failing
```shell
Run ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
Error: Unknown version 3.0.3 for ruby on ubuntu-20.04
        available versions for ruby on ubuntu-20.04: 2.1.9, 2.2.10, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.4.7, 2.4.9, 2.4.10, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.5.6, 2.5.7, 2.5.8, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.6.6, 2.7.0, 2.7.1, 2.7.2, 3.0.0-preview1, 3.0.0-preview2, 3.0.0-rc1, 3.0.0, head, debug
        File an issue at https://github.com/ruby/setup-ruby/issues if would like support for a new version
```

### whether you are using a self-hosted runner
Not self-hosted.

**Comment by eregon** [comment]
See https://github.com/actions/starter-workflows/pull/823#issuecomment-789970701
I agree, but GitHub doesn't :/

What you can do is a PR to update https://github.com/actions/starter-workflows/blob/ad9daa8da372928e50064995bb1c2f542c0c345c/ci/ruby.yml#L33 to use the latest commit sha.

**Comment by dentarg** [comment]
There's also pages on https://docs.github.com/ that needs updates, where [the helpful comment in the starter workflow](https://github.com/actions/starter-workflows/blob/ad9daa8da372928e50064995bb1c2f542c0c345c/ci/ruby.yml#L30-L32) isn't even allowed (https://github.com/github/docs/pull/15240#discussion_r804929843) :/

**Comment by eregon** [comment]
Good point, I replied there as well. We got official confirmation for that helpful comment, so I think they must allow it in the docs too.

**Comment by 0atman** [comment]
Ask an ye shall receive https://github.com/actions/starter-workflows/pull/1542#event-6520276749
