### ISSUE TITLE
Support Ubuntu 22.04

### ISSUE THREAD

**Issue by Watson1978** [ruby/setup-ruby#333]
Github Actions has been support Ubuntu 22.04 platform (as public beta) and we can try it.
(Ref. https://github.com/actions/virtual-environments/issues/5490)

However, seems that setup-ruby action does not support it yet.
When downloading, the specified Ruby seems to be missing.

![image](https://user-images.githubusercontent.com/199156/167858502-fa56e18d-7489-41f4-9a87-7916e1cf768d.png)

**Comment by eregon** [comment]
It's still in beta, so it might take some time to support it.
Especially versions before 3.1 seem complicated to support due to 22.04 shipping with OpenSSL 3 and only Ruby 3.1 supports OpenSSL 3. At least we'll need https://github.com/rbenv/ruby-build/pull/1974.

So for now, on Ubuntu 22.04 we will only have Ruby 3.1+ available.

It might need a few trivial changes in this repo which I'll do soon.

**Comment by eregon** [comment]
`jruby` can't build on 22.04, because the ubuntu-22.04 image doesn't have java currently: https://github.com/actions/virtual-environments/issues/5490
> Java is not available for Ubuntu 22 at the moment

`truffleruby` can't build on 22.04, because it needs OpenSSL 3 support first.

So for now it will just be:
```
ruby:
"3.1.0", "3.1.1", "3.1.2", "3.2.0-preview1", "head", "debug"
```

**Comment by eregon** [comment]
Those work from https://github.com/ruby/setup-ruby/releases/tag/v1.107.0 (ruby-head build in progress)

**Comment by iBug** [comment]
> Especially versions before 3.1 seem complicated to support

I'm not sure what difficulties have been overcome, but Ubuntu's stock `ruby` package is 3.0.2. It also uses OpenSSL 3.0.

```shell
$ dpkg -L libruby3.0
...
/usr/lib/x86_64-linux-gnu/ruby/3.0.0/openssl.so
...

$ ldd /usr/lib/x86_64-linux-gnu/ruby/3.0.0/openssl.so
...
libssl.so.3 => /lib/x86_64-linux-gnu/libssl.so.3 (0x00007fca63008000)
...
```

I may understand how Ruby 2.x would be difficult to build, but why would Ruby 3.0?

**Comment by eregon** [comment]
@iBug Read https://bugs.ruby-lang.org/issues/18658. Ruby 3.0 does not support OpenSSL 3.0, Ubuntu manually backported that but it's not something we can use or an official Ruby release tarball.

**Comment by Watson1978** [comment]
How is the progress?

Looks like Ubuntu 22.04 will be officially started from August 8.
https://github.com/actions/virtual-environments/issues/5998

**Comment by eregon** [comment]
Now that https://github.com/rbenv/ruby-build/pull/1974 is merged in ruby-build we should be able to build all/most Ruby versions on Ubuntu 22.04, I'll start the builds.

**Comment by eregon** [comment]
Done now, all versions are also built on Ubuntu 22.04.
Some exceptions: preview/RC (except the latest preview), and old jruby/truffleruby releases, those I'll only build if needed.

**Comment by Watson1978** [comment]
Thanks !!
