### ISSUE TITLE
Does cache sometimes expire on its own for no reason?

### ISSUE THREAD

**Issue by davidpellcb** [ruby/setup-ruby#334]
I have inherited an app that takes an excruciatingly long time to run `bundle install` (not quite sure why yet, trying to get to that, but I assume it has to do with native extensions). It takes 7-8 minutes when the cache misses, and the cache seems to be missing sometimes even when the cache key is unchanged.

For example, I recently got this cache key:

```
Cache key: setup-ruby-bundler-cache-v3-ubuntu-20.04-ruby-2.6.5-Gemfile.lock-d6e65c7bbe5e7d5c7f7c43b9dc779c2f7ace2ed2a8ef843d7801412621ec3994
```

The cache missed, and the build took about 8 minutes. However, this was for a PR that didn't include any changes to `Gemfile.lock`.

When I look at the build from 6 hours ago that finished in just 1 minute 18 seconds, I see this:

```
Cache key: setup-ruby-bundler-cache-v3-ubuntu-20.04-ruby-2.6.5-Gemfile.lock-d6e65c7bbe5e7d5c7f7c43b9dc779c2f7ace2ed2a8ef843d7801412621ec3994
  Received 54525952 of 71843387 (75.9%), 51.9 MBs/sec
  Received 71843387 of 71843387 (100.0%), 56.9 MBs/sec
  Cache Size: ~69 MB (71843387 B)
  /usr/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/879c366f-6d06-4d92-b881-1c8bc0[31](https://github.com/myorg/myapp/runs/6413449311?check_suite_focus=true#step:3:31)df28/cache.tzst -P -C /home/runner/work/myapp/myapp
  Cache restored successfully
  Found cache for key: setup-ruby-bundler-cache-v3-ubuntu-20.04-ruby-2.6.5-Gemfile.lock-d6e65c7bbe5e7d5c7f7c43b9dc779c2f7ace2ed2a8ef843d7801412621ec3994
```

Notice that the cache keys are the same.

Here's a screenshot of the times for the last 5 builds:

<img width="163" alt="image" src="https://user-images.githubusercontent.com/92184793/168202479-726c7d7b-c162-4b71-a3a6-5ce46fa2545b.png">

Here we see a cache miss 10 hours ago (build time 8m) followed by a cache hit 8 hours ago (build time 43s), followed up another cache hit 6 hours ago (build time 1m18s) followed by the cache miss 15 minutes ago (9m8s) followed by another cache hit.

Is this kind of thing expected? Is the GiHub Actions cache local to the individual build machine and thus liable to be missed if a subsequent build runs on a different machine?

**Comment by eregon** [comment]
I'm not sure what's the problem in your case, the only limits I'm aware of are https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy
The relation between branches does matter IIRC, and that's not shown as part of the key (https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache).

In any case, I don't think this action can do anything about that, it sounds like an issue of actions/cache or GitHub, so I close this issue.

**Comment by davidpellcb** [comment]
Thanks @eregon. Closing the loop on this in case it might help someone in the future: the discussion at your second link about [how the cache keys are matched](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#matching-a-cache-key) _against branches_ helped me solve my problem.

I didn't realize that the cache key was associated with a particular branch, and I was only building on PR events. GH Actions looks up the cache key like this:
1. see if the key exists for the current feature branch
2. see if the key exists for the default branch

Since I was only building on PRs, the cache key was never associated with the `master` branch, meaning that for new PRs the first lookup was always a miss (key not associated with new branch, key also not associated with `master`). I was able to fix my problem by setting up my workflow this way:

```yaml
name: Build
on:
  # Build anytime a PR is opened or updated
  pull_request:
  # Build when we merge to master
  push:
    branches:
      - master
```
