### ISSUE TITLE
macOS regression @v1 - Supported platforms

### ISSUE THREAD

**Issue by danielbowden** [ruby/setup-ruby#336]
Hi,

We are using `@v1` version tag and have experienced a breaking change with this recent [commit](https://github.com/ruby/setup-ruby/commit/296bf7f67a651ec2f74c08983d6c625973da73a1):
```
Use an explicit list of supported platforms for nicer error messages
(https://github.com/ruby/setup-ruby/commit/296bf7f67a651ec2f74c08983d6c625973da73a1).
```

GH virtual environments now support macOS-12 (https://github.com/actions/virtual-environments/blob/main/images/macos/macos-12-Readme.md) and like many projects we are using these hosted runners with `runs-on: macos-12`.

With the recent change we are experiencing failures as macOS 12 is not included in the new `supportedPlatforms` array, with the error:
```
Error: Unsupported platform macos-12.0 at Module.getAvailableVersions
```

To get around this temporarily, we are locking to a specific action version from before this change. eg.

```yaml
 uses: ruby/setup-ruby@v1.106.0
```

If you require any more info please let more know.

**Comment by jonghyun-kim** [comment]
Same here.

**Comment by eregon** [comment]
Let's track this in https://github.com/ruby/setup-ruby/issues/337

**Comment by eregon** [comment]
Support added in https://github.com/ruby/setup-ruby/releases/tag/v1.108.0 (a7439cf424c9677922eee7cb72a848b9fd7fb3ff)
