### ISSUE TITLE
Any idea when macOS-12 will be supported?

### ISSUE THREAD

**Issue by duro** [ruby/setup-ruby#337]
Using `runs-on: macos-12` I currently get `Error: Unsupported platform macos-12.0`

Curious if there is a timeline on when this action will support that runner?

**Comment by matbouil** [comment]
Hi ! I encountered this error too ... However it was still working with macos-12.0 three days ago.

**Comment by duro** [comment]
I went ahead and created a pull request to simply add macos-12 to the list of allowed runners. My testing has gone flawlessly so far.

**Comment by alrocha** [comment]
as a temporary fix, I set it up to the previous version which was working fine
`uses: ruby/setup-ruby@v1.106.0`

**Comment by eregon** [comment]
It was working accidentally before.
It should be fine to add it to supported platforms if tests pass on this platform.

**Comment by eregon** [comment]
Support added in https://github.com/ruby/setup-ruby/releases/tag/v1.108.0 (a7439cf424c9677922eee7cb72a848b9fd7fb3ff)
