### ISSUE TITLE
Windows JRuby - recent failure

### ISSUE THREAD

**Issue by MSP-Greg** [ruby/setup-ruby#339]
Recent CI using Windows and both jruby and jruby-head are failing.

Running `bundle env` in my fork shows
```
Errno::EACCES: Permission denied - NUL
            sysopen at org/jruby/RubyIO.java:[12](https://github.com/MSP-Greg/setup-ruby/runs/6454940480?check_suite_focus=true#step:7:12)27
         initialize at org/jruby/RubyFile.java:362
                new at org/jruby/RubyClass.java:909
               open at org/jruby/RubyIO.java:1[14](https://github.com/MSP-Greg/setup-ruby/runs/6454940480?check_suite_focus=true#step:7:14)6
             output at D:/jruby-9.3.4.0/lib/ruby/stdlib/rubygems/resolver.rb:176
```

The Ruby code line (`lib/ruby/stdlib/rubygems/resolver.rb:176`) is:
```ruby
@output ||= debug? ? $stdout : File.open(IO::NULL, 'w')
```

@headius any ideas?  Of course, running `bundle env` locally works fine...

**Comment by eregon** [comment]
i.e., failure on this action's CI: https://github.com/ruby/setup-ruby/runs/6450274289?check_suite_focus=true

**Comment by nwjsmith** [comment]
This looks relevant: https://github.com/jruby/jruby/issues/7182

**Comment by MSP-Greg** [comment]
Sorry, I should have posted some links.  Given that logs are removed, I sometimes just grab the pertinent log output.

This is odd.  But, I've also noticed an issue that is similar to using Windows mingw and ucrt files, which can have very strange problems..

Re the juby issue above, that's 20 days old, but CI passed just six days ago here - https://github.com/ruby/setup-ruby/runs/6374617633.  That was with a cache, but it logged things before the cache restore that aren't logged in the recent failures.  Confused, with very little Java/JRuby knowledge...

**Comment by dentarg** [comment]
> Re the juby issue above, that's 20 days old, but CI passed just six days ago here - https://github.com/ruby/setup-ruby/runs/6374617633

https://github.com/actions/virtual-environments/pull/5524 happened 6 days ago

Java changed from `8.0.322+6 (default)` to `8.0.332+9 (default)` https://github.com/actions/virtual-environments/pull/5524/files#diff-f65387936ddf6510c2fb625ce3608de69c9565728a432af796da8a5de49b7a7bL115, that matches https://github.com/jruby/jruby/issues/7182#issuecomment-1111610677

**Comment by eregon** [comment]
This should be fixed in the July JDK release, so let's just wait for that (https://github.com/ruby-git/ruby-git/pull/582).

**Comment by halostatue** [comment]
Is this error the same or something new?

```console
Error: Error: Unexpected HTTP response: 404
[27](https://github.com/halostatue/minitar/runs/7188010152?check_suite_focus=true#step:3:34)
    at D:\a\_actions\ruby\setup-ruby\v1\dist\index.js:7561:25
[28](https://github.com/halostatue/minitar/runs/7188010152?check_suite_focus=true#step:3:35)
    at Generator.next (<anonymous>)
[29](https://github.com/halostatue/minitar/runs/7188010152?check_suite_focus=true#step:3:36)
    at fulfilled (D:\a\_actions\ruby\setup-ruby\v1\dist\index.js:7471:58)
[30](https://github.com/halostatue/minitar/runs/7188010152?check_suite_focus=true#step:3:37)
    at runMicrotasks (<anonymous>)
[31](https://github.com/halostatue/minitar/runs/7188010152?check_suite_focus=true#step:3:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Run tests
```

**Comment by eregon** [comment]
FWIW, the latest jruby-head on Windows is completely broken currently: https://github.com/jruby/jruby/issues/7106
The 404 is https://github.com/ruby/setup-ruby/issues/356 and just a side effect of this issue that it's not possible to build a JRuby archive on Windows without workarounds.

**Comment by headius** [comment]
It should be possible to build a JRuby bundle on Windows without using Windows, but I suppose setup-ruby does not work that way.

jruby/jruby#7106 will be fixed soon, but I'm unclear why it started to fail.

**Comment by eregon** [comment]
GitHub Actions updated the JDK, which fixes the `NUL` issue: https://github.com/actions/virtual-environments/commit/29009846626f499fbae885c06171f17b82ce7583
So now JRuby on Windows works again: https://github.com/eregon/setup-ruby/runs/7704539364?check_suite_focus=true

https://github.com/jruby/jruby/issues/7106 being fixed means jruby-head on Windows is also fixed now.
