### ISSUE TITLE
Can't create 'x64' while extracting package macOS self-hosted runner

### ISSUE THREAD

**Issue by cinder92** [ruby/setup-ruby#347]
After a while, i had to create `/Users/runner/hostedtoolcache/Ruby/2.7.4` folder manually. Otherwise this tool was sating that does not have enough Permissions.

After i created that folder im stuck in this step.

![Screen Shot 2022-06-10 at 2 19 24](https://user-images.githubusercontent.com/4725556/173011902-cbbf8e77-7aad-4c16-a884-ed1dbb503f07.png)

Will this issue fix if i install ruby 2.7.4 manually on the host?

Thanks

**Comment by eregon** [comment]
You need to give the runner the permission to write there.
