### ISSUE TITLE
ansi.rb:100 in winsize Operation not supported on socket

### ISSUE THREAD

**Issue by xucian** [ruby/setup-ruby#355]
Hi,
Any clue? Google doesn't help

* the code of or a link to the workflow used
[workflow-stripped.txt](https://github.com/ruby/setup-ruby/files/9023165/workflow-stripped.txt)

* the link to the log of a failed workflow job
[step output.txt](https://github.com/ruby/setup-ruby/files/9023141/step.output.txt)

* the command and output of the step failing
```
/Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/2.7.0/reline/ansi.rb:100:in `winsize': Operation not supported on socket (Errno::EOPNOTSUPP)
```

* whether you are using a self-hosted runner
Yes

**Comment by MSP-Greg** [comment]
Have you looked at https://github.com/ruby/reline/blob/master/.github/workflows/reline.yml?

**Comment by tfgstudios** [comment]
Not sure what to look for, exactly. Is it a dependency for setup-ruby in my
case?

**Comment by MSP-Greg** [comment]
> Is it a dependency for setup-ruby in my case?

No.  Your error is in reline code, and that's the Actions workflow file for reline.  Its test suite may contain info as to your issue also.

Lastly, there is no console in Actions, I believe the runner code is C#, and it's collecting the output.  Your error (below) certainly looks like it's trying to set a console property...
```
reline/ansi.rb:100:in `winsize': Operation not supported on socket (Errno::EOPNOTSUPP)
```

**Comment by dentarg** [comment]
Maybe some clues in https://github.com/fastlane/fastlane/issues/20123? Maybe not the exact same issue but sounds similar 

In any case, I'm really doubtful this is a problem in setup-ruby. Seeing you are using a self hosted runner, you are on your own to debug this.

**Comment by dentarg** [comment]
You should try with the latest version of fastlane if you haven't already

**Comment by tfgstudios** [comment]
Thanks guys for directions. In my case the solution was to just update the ruby version.
I was under the impression that 2.7.2 is the latest. As you see in the workflow, I had "ruby-version: 2.7.2". I discovered by mistake that 3.1.2 is actually the latest. 
This solved my case without updating fastlane, but doing this as well won't hurt.
Thanks!
