### ISSUE TITLE
JRuby Windows, compiling & Actions

### ISSUE THREAD

**Issue by MSP-Greg** [ruby/setup-ruby#36]
@headius @eregon

I saw PR https://github.com/ruby/setup-ruby/pull/35, was led to jruby/jruby-launcher, and saw mention of MinGW.

Not being very familiar with JRuby, is there a need for compile tools on Windows?  Also, I believe Java itself is compiled with MSVC/mswin tools, not MinGW tools.

With the current code here, there is no way to enable compile tools on Windows unless the Ruby platform is MRI mswin or mingw.  Enabling mswin is simple and fast, but (long story) enabling mingw takes a minute or two.

**Comment by eregon** [comment]
I think in general there isn't because JRuby doesn't support building C extensions.
I would think the `jruby-launcher` "gem" is prebuilt on Windows, but maybe it isn't?

AFAIK JRuby Windows users already have a `bin/jruby.exe` launcher, so there is no need to manually `gem install jruby-launcher` on Windows.

**Comment by MSP-Greg** [comment]
> I think in general there isn't because JRuby doesn't support building C extensions.

Thanks.  that was my impression, but I just wanted to verify.

So, although `jruby-launcher` could add Windows and/or macOS to its CI, it's a 'singularity' in the JRuby world in terms of needing  c compilers?

**Comment by MSP-Greg** [comment]
Below is taken from https://github.com/MSP-Greg/actions-image-testing/actions.  All of the below have `JAVA_HOME` set to JDK 8.  Being a JRuby neophyte, would building head from JDK 11 be helpful to anyone?

```
Ubuntu
JAVA_HOME          /usr/lib/jvm/zulu-8-azure-amd64
JAVA_HOME_11_X64   /usr/lib/jvm/zulu-11-azure-amd64
JAVA_HOME_12_X64   /usr/lib/jvm/zulu-12-azure-amd64
JAVA_HOME_7_X64    /usr/lib/jvm/zulu-7-azure-amd64
JAVA_HOME_8_X64    /usr/lib/jvm/zulu-8-azure-amd64

macOS
JAVA_HOME          /Library/Java/JavaVirtualMachines/zulu-8.jdk/Co…
JAVA_HOME_11_X64   /Library/Java/JavaVirtualMachines/zulu-11.jdk/C…
JAVA_HOME_12_X64   /Library/Java/JavaVirtualMachines/zulu-12.jdk/C…
JAVA_HOME_13_X64   /Library/Java/JavaVirtualMachines/zulu-13.jdk/C…
JAVA_HOME_7_X64    /Library/Java/JavaVirtualMachines/zulu-7.jdk/Co…
JAVA_HOME_8_X64    /Library/Java/JavaVirtualMachines/zulu-8.jdk/Co…

Windows
JAVA_HOME          C:\Program Files\Java\zulu-8-azure-jdk_8.40.0.25-8.0.222-win_x64
JAVA_HOME_11_X64   C:\Program Files\Java\zulu-11-azure-jdk_11.33.15-11.0.4-win_x64
JAVA_HOME_7_X64    C:\Program Files\Java\zulu-7-azure-jdk_7.31.0.5-7.0.232-win_x64
JAVA_HOME_8_X64    C:\Program Files\Java\zulu-8-azure-jdk_8.40.0.25-8.0.222-win_x64
```

**Comment by eregon** [comment]
Java 8 is the most compatible with JRuby AFAIK, since there are no module warnings.
@headius Can you confirm?
