### ISSUE TITLE
Removing preview and RC builds for older releases

### ISSUE THREAD

**Issue by eregon** [ruby/setup-ruby#367]
I think these have no value once there is a full release of that Ruby major.minor branch.
So for example I'd like to remove:
```
"3.0.0-preview1", "3.0.0-preview2", "3.0.0-rc1",
"3.1.0-preview1"
```
I already will not build those for Ubuntu 22.04 to avoid wasting storage and time.

and only keep:
```
"3.2.0-preview1",
```
until 3.2.0 is released.

Thoughts?

**Comment by dentarg** [comment]
Sounds reasonable to me 👍🏻

**Comment by hsbt** [comment]
👍  It's only used for bisecting commits now. Not for CI testing.

**Comment by eregon** [comment]
Removed.
