### ISSUE TITLE
Github actions deploy common error

### ISSUE THREAD

**Issue by eavesdr0pper** [ruby/setup-ruby#370]
## Link the workflow used
See the github action workflow deploy details [here](https://github.com/eavesdr0pper/eavesdr0pper.github.io/runs/7817496849?check_suite_focus=true#step:3:72)

The Github actions workflow config yaml file  [here](https://github.com/eavesdr0pper/eavesdr0pper.github.io/blob/master/.github/workflows/pages.yml)

## The command and output of the step failing

```bash
Error: Error: The process '/opt/hostedtoolcache/Ruby/3.0.4/x64/bin/bundle' failed with exit code 16
    at ExecState._setResult (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:4945:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:4928:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:4822:27)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
```

## Detailed description

Git pages recently publish a new [beta version](https://github.blog/changelog/2022-07-27-github-pages-custom-github-actions-workflows-beta/), which user can now deploy to a GitHub Pages site directly from a repository using GitHub Actions, without needing to set up a publishing source. 

For the above mentioned workflow, Github pages use the `setup-ruby@v1` to deploy. But I tried a lot of jekyll projects, all failed to deploy, and the errors all appeared in the `setup-ruby` step.

How can I solve the above error? 

Thanks!

**Comment by eregon** [comment]
Just click on `> bundle install` and you'll see the error.
It seems your Gemfile.lock has a pretty old `BUNDLED WITH` and is not in sync with the Gemfile.

**Comment by vincerubinetti** [comment]
Fwiw I was getting the same error, and I found out it was because my GitHub Actions runner/image didn't match any of the platforms listed in my `Gemfile.lock` file.

```
Your bundle only supports platforms ["universal-darwin-21", "x64-mingw32"] but
  your local platform is x86_64-linux. Add the current platform to the lockfile
  with `bundle lock --add-platform x86_64-linux` and try again.
```

Make sure you click to expand all the little ▶s
