### ISSUE TITLE
ruby not added to path

### ISSUE THREAD

**Issue by tfgstudios** [ruby/setup-ruby#377]
Hello,

At the "bundle install" step, I'm getting "Could not determine gemfile path, skipping "bundle install" and caching"
Then I'm getting "gem: command not found" on my next action (maierj/fastlane-action@v2.2.1)

I'll be more careful from now on and not use @v1 (I also recommend you to update the docs with this recommendation), as I know that it worked in the past and now suddenly it doesn't, so I'm assuming it's something related to latest changes.
Machine is ubuntu 20.04.

Thanks

**Comment by MSP-Greg** [comment]
Need more info.

A lot of repos use this Action, and most use `@v1`, including a run in Rails about 20 minutes ago.  `@v1` use is still recommended.

The error message would indicate the Gemfile or gems.rb is missing?

**Comment by eregon** [comment]
> I'll be more careful from now on and not use @v1 (I also recommend you to update the docs with this recommendation), as I know that it worked in the past and now suddenly it doesn't, so I'm assuming it's something related to latest changes.

@tfgstudios This lack of respect is incredible. Even more so for open source work.
And you dare assume it's "our fault" when it's 99% likely to be a problem in your project, and the master CI is green proving it's not the fault of this action.
You also assume a previous version would solve it, I highly doubt so.
There could of course be an external change which breaks this action (e.g. in virtual environments), in which case it is obviously not the fault of this action.

I am waiting your apology.

**Comment by tfgstudios** [comment]
Thanks for the quick reply.
Yes, but it worked previously.
The reason the gemfile is missing is because I skip a repo checkout, as an
optimization.
I guess there was a change somewhere that now makes the gemfile mandatory.
Is that right?

**Comment by MSP-Greg** [comment]
> The reason the gemfile is missing is because I skip a repo checkout, as an optimization.

Odd 'optimization'. If you have the inputs for this action setup to run Bundler, then you need to either change the inputs or have the Gemfile in place before you use the action.  Please review the input docs.

**Comment by tfgstudios** [comment]
> > The reason the gemfile is missing is because I skip a repo checkout, as an optimization.
> 
> Odd 'optimization'. If you have the inputs for this action setup to run Bundler, then you need to either change the inputs or have the Gemfile in place before you use the action. Please review the input docs.

It's not odd if your repo is 20gb and you have a workflow that only needs pre-generated artifacts.
Can you confirm if this action made it mandatory to have the gemfile just recently or if it was always a hard-requirement?

**Comment by MSP-Greg** [comment]
Please provide the yaml you use with the action, in particular, the inputs.

> Can you confirm if this action made it mandatory to have the gemfile just recently

June 14, 2020.  Not exactly recent.

**Comment by eregon** [comment]
A Gemfile should only be needed if `bundler-cache: true` is used, otherwise not.

**Comment by MSP-Greg** [comment]
@tfgstudios I have a high tolerance for ESL.  Otherwise, I'd agree with @eregon's first post.

**Comment by tfgstudios** [comment]
> 

What a grotesquely EFL-elitist comment 🤣 thank god I take everything as a joke.

**Comment by tfgstudios** [comment]
> > I'll be more careful from now on and not use @v1 (I also recommend you to update the docs with this recommendation), as I know that it worked in the past and now suddenly it doesn't, so I'm assuming it's something related to latest changes.
> 
> @tfgstudios This lack of respect is incredible. Even more so for open source work. And you dare assume it's "our fault" when it's 99% likely to be a problem in your project, and the master CI is green proving it's not the fault of this action. You also assume a previous version would solve it, I highly doubt so. There could of course be an external change which breaks this action (e.g. in virtual environments), in which case it is obviously not the fault of this action.
> 
> I am waiting your apology.

Thanks for putting the time into this repo. Folk gets angry sometimes. 




> Please provide the yaml you use with the action, in particular, the inputs.
> 
> > Can you confirm if this action made it mandatory to have the gemfile just recently
> 
> June 14, 2020. Not exactly recent.

It means something odd happened on the github runner. My fault. Double sorry. ✌️


> A Gemfile should only be needed if `bundler-cache: true` is used, otherwise not.
Good to know.

Conclusion is: something outside the env/repo happened, even though nothing manually changed in months
