### ISSUE TITLE
Download macOS ruby from linux-based self-host runner

### ISSUE THREAD

**Issue by jieey1140** [ruby/setup-ruby#382]
### Ensure the following before filing this issue

- [ ] I verified it reproduces with the latest version with `- uses: ruby/setup-ruby@v1` (see [Versioning policy](https://github.com/ruby/setup-ruby/blob/master/README.md#versioning))

- [ ] I tried to reproduce the issue locally by following the workflow steps (including all commands done by `ruby/setup-ruby`, except for `Downloading Ruby` & `Extracting Ruby`),
and it did not reproduce locally (if it does reproduce locally, it's not a ruby/setup-ruby issue)

### Are you running on a GitHub-hosted runner or a self-hosted runner?

self-hosted runner

### The workflow code or a link to the workflow file

```yaml
- name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.RUBY_VERSION }} //2.6.0
      env: 
        ImageOs: 'ubuntu-22.04'
```

### Link to the log of a failed workflow job, or to a gist with the output

 Error: The process '/Users/runner/hostedtoolcache/Ruby/2.7.5/x64/bin/ruby' failed with exit code 2

### The command and output of the failing step

```shell
Run ruby/setup-ruby@v1
742
Modifying PATH
743
  Entries added to PATH to use selected Ruby:
744
    /Users/runner/hostedtoolcache/Ruby/2.7.5/x64/bin
745
Downloading Ruby
746
  https://github.com/ruby/ruby-builder/releases/download/toolcache/ruby-2.7.5-macos-latest.tar.gz
747
  Took   1.68 seconds
748
Extracting  Ruby
749
  /usr/bin/tar -xz -C /Users/runner/hostedtoolcache/Ruby/2.7.5 -f /home/runnerHome/actions-runner/_work/_temp/c86c44f8-2b12-4956-9ed5-d64adc471584
750
  Took   0.31 seconds
751
Print Ruby version
752
  /Users/runner/hostedtoolcache/Ruby/2.7.5/x64/bin/ruby --version
753
  /Users/runner/hostedtoolcache/Ruby/2.7.5/x64/bin/ruby: 1: Syntax error: "(" unexpected
754
  Took   0.00 seconds
755
Error: Error: The process '/Users/runner/hostedtoolcache/Ruby/2.7.5/x64/bin/ruby' failed with exit code 2
```

### Any other notes?

It seems to receive macOS ruby version from self-host runner in linux(ubuntu22).

**Comment by MSP-Greg** [comment]
Maybe `ImageOS`, not `ImageOs`?

**Comment by jieey1140** [comment]
Thank you for the information. My question was correct! :( After the change, Linux-based ruby was successfully loaded. When env is null, the default seems to be macOS. Thank you for your reply. I will close this issue :)

**Comment by MSP-Greg** [comment]
@jieey1140 Glad I could help.  I've had a repo that logs info about the Actions runner setups, you may find it helpful:

https://github.com/MSP-Greg/actions-image-testing/actions/workflows/image_info.yml

As you know, Actions logs do get flushed.  So, if I haven't run it for a while, the logs may be empty.
