### ISSUE TITLE
Deprecation warning for set-output command in GitHub Actions

### ISSUE THREAD

**Issue by d3li0n** [ruby/setup-ruby#385]
Hello team,

It appears that GitHub is planning to disable `set-output` command soon according to the [blog](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).

I am currently using the follow code to setup Ruby in my GitHub Actions:
```yaml
- name: Setup Ruby  
   uses: ruby/setup-ruby@v1
```

Warning message:

`Warning: The set-output command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/`

**Comment by ybiquitous** [comment]
I believe the warning should be resolved by updating to `@actions/core@1.10.0`. Because, with the version, the `setOutput` command uses environment files if available. See also the [changelog](https://github.com/actions/toolkit/blob/main/packages/core/RELEASES.md#1100).

**Comment by eregon** [comment]
Done in https://github.com/ruby/setup-ruby/commit/eae47962baca661befdfd24e4d6c34ade04858f7
