### ISSUE TITLE
Frequent `ETIMEDOUT` errors occuring

### ISSUE THREAD

**Issue by ianks** [ruby/setup-ruby#398]
### Ensure the following before filing this issue

- [X] I verified it reproduces with the latest version with `- uses: ruby/setup-ruby@v1` (see [Versioning policy](https://github.com/ruby/setup-ruby/blob/master/README.md#versioning))

- [X] I tried to reproduce the issue locally by following the workflow steps (including all commands done by `ruby/setup-ruby`, except for `Downloading Ruby` & `Extracting Ruby`),
and it did not reproduce locally (if it does reproduce locally, it's not a ruby/setup-ruby issue)

### Are you running on a GitHub-hosted runner or a self-hosted runner?

GitHub-hosted runner

### The workflow code or a link to the workflow file

```yaml
https://github.com/oxidize-rb/rb-sys/actions/runs/3457144103/jobs/5770380878
```

### Link to the log of a failed workflow job, or to a gist with the output

https://github.com/oxidize-rb/rb-sys/actions/runs/3457144103/jobs/5770380878

### The command and output of the failing step

```shell
Run ruby/setup-ruby-pkgs@v1
  ——————————————————    Ruby tasks using: ruby/setup-ruby/v1
Error: connect ETIMEDOUT 185.199.110.133:443
```

### Any other notes?

These have been happening sporadically for a month or so, but today I got 3 in a single build. May be missing a `retry` option somewhere?

**Comment by MSP-Greg** [comment]
I've seen the same 'type' of issue, but recently also saw the below.  The error you're seeing is executing js code, the below code is Ruby code (`bundle install`).

```
Fetching gem metadata from [https://rubygems.org/.](https://rubygems.org/)
  Network error while fetching
  https://rubygems.org/quick/Marshal.4.8/rake-compiler-1.1.1.gemspec.rz
```

JFYI, I download Actions logs and test artifacts from all ruby-loco builds, which also hits the GitHub API.  The code logs retries, and several weeks ago, I started seeing them regularly.

Hence, I think it's a GitHub network issue, and I assume they'll fix it sometime soon...

**Comment by MSP-Greg** [comment]
@ianks I suspect #399 should fix this.

**Comment by eregon** [comment]
I wonder if this might be timeouts from rubygems.org, cc @deivid-rodriguez 
Also https://github.com/ruby/setup-ruby/actions/runs/3457650272/jobs/5771287394 for example

**Comment by MSP-Greg** [comment]
@eregon I've seen that error also.

@ianks This repo is using the `downloadTool` function from @actions/tool-cache, which is part of [actions/toolkit](https://github.com/actions/toolkit).  I'm still seeing errors, but possibly less frequently.  May open an issue in a GitHub repo if it continues.

**Comment by eregon** [comment]
I guess this doesn't happen anymore, and anyway I don't think this action can do much about it.
