### ISSUE TITLE
Ruby 2.3.8 not available on Windows

### ISSUE THREAD

**Issue by deivid-rodriguez** [ruby/setup-ruby#40]
I noticed it when seeing this error (fantastic, clear, error message, by the way, kudos to that).

Not sure if it's expected or not.

If it's expected, a note should probably be added to the README like the one for ruby 2.2:

>  Ruby 2.2 resolves to 2.2.6 on Windows (last build from RubyInstaller) and 2.2.10 otherwise.

If it's not expected, can we add 2.3.8 for Windows? :)

**Comment by eregon** [comment]
Yes, it's the same issue, https://rubyinstaller.org/downloads/ doesn't have builds of Ruby 2.3 more recent than 2.3.3. Will add a note in the README.

**Comment by deivid-rodriguez** [comment]
Thanks @eregon!
