### ISSUE TITLE
JRuby 9.1.17.0, 9.2.1.0 - 9.2.20.0, 9.3.1.0 - 9.3.5.0 releases do not install on the latest Ubuntu

### ISSUE THREAD

**Issue by piotrmurach** [ruby/setup-ruby#406]
### Ensure the following before filing this issue

- [X] I verified it reproduces with the latest version with `- uses: ruby/setup-ruby@v1` (see [Versioning policy](https://github.com/ruby/setup-ruby/blob/master/README.md#versioning))

- [X] I tried to reproduce the issue locally by following the workflow steps (including all commands done by `ruby/setup-ruby`, except for `Downloading Ruby` & `Extracting Ruby`),
and it did not reproduce locally (if it does reproduce locally, it's not a ruby/setup-ruby issue)

### Are you running on a GitHub-hosted runner or a self-hosted runner?

GitHub-hosted runner

### The workflow code or a link to the workflow file

```yaml
https://github.com/piotrmurach/tty-markdown/blob/master/.github/workflows/ci.yml
```

### Link to the log of a failed workflow job, or to a gist with the output

https://github.com/piotrmurach/tty-markdown/actions/runs/3558016561/jobs/5976410851

### The command and output of the failing step

```shell
Downloading Ruby
  https://github.com/ruby/ruby-builder/releases/download/toolcache/jruby-9.2.13.0-ubuntu-22.04.tar.gz

Error: Unexpected HTTP response: 404
    at /home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:8075:25
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:7985:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Any other notes?

This seems to have stopped working in recent days. I can move on to using the latest JRuby fine. But I thought it might be helpful to you to know that the majority of jRuby releases on the latest Ubuntu 22 don't work and return 404.

**Comment by eregon** [comment]
9.2.13.0 is rather old (released in 2020), at the time it came out ubuntu 22.04 wasn't released yet.

I don't think these versions were ever built for 22.04, probably you were using ubuntu 20.04 before.

Could you use more recent versions?
See https://github.com/ruby/ruby-builder/releases/tag/toolcache for available versions on 22.04.
9.2.21.0 is available on 22.04.

This is still an issue because we should build those versions for 22.04 too for consistency.

**Comment by eregon** [comment]
> Could you use more recent versions?

Ah your issue already mentions yes to that.
Thank you for the report, indeed we should fix this.

**Comment by qisantanu** [comment]
![image](https://user-images.githubusercontent.com/46150713/207014090-378f728c-3e48-4886-bbef-d0409b18318f.png)
Suddenly my github actions are facing this error.

The actions were good 14 days ago.

**Comment by eregon** [comment]
That's most likely because you use `ubuntu-latest` and that changed to mean 22.04 I guess.
You can fix it by using `ubuntu-20.04`.

**Comment by eregon** [comment]
Fixed by https://github.com/ruby/ruby-builder/actions/runs/3688665959/jobs/6243726088.

**Comment by piotrmurach** [comment]
@eregon Thank you for fixing this issue and for your continued maintenance. 

My new approach to testing on JRuby is to download the latest version with the following automatically:

```yaml
ruby:
  - jruby-9.1
  - jruby-9.2 
  - jruby-9.3
  - jruby-9.4
  - jruby-head
```
