### ISSUE TITLE
Bundle install fails on 3.1.3

### ISSUE THREAD

**Issue by miharekar** [ruby/setup-ruby#407]
### Ensure the following before filing this issue

- [X] I verified it reproduces with the latest version with `- uses: ruby/setup-ruby@v1` (see [Versioning policy](https://github.com/ruby/setup-ruby/blob/master/README.md#versioning))

- [x] I tried to reproduce the issue locally by following the workflow steps (including all commands done by `ruby/setup-ruby`, except for `Downloading Ruby` & `Extracting Ruby`),
and it did not reproduce locally (if it does reproduce locally, it's not a ruby/setup-ruby issue)

### Are you running on a GitHub-hosted runner or a self-hosted runner?

GitHub-hosted runner

### The workflow code or a link to the workflow file

```yaml
https://github.com/miharekar/decent-visualizer/blob/main/.github/workflows/ruby-tests.yml
```

### Link to the log of a failed workflow job, or to a gist with the output

https://github.com/miharekar/decent-visualizer/actions/runs/3563650016

### The command and output of the failing step

```shell
> bundle install
Error: Error: The process '/opt/hostedtoolcache/Ruby/3.1.3/x64/bin/bundle' failed with exit code 34
    at ExecState._setResult (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:5340:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:5323:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:5217:27)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
```
```


### Any other notes?

Bundle install fails on 3.1.3. There were no other changes on the [commit](https://github.com/miharekar/decent-visualizer/commit/85b3439e8ac01bb95d2397e27449ad2477c81d63) except ruby and bundler version in Gemfile.lock.

**Comment by dentarg** [comment]
The error from `bundle install` is (at https://github.com/miharekar/decent-visualizer/actions/runs/3563650016/jobs/5986685052#step:4:181)

```
 Downloading debug-1.6.3 revealed dependencies not in the API or the lockfile
  (irb (>= 1.3.6), reline (>= 0.3.1)).
  Either installing with `--full-index` or running `bundle update debug` should
  fix the problem.
```

Does it happen if you re-run the job?

**Comment by dentarg** [comment]
I don't think this should have happened: https://github.com/miharekar/decent-visualizer/commit/85b3439e8ac01bb95d2397e27449ad2477c81d63#diff-89cade48462044ee1b672dc5f4c3ec250fbd29effcd8932096a23c1283c6731fL134-L135

```diff
    debug (1.6.3)
-      irb (>= 1.3.6)
-      reline (>= 0.3.1)
```

`irb` and `reline` are both runtime dependencies to `debug` according to https://rubygems.org/gems/debug/versions/1.6.3

**Comment by miharekar** [comment]
Huh, you think it's a problem with bundler itself? Neither bundle nor bundle update adds those dependencies. Even tried deleting the Gemfile.lock and doing it again. No dice.

**Comment by miharekar** [comment]
Ah, those 2 versions now come with ruby std lib: https://stdgems.org/reline/

**Comment by nickstanish** [comment]
There's an issue open in rubygems about this: https://github.com/rubygems/rubygems/issues/6082
I found a workaround to get my actions to succeed by manually repairing the Gemfile.lock in the meantime https://github.com/rubygems/rubygems/issues/6082#issuecomment-1329437635

**Comment by Petercopter** [comment]
I don't know if this is related to the problem here, or specific to my bundle, but I'm seeing `arm64-darwin-22` being added to my platforms. I'm on MacOS Ventura.

![image](https://user-images.githubusercontent.com/1493974/204346450-5888ada2-622b-40e8-8913-13b7f2b6f558.png)

**Comment by dentarg** [comment]
@Petercopter doesn't sound related and to be expected if you are on Ventura, as that is [Darwin 22](https://en.wikipedia.org/wiki/MacOS_Ventura#Release_history)

**Comment by Petercopter** [comment]
@dentarg Thank you, makes sense 👍 I know this Ruby release mentioned Ventura, so it being a new Darwin version would explain that.

**Comment by eregon** [comment]
This seems a Bundler issue, independent of setup-ruby, so I'll close this.

**Comment by viktorianer** [comment]
Maybe related to this fix

https://github.com/rubygems/rubygems/pull/6086

**Comment by jasonperrone** [comment]
This is closed and yet I don't know why. 

Still getting this error:
```
Downloading debug-1.7.1 revealed dependencies not in the API or the lockfile
(irb (>= 1.5.0), reline (>= 0.3.1)).
Either installing with `--full-index` or running `bundle update debug` should
fix the problem.
Error: The process '/opt/hostedtoolcache/Ruby/3.2.1/x64/bin/bundle' failed with exit code 34
```

Using bundler 2.4.7.

Tried putting irb and reline in the Gemfile, still didn't work. Since y'all seem to have gotten past this problem, perhaps you could share your wisdom?

**Comment by dentarg** [comment]
@jasonperrone Looks like people have commented with workarounds in https://github.com/ruby/debug/issues/898 and https://github.com/ruby/debug/issues/852

**Comment by jasonperrone** [comment]
I have a hard time getting my head around that because I have no problems on my local machine, it's only with Github Actions.

**Comment by jasonperrone** [comment]
Ok, think I got it. What was confusing me was I did have the proper dependecies in Gemfile.lock and it was still failing. But I tried again and it worked so maybe something was cached.
