### ISSUE TITLE
ruby/ruby-dev-builder - missing debug & rbs gems?

### ISSUE THREAD

**Issue by MSP-Greg** [ruby/setup-ruby#415]
Checked 3.1.3, and they are installed, but not in ruby head builds?

**Comment by eregon** [comment]
Do you have a log output showing they are missing?

**Comment by MSP-Greg** [comment]
No, I downloaded the Ubuntu & macOS archive files.  I can open/view them on Windows with 7z; I can't run the macOS, and I'd prefer to not install the Ubuntu version, as I've got my own master builds locally...

They aren't installed...

**Comment by eregon** [comment]
OK I'll take a look, weird

**Comment by MSP-Greg** [comment]
This is weird, not sure why it's happening.

See https://github.com/ruby/ruby-dev-builder/actions/runs/3665546238/jobs/6196697626#step:17:312, and note the list.

From the ruby-loco ucrt build, see https://github.com/MSP-Greg/ruby-loco/actions/runs/3669719811/jobs/6203751704#step:8:2256

Note that the ucrt builds ends with
```
rbs 2.8.1
typeprof 0.21.3
debug 1.7.0
```

Whereas the Ubuntu builds just shows `typeprof 0.21.3`.  Very odd. I'll check my Ubuntu local script...

**Comment by eregon** [comment]
I also tried and indeed https://github.com/eregon/setup-ruby-test/actions/runs/3670209767/jobs/6204587564 doesn't list them.

**Comment by eregon** [comment]
It's just `make` and `make install` in https://github.com/ruby/ruby-dev-builder/blob/1cdfbf1ebb4d417d43f968b35a416fba5987a3f0/.github/workflows/build.yml#L95-L96

**Comment by eregon** [comment]
This looks suspicious https://github.com/ruby/ruby-dev-builder/actions/runs/3665546238/jobs/6196697626#step:17:62
A bug in CRuby master maybe then?

**Comment by MSP-Greg** [comment]
Both [ruby/ruby Ubuntu script](https://github.com/ruby/ruby/blob/e1ca089b5dddd30c4ac8de9c7ec9e52948768117/.github/workflows/ubuntu.yml#L99) and my local script run `make prepare-gems` before `make install`.  Odd thing is ruby-loco doesn't.  But, the Windows make file is different from the others.  Not.sure.

**Comment by MSP-Greg** [comment]
I was always 'quickly' at my desk earlier.  I just noticed all the builds here show a last line of the following in `make install`:
```
skipped bundled gems: /home/runner/work/ruby-dev-builder/ruby-dev-builder/gems/debug-1.7.0.gem /home/runner/work/ruby-dev-builder/ruby-dev-builder/gems/rbs-2.8.1.gem
```

My local Ubuntu install also shows the same.  That line is generated by `tool/rbinstall.rb`, which looks like it caused by the lines you linked to:
```
rm -rf .bundle/gems/debug-1.7.0/
rm -rf .bundle/gems/rbs-2.8.1/
```

I believe the only workflow in ruby/ruby that runs `make install` is mingw.yml, which does install both gems, but it may use different build scripts?

Or, maybe you've found the problem.  If not, maybe an issue in 'bugs.ruby-lang.org'?  I'm not experienced with complex build systems like Ruby, so rather unlikely I can find the code...

I get very frustrated by these install issues, as ruby core prefers to assume that `make install` just magically works.  It took 28 seconds in a recent Ubuntu job, and 41 sec in a macOS job.  Pretty small addition to the current job run times...

**Comment by hsbt** [comment]
> It's just `make` and `make install` in https://github.com/ruby/ruby-dev-builder/blob/1cdfbf1ebb4d417d43f968b35a416fba5987a3f0/.github/workflows/build.yml#L95-L96

It needs to `make up` between `make` and `make install`.

And I also confirm to remove `rbs` and `debug` with `make prepare-gems`. I'm not sure this is intentional behavior.

**Comment by MSP-Greg** [comment]
@hsbt

> It needs to `make up` between `make` and `make install`.

Thank you.  I could repo this locally (WSL2/Ubuntu) and adding `make up` fixes the issue, as debug & rbs are properly installed.  Also, the `rm` lines no longer appear in the `make install` log.

**Comment by eregon** [comment]
https://github.com/ruby/ruby/blob/master/doc/contributing/building_ruby.md doesn't mention `make up`, only `./autogen.sh
` and `make install`. Does it mean that documentation is outdated/incorrect?
I guess it's still a bug that those gems are not present with just `make install`.
Maybe @nobu's commit above fixes it?

**Comment by MSP-Greg** [comment]
@nobu

Thank you.  I just built the following locally (without `make up`), and they both installed rbs & debug properly:

```
ruby 3.2.0dev (2022-12-12T20:04:00Z master 8e619b8e0e) [x86_64-linux]
ruby 3.2.0dev (2022-12-12T20:13:46Z master 1004d693b7) [x64-mswin64_140]
```

I also noticed that their extension files (*.so) are contained only in the platform specific folder within `lib/ruby/gems/3.2.0+3/extensions`. Very helpful when one might have multiple Windows builds using gems within `--user-install`...

**Comment by MSP-Greg** [comment]
@eregon

JFYI, rbs does have a bin file.  In ruby-loco I use the following for a bin file check.  Something like it could be added to `ruby-dev-builder`...

```
error=0

printf "bundle version: "
bundle version
error=$((error + $?))

printf "gem  --version: "
gem --version
error=$((error + $?))

printf "irb  --version: "
irb --version
error=$((error + $?))

printf "racc --version: "
racc --version
error=$((error + $?))

printf "rake --version: "
rake --version
error=$((error + $?))

printf "rbs  --version: "
rbs --version
error=$((error + $?))

printf "rdoc --version: "
rdoc --version
error=$((error + $?))

ruby -v

if [ "$error" != 0 ]; then exit 1; fi
```

**Comment by eregon** [comment]
Fixed upstream, all good.

I think it would be best to have such tests for "after make install" upstream in ruby/ruby.
In fact for such use cases I'd rather run everything on make-installed ruby, not on partially-built ruby.
