### ISSUE TITLE
Fails to install bundler on JRuby 9.2.* when bundler-cache is true

### ISSUE THREAD

**Issue by piotrmurach** [ruby/setup-ruby#425]
### Ensure the following before filing this issue

- [X] I verified it reproduces with the latest version with `- uses: ruby/setup-ruby@v1` (see [Versioning policy](https://github.com/ruby/setup-ruby/blob/master/README.md#versioning))

- [X] I tried to reproduce the issue locally by following the workflow steps (including all commands done by `ruby/setup-ruby`, except for `Downloading Ruby` & `Extracting Ruby`),
and it did not reproduce locally (if it does reproduce locally, it's not a ruby/setup-ruby issue)

### Are you running on a GitHub-hosted runner or a self-hosted runner?

GitHub-hosted runner

### The workflow code or a link to the workflow file

```yaml
https://github.com/piotrmurach/slideck/blob/master/.github/workflows/ci.yml
```

### Link to the log of a failed workflow job, or to a gist with the output

https://github.com/piotrmurach/slideck/actions/runs/3776093709/jobs/6419229630#step:3:54

### The command and output of the failing step

```shell
Installing Bundler
  /home/runner/.rubies/jruby-9.2.21.0/bin/gem install bundler -v ~> 2.0
  ERROR:  Error installing bundler:
  	The last version of bundler (~> 2.0) to support your Ruby & RubyGems was 2.3.26. Try installing it with `gem install bundler -v 2.3.26`
  	bundler requires Ruby version >= 2.6.0. The current ruby version is 2.5.8.0.
  Took   8.03 seconds
  ::endgroup::
Error: Error: The process '/home/runner/.rubies/jruby-9.2.21.0/bin/gem' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:5344:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:5327:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:5221:27)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
```

### Any other notes?

I'm not sure whether this is to be treated as a special case [similar to JRuby 9.1](https://github.com/ruby/setup-ruby/blob/4e1189c53d558b920b51b4cdb7161205ddb7b274/bundler.js#L103) and therefore drop down to using Bundler 1 or limit installation to Bundler 2.3.

**Comment by eregon** [comment]
JRuby 9.2 targets 2.5 so it should probably be the same fix as the recent fix for CRuby 2.3-2.5. PR welcome.

BTW is JRuby 9.2 still supported?
I would be happier if I don't have to support more than 2 release series per Ruby implementation except for CRuby where it seems unavoidable.

**Comment by piotrmurach** [comment]
PR submitted.

I'm not sure about JRuby 9.2 support. I don't use JRuby myself though prefer to run my CI against it as well.

Given it is on par with Ruby 2.5 then the answer is probably that it's unsupported. 

Since JRuby 9.2 is still on the list of supported Rubies for this action, I felt it would be good for it to still work with automatic bundler installation.

I totally can you see your point regarding supporting older versions. It definitely adds to the support burden. The only comment I'd make is to consider releasing a new version of the action when you drop the support.

**Comment by piotrmurach** [comment]
This is to confirm that the issue is resolved:

```
 Ruby 2.3.2 - 2.5 only works with Bundler 2.3
  /home/runner/.rubies/jruby-9.2.21.0/bin/gem install bundler -v ~> 2.3.0
  Successfully installed bundler-2.3.26
  1 gem installed
  Took   8.06 seconds
```
