### ISSUE TITLE
Bundler claims Gemfile changed, but saved gemfile/gemfile.lock show no changes from committed versions

### ISSUE THREAD

**Issue by CamJN** [ruby/setup-ruby#438]
### Ensure the following before filing this issue

- [X] I verified it reproduces with the latest version with `- uses: ruby/setup-ruby@v1` (see [Versioning policy](https://github.com/ruby/setup-ruby/blob/master/README.md#versioning))

- [X] I tried to reproduce the issue locally by following the workflow steps (including all commands done by `ruby/setup-ruby`, except for `Downloading Ruby` & `Extracting Ruby`),
and it did not reproduce locally (if it does reproduce locally, it's not a ruby/setup-ruby issue)

### Are you running on a GitHub-hosted runner or a self-hosted runner?

GitHub-hosted runner

### The workflow code or a link to the workflow file

```yaml
https://github.com/getargv/getargv_ruby/actions/runs/3844482254/workflow
```

### Link to the log of a failed workflow job, or to a gist with the output

https://gist.github.com/CamJN/8777d56304e09cbebd78c5fa79010ea7

### The command and output of the failing step

```shell
bundle install
  /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/bin/bundle config --local path /Users/runner/work/getargv_ruby/getargv_ruby/getargv_ruby/vendor/bundle
  /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/bin/bundle config --local deployment true
  Cache key: setup-ruby-bundler-cache-v4-macos-12-ruby-3.2.0-cachever:2-Gemfile.lock-62bc0af39308f8e3a39e7b48a4408b8486339f43458403b2525ea22bc40c1156
  /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/bin/bundle install --jobs 4
  You are trying to install in deployment mode after changing
  your Gemfile. Run `bundle install` elsewhere and add the
  updated Gemfile.lock to version control.
  
  If this is a development machine, remove the
  /Users/runner/work/getargv_ruby/getargv_ruby/getargv_ruby/Gemfile freeze
  by running `bundle config unset deployment`.
  
  The gemspecs for path gems changed
  Took   1.78 seconds
```

### Any other notes?

I saved and downloaded the Gemfile and Gemfile.lock from the run and they are the same as the committed versions. Locally running the below commands manually doesn't reproduce the issue:

```
bundle config --local path ./vendor/bundle
bundle config --local deployment true
bundle install --jobs 4
```

**Comment by eregon** [comment]
Bundler says `The gemspecs for path gems changed`.
And I found https://github.com/getargv/getargv_ruby/blob/f5a82b8af82f35c65cd1413148c812e38e6c879f/Gemfile.lock#L4

https://github.com/getargv/getargv_ruby/actions/runs/3844482254/jobs/6547620950 ran on macOS 12.6.2 = darwin-21.6.0
So darwin-21 vs darwin-22.

The platforms seem to include both though: https://github.com/getargv/getargv_ruby/blob/f5a82b8af82f35c65cd1413148c812e38e6c879f/Gemfile.lock#L87-L95

This seems an issue of Bundler, could you open an issue there?

**Comment by eregon** [comment]
https://github.com/getargv/getargv_ruby/blob/f5a82b8af82f35c65cd1413148c812e38e6c879f/getargv_ruby.gemspec#L43 probably causes it. I don't think the gemspec platform should be set manually (unless you are pushing a precompiled gem maybe).

**Comment by vivekbisen** [comment]
When I ran into this issue, it was because I changed the version of my gem and forgot to run `bundle install` locally. So, my `Gemfile.lock` was out-of-date. 🤦🏽‍♂️

**Comment by CamJN** [comment]
@vivekbisen I definitely ran `bundle install` locally, the platform thing @eregon mentioned looks like a promising lead though, I thought that gems with native C code need the platform mentioned in the spec, but I might have been mistaken I have to investigate if the gem is precompiled or compiles on the user's machine.

**Comment by andyw8** [comment]
Just ran into this. Running `bundle update --bundler` fixed it. (it updated `Gemfile.lock` from 2.3.14 to 2.4.6).
