### ISSUE TITLE
Ruby 2.3 to 2.5 - cannot update RubyGems

### ISSUE THREAD

**Issue by andrykonchin** [ruby/setup-ruby#441]
### Ensure the following before filing this issue

- [X] I verified it reproduces with the latest version with `- uses: ruby/setup-ruby@v1` (see [Versioning policy](https://github.com/ruby/setup-ruby/blob/master/README.md#versioning))

- [X] I tried to reproduce the issue locally by following the workflow steps (including all commands done by `ruby/setup-ruby`, except for `Downloading Ruby` & `Extracting Ruby`),
and it did not reproduce locally (if it does reproduce locally, it's not a ruby/setup-ruby issue)

### Are you running on a GitHub-hosted runner or a self-hosted runner?

GitHub-hosted runner

### The workflow code or a link to the workflow file

```yaml
https://github.com/Dynamoid/dynamoid/blob/master/.github/workflows/ci.yml
```

### Link to the log of a failed workflow job, or to a gist with the output

https://github.com/Dynamoid/dynamoid/actions/runs/3864041701/jobs/6586597944

### The command and output of the failing step

```shell
Updating RubyGems

/opt/hostedtoolcache/Ruby/2.5.9/x64/bin/gem --version
  2.7.6.3
  Default RubyGems version is 2.7.6
  Updating RubyGems to latest version
  /opt/hostedtoolcache/Ruby/2.5.9/x64/bin/gem update --system
  ERROR:  Error installing rubygems-update:
  	There are no versions of rubygems-update (= 3.4.3) compatible with your Ruby & RubyGems
  	rubygems-update requires Ruby version >= 2.6.0. The current ruby version is 2.5.0.
  ERROR:  While executing gem ... (NoMethodError)
      undefined method `version' for nil:NilClass
  Updating rubygems-update
  Took   3.06 seconds
```

### Any other notes?

The last successful build was on Dec 22 - https://github.com/Dynamoid/dynamoid/actions/runs/3757073712/jobs/6383867862

**Comment by eregon** [comment]
@deivid-rodriguez Do you know about this?
Is it OK if I assign this to you?

Maybe it's related to `gem install bundler` on old RubyGems not finding the correct version which matches the `required_ruby_version`?

**Comment by deivid-rodriguez** [comment]
Yep, it's the same issue.

When end user specifies `rubygems: latest`, this action runs `gem update --system`, and that command suffers from the same issue if the version we're upgrading from is older than 3.2.33. Just like `gem install bundler`, the issue surfaced as soon as we released a RubyGems version that does not support Ruby 2.3.

Ideally this action would run `gem update --system 3.3.26` instead when `latest` is specified on Ruby 2.3, 2.4, or 2.5, since that's as far as we can go on those rubies.

**Comment by eregon** [comment]
@andrykonchin Could you try with `rubygems: default`? Is there a need for `rubygems: latest` in that workflow?
I would recommend the same for Bundler, to just use `setup-ruby`'s defaults.
FWIW I found that https://github.com/Dynamoid/dynamoid/pull/536/commits/073374e4bc0878664e56961d6deaa95bdc922569 introduced the change to use both latest.

**Comment by eregon** [comment]
@deivid-rodriguez Thank you for the explanation. Is there a way to `gem update --system ~> 3.3.0`, so it would pick a potential 3.3.27 etc?

**Comment by deivid-rodriguez** [comment]
I have no idea so I tried it and it does not seem to work, no.

**Comment by andrykonchin** [comment]
Thank you 🎆.

Yeah, there is no any need to use the latest RubyGems and Bundler I believe in our case.

**Comment by eregon** [comment]
This is now fixed in https://github.com/ruby/setup-ruby/releases/tag/v1.165.0
