### ISSUE TITLE
Incorrect ruby version. Should be 3.0, but 3.2 is installed.

### ISSUE THREAD

**Issue by mscottford** [ruby/setup-ruby#442]
### Ensure the following before filing this issue

- [X] I verified it reproduces with the latest version with `- uses: ruby/setup-ruby@v1` (see [Versioning policy](https://github.com/ruby/setup-ruby/blob/master/README.md#versioning))

- [X] I tried to reproduce the issue locally by following the workflow steps (including all commands done by `ruby/setup-ruby`, except for `Downloading Ruby` & `Extracting Ruby`),
and it did not reproduce locally (if it does reproduce locally, it's not a ruby/setup-ruby issue)

### Are you running on a GitHub-hosted runner or a self-hosted runner?

GitHub-hosted runner

### The workflow code or a link to the workflow file

```yaml
- name: "[Setup] - Install Ruby"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0 # Not needed with a .ruby-version file
          bundler-cache: true
```
Source: https://github.com/corgibytes/freshli-agent-java/blob/29e5e73f49c2faef647368db90bfd6c0e7d7a4e7/.github/workflows/ci.yml#LL34-L38C30

### Link to the log of a failed workflow job, or to a gist with the output

https://github.com/corgibytes/freshli-agent-java/actions/runs/3857279757/jobs/6607269906

### The command and output of the failing step

```shell
Run ruby/setup-ruby@v1
  with:
    ruby-version: 3
    bundler-cache: true
  env:
    BUILD_ARTIFACTS_FOLDER: build_artifacts
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/8.0.352-8/x64
    JAVA_HOME_8_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/8.0.352-8/x64
Modifying PATH
  Entries added to PATH to use selected Ruby:
    /opt/hostedtoolcache/Ruby/3.2.0/x64/bin
Downloading Ruby
  https://github.com/ruby/ruby-builder/releases/download/toolcache/ruby-3.2.0-ubuntu-22.04.tar.gz
  Took   0.37 seconds
```
```


### Any other notes?

This started happening recently. I'm going to try and figure out which release introduced the failure.

**Comment by MSP-Greg** [comment]
Above you show both `ruby-version: 3` and `ruby-version: 3.0`.  The yaml parser in Actions interprets both as an integer `3`, so they will match the most recent (latest) Ruby 3.x.y release.

Or, **the yaml parser truncates trailing zeros**.  So, it you want the latest Ruby 3.0.x, you need to quote the value to force it to be parsed as a string, eg `"3.0"`.

**Comment by mscottford** [comment]
Doh! That makes sense. Giving that a try now. :)

**Comment by mscottford** [comment]
That worked. Thank you so much for the quick reply!
