### ISSUE TITLE
Setting Bundler version and not having it superseded by the new env var.

### ISSUE THREAD

**Issue by RyanRennCN** [ruby/setup-ruby#443]
Hello,

With this most recent [commit](https://github.com/ruby/setup-ruby/commit/319066216501fbd5e2d568f14b7d68c19fb67a5d) to add BUNDLER_VERSION after installing Bundler, it has impacted the behavior of one of our jobs where two different versions of bundler are used in two different sub-folders.

The first one uses 1.17.3 and this commit then writes out an env var with this version that is then used by the second Setup Ruby action. I tried setting the bundler version as a Ruby input on the second action, but it seems that the env var overwrites it. 

For now, I rolled both actions back to use ruby/setup-ruby@v1.133.0, but I would like to understand if there is something different that I should be doing now to set the correct bundler version because of this latest change?

Code:
      
      - name: Set up Ruby for First Folder
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
          bundler-cache: true
          working-directory: ./first_folder
      
      - name: Set up Ruby for Second Folder
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
          bundler-cache: true 
          working-directory: ./second_folder

Thank you!

**Comment by eregon** [comment]
Please file the issue again using the template, I don't have nearly enough information here to understand the issue. For instance I need to see the logs, what you expect, the more complete workflow file, etc.

**Comment by RyanRennCN** [comment]
If anyone sees this later, the new issue is [this](https://github.com/ruby/setup-ruby/issues/444).
