### ISSUE TITLE
Please consider adding ARM support

### ISSUE THREAD

**Issue by cayblood** [ruby/setup-ruby#453]
I would like to run this on a more cost-effective AWS instance. It would be nice if you had support for ARM. Will try to work on a PR for you.

**Comment by dentarg** [comment]
See https://github.com/ruby/setup-ruby/issues/90 for previous discussion on this

**Comment by eregon** [comment]
Yeah, duplicate. And not possible until GitHub-hosted runners support arm64.

**Comment by eregon** [comment]
With https://github.com/ruby/setup-ruby/pull/473 this action now gives instructions for how to make it work for self-hosted runners not matching a GitHub-hosted runner image.
