### ISSUE TITLE
Add action typing

### ISSUE THREAD

**Issue by krzema12** [ruby/setup-ruby#458]
Hi @eregon!

I'd like to ask you to add a piece of documentation. However, it won't be yet another piece of Markdown. When working with various actions, I discovered that it's challenging to know what type of data is needed for the inputs of an action, the same for outputs. Every action has its own custom way of documenting it, if it documents it at all, which makes it challenging for humans and automation to work with various actions. I figured there must be a way to address it.

I looked for an inspiration in other ecosystems where types were added later, like TypeScript adding types for JavaScript, or type hints in the Python world. I decided to create [github-actions-typing](https://github.com/krzema12/github-actions-typing) which aspires to be the standardized way of typing your action's API. Onboarding is as easy as adding an extra `action-types.yml` file to your repository root, and (optionally, although highly recommended) adding a simple GitHub workflow that validates this new file. It has no negative effects on current action consumers, they continue to use the action as if the file wasn't there.

In this feature request, I would like to ask you if you're open to introducing such typings in your action. You wouldn't be first - there're already other actions using it, like e.g.: [microsoft/setup-msbuild](https://github.com/microsoft/setup-msbuild), [Vampire/setup-wsl](https://github.com/Vampire/setup-wsl), [ReactiveCircus/android-emulator-runner](https://github.com/ReactiveCircus/android-emulator-runner) (full list of actions using the validation workflow is [here](https://github.com/krzema12/github-actions-typing/network/dependents))
If your answer is "yes", feel free to either add it yourself, or let me know - me or some of the other contributors would be happy to post a PR. We're also open to any kind of questions and feedback.

**Comment by eregon** [comment]
It's clear from https://github.com/ruby/setup-ruby/blob/master/action.yml they are all strings, except bundler-cache which is boolean, as documented.
And of course GHA converts every input to String anyway before passing it to the actions (since it goes through env vars).

So I don't see the value, if it's an extra file people would need to look at to find the same information already in action.yml, that's just worse.
Maybe if some editors/IDEs would take advantage of it. But that doesn't seem the case (from the README of github-actions-typing).

Also, how would you type the ruby-version input which can be either a float or a string?

I close to mark no intention to do this.

**Comment by krzema12** [comment]
@eregon 

> It's clear from https://github.com/ruby/setup-ruby/blob/master/action.yml they are all strings, except bundler-cache which is boolean, as documented.

Partially yes. I'd argue that `rubygems` and `bundler` could be modeled as enums. The documentation is now purely human-readable, the types are still missing.

> And of course GHA converts every input to String anyway before passing it to the actions (since it goes through env vars).

It doesn't matter in this case what happens under the hood. The goal of this project is to provide type-safety on top of GitHub not caring about typing.

> So I don't see the value, if it's an extra file people would need to look at to find the same information already in action.yml, that's just worse.

Yes, there's some duplication, but I don't agree it's the same information. It's machine readable.

> Maybe if some editors/IDEs would take advantage of it. But that doesn't seem the case (from the README of github-actions-typing).

There's already one tool that makes use of the typings already introduced in multiple actions, see https://github.com/krzema12/github-workflows-kt. Regarding IDE support, that's actually a great idea!

> Also, how would you type the ruby-version input which can be either a float or a string?

Currently, as a string. Union types are not yet supported. However, I'd type it as string anyway since `3.2.1` is definitely not a float, and assuming e.g. `3.2` being a float is an overinterpretation.

> I close to mark no intention to do this.
👌
