### ISSUE TITLE
Could this have ARM support

### ISSUE THREAD

**Issue by sreid99** [ruby/setup-ruby#468]
As per #453, this would be very useful for my ARM builds.

Ideally it would work with Buildjet's ARM based github action runners - https://buildjet.com/for-github-actions/docs/runners

**Comment by eregon** [comment]
With https://github.com/ruby/setup-ruby/pull/473 this action now gives instructions for how to make it work for self-hosted runners not matching a GitHub-hosted runner image.

**Comment by xcskier56** [comment]
FYI @sreid99 I ran into the same issue as you on Buildjet. I solved this by creating a local action that will build and then cache the built ruby using Buildjet's cache. Here's a gist you use https://gist.github.com/xcskier56/8559e89d53e02babecc87a52166566e5
