### ISSUE TITLE
Upgrade from ubuntu18 to ubuntu22 failed

### ISSUE THREAD

**Issue by PavelSusloparov** [ruby/setup-ruby#469]
### Ensure the following before filing this issue

- [X] I verified it reproduces with the latest version with `- uses: ruby/setup-ruby@v1` (see [Versioning policy](https://github.com/ruby/setup-ruby/blob/master/README.md#versioning))

- [] I tried to reproduce the issue locally by following the workflow steps (including all commands done by `ruby/setup-ruby`, except for `Downloading Ruby` & `Extracting Ruby`),
and it did not reproduce locally (if it does reproduce locally, it's not a ruby/setup-ruby issue)

### Are you running on a GitHub-hosted runner or a self-hosted runner?

GitHub-hosted runner

### The workflow code or a link to the workflow file

```yaml
- uses: ruby/setup-ruby@v1
  env:
    ImageOS: ubuntu22
  with:
    ruby-version: 3.0.2
    bundler-cache: true
```
```


### Link to the log of a failed workflow job, or to a gist with the output

https://gist.github.com/PavelSusloparov/9fc9e328dd17e06751eff1521e8e9340

### The command and output of the failing step

```shell
Run ruby/setup-ruby@v1
/bin/docker exec  1e6d83e0d3886871d7791a6945dd4dd64b228596261ae4c98cfdb84c4b9b19d1 sh -c "cat /etc/*release | grep ^ID"
Modifying PATH
  Entries added to PATH to use selected Ruby:
    /opt/hostedtoolcache/Ruby/3.0.2/x64/bin
Downloading Ruby
  https://github.com/ruby/ruby-builder/releases/download/toolcache/ruby-3.0.2-ubuntu-22.04.tar.gz
  Took   0.87 seconds
Extracting  Ruby
  /bin/tar -xz -C /opt/hostedtoolcache/Ruby/3.0.2 -f /__w/_temp/dec130f4-1643-4745-bea1-e95b68fd6c1b
  Took   0.40 seconds
Print Ruby version
  /opt/hostedtoolcache/Ruby/3.0.2/x64/bin/ruby --version
  /opt/hostedtoolcache/Ruby/3.0.2/x64/bin/ruby: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /opt/hostedtoolcache/Ruby/3.0.2/x64/bin/ruby)
  /opt/hostedtoolcache/Ruby/3.0.2/x64/bin/ruby: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/libruby.so.3.0)
  /opt/hostedtoolcache/Ruby/3.0.2/x64/bin/ruby: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/libruby.so.3.0)
  /opt/hostedtoolcache/Ruby/3.0.2/x64/bin/ruby: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/libruby.so.3.0)
  /opt/hostedtoolcache/Ruby/3.0.2/x64/bin/ruby: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/libruby.so.3.0)
  Took   0.00 seconds
Error: The process '/opt/hostedtoolcache/Ruby/3.0.2/x64/bin/ruby' failed with exit code 1
```
```


### Any other notes?

Ubuntu18 support was removed in https://github.com/ruby/setup-ruby yesterday.
I tried to upgrade to ubuntu22, but this failed with the error I provided in above.

**Comment by mlyskawinski** [comment]
Having the same issue, please bring back ubuntu -18, as this breaks a lot of pipelines

**Comment by PavelSusloparov** [comment]
Yes please ^^

**Comment by PavelSusloparov** [comment]
ended up stopping using the action in favor of a ruby docker container with the ```bundle install --frozen``` step.

**Comment by MSP-Greg** [comment]
> please bring back ubuntu -18

That choice is made by GitHub, not by anyone involved in the repo.

See https://github.com/actions/runner-images

**Comment by eregon** [comment]
See https://github.com/ruby/setup-ruby/releases/tag/v1.139.0
macos-10.15 and ubuntu-18.04 are deprecated and have a brownout period every week, so it's no longer possible to reliably build on those platforms with GH runners.
That means it's not possible to build Ruby binaries on these images reliably, and also jobs on such images fail during the brownout periods and will be completely removed in a month anyway.

So just change `ubuntu-18.04` by `ubuntu-20.04` or `ubuntu-22.04` or `ubuntu-latest`.

You can also stick to `v1.138.0`, but obviously your workflow will be broken on April 1 then: https://github.com/actions/runner-images/issues/6002.

If you are not using GitHub-hosted runners then indeed this is unfortunate, but unavoidable as Rubies are built on GitHub-hosted runners.

**Comment by eregon** [comment]
Ah, I misread, the original report is about something failing on ubuntu-22.04, I'll look at that.

**Comment by eregon** [comment]
Ruby 3.0.5 works fine on Ubuntu 22.04: https://github.com/ruby/setup-ruby/actions/runs/4285836825/jobs/7464657539
The easiest workaround is to use the latest patch release of your Ruby major.minor (e.g. 3.0.x), previous versions are unsupported by CRuby and have known bugs.

So it seems an issue for older Rubies due to what seems a glibc update in Ubuntu 22.04. That's surprising. I'll investigate more later. We can likely rebuild those, but a glibc update is rather unexpected for a Ubuntu LTS.

**Comment by eregon** [comment]
It works fine on GitHub-hosted runners, as proven here:
https://github.com/eregon/setup-ruby-test/actions/runs/4297309313/jobs/7490118600

You said you used `GitHub-hosted runner` but then you set `ImageOS: ubuntu22` manually, that doesn't make any sense.
So either:
* you use GitHub-hosted runners by specifying `runs-on: ubuntu-22.04` and don't specify `ImageOS` (that's telling this action the incorrect OS, that's pretty evil)
* you are using a self-hosted runner but your image is not actually based on Ubuntu 22.04.

Summary: do not set `ImageOS`, that should be set in the runner, never in the workflow.

**Comment by eregon** [comment]
I guess I should bring back the code that gets the image version from the OS files, since people seem to misuse `ImageOS` and don't understand implications of it :(

**Comment by eregon** [comment]
https://github.com/ruby/setup-ruby/pull/473 so ImageOS will be ignored now.
