### ISSUE TITLE
bundle install not respecting Gemfile.lock dependencies for debug gem

### ISSUE THREAD

**Issue by jasonperrone** [ruby/setup-ruby#481]
### Ensure the following before filing this issue

- [X] I verified it reproduces with the latest version with `- uses: ruby/setup-ruby@v1` (see [Versioning policy](https://github.com/ruby/setup-ruby/blob/master/README.md#versioning))

- [X] I tried to reproduce the issue locally by following the workflow steps (including all commands done by `ruby/setup-ruby`, except for `Downloading Ruby` & `Extracting Ruby`),
and it did not reproduce locally (if it does reproduce locally, it's not a ruby/setup-ruby issue)

### Are you running on a GitHub-hosted runner or a self-hosted runner?

GitHub-hosted runner

### The workflow code or a link to the workflow file

```
https://gist.github.com/jasonperrone/0995819e15b025a782478e564a44b55e
```

### Link to the log of a failed workflow job, or to a gist with the output

```
https://gist.github.com/jasonperrone/519ad9d8e3648774d788468c3ba89c73
```

### The command and output of the failing step

```shell
2023-03-11T16:24:48.1140965Z Downloading debug-1.7.1 revealed dependencies not in the API or the lockfile
2023-03-11T16:24:48.1141754Z (irb (>= 1.5.0), reline (>= 0.3.1)).
2023-03-11T16:24:48.1142440Z Either installing with `--full-index` or running `bundle update debug` should
2023-03-11T16:24:48.1143318Z fix the problem.
```

### Any other notes?

My Gemfile.lock has debug (1.7.1), irb (1.6.3) and reline (0.3.2). So why are the dependencies failing?

**Comment by jasonperrone** [comment]
I don't have this problem locally nor on any of the four servers I deploy to.

**Comment by jasonperrone** [comment]
Doubt this will help other people, but since I am using my Action only to run my tests, I didn't need anything from the development group of my Gemfile. So I just put
```
 env:
      BUNDLE_WITHOUT: development
```
so it won't even try to install gems like debug that I don't need to run my tests.

Cheating, I know...

**Comment by eregon** [comment]
It's a CRuby bug: https://github.com/rubygems/rubygems/issues/6082
