### ISSUE TITLE
cache without installing

### ISSUE THREAD

**Issue by akostadinov** [ruby/setup-ruby#498]
Hello, I want to speed up container image builds so my idea is to cache the gems, then use the cache during the build.

For this I need the cache to be of the non-installed gem files. Ideally it would cache files for all PLATFORMS listed in `Gemfile.lock`.

I saw a related issue #489 but it is about running in an image, not building one.

Also I saw #451 but it will not help when building multiple architectures. At least cache would need to be different for each. Also layers unnecessary increase image size.

**Comment by eregon** [comment]
Caching `.gem` files is out of scope of this action.
This action is meant to be used on runners directly, not inside a Docker image, and not to build a Docker image.

**Comment by eregon** [comment]
Also BTW caching .gem is unlikely to provide any speedup, it's a download vs a few downloads.
