### ISSUE TITLE
truffleruby+graalvm-head is failing because of a moved URL

### ISSUE THREAD

**Issue by halostatue** [ruby/setup-ruby#499]
This can be seen in this [failing workflow](https://github.com/KineticCafe/app_identity/actions/runs/4739650221/jobs/8414677948#logs) and should be resolved when rbenv/ruby-build is updated to resolve this, or if the GraalVM download names are reverted.

See this [rbenv/ruby-build failing build report](https://github.com/rbenv/ruby-build/discussions/2188) for more information.

**Comment by eregon** [comment]
Fixed in https://github.com/rbenv/ruby-build/commit/fca13fbea836ad3cc37da35925b11f892886a021
