### ISSUE TITLE
ruby 3.3.0-preview1 setup-ruby file

### ISSUE THREAD

**Issue by jasnow** [ruby/setup-ruby#503]
Please add a setup-ruby version for https://www.ruby-lang.org/en/news/2023/05/12/ruby-3-3-0-preview1-released .
Thanks

**Comment by eregon** [comment]
It failed to upload in https://github.com/ruby/ruby-builder/actions/runs/4962171899/jobs/8879901194
Maybe there is a limit of 512 assets per release: https://github.com/ruby/ruby-builder/releases/tag/toolcache

**Comment by eregon** [comment]
https://github.com/ruby/setup-ruby/pull/504

**Comment by jasnow** [comment]
@eregon - How will I tell when this is released?

**Comment by eregon** [comment]
It's released.

**Comment by jasnow** [comment]
Got it to work - Thanks so much.
