### ISSUE TITLE
Ability to Pass Flags to Ruby Build (Jemalloc Support)

### ISSUE THREAD

**Issue by ashwinv11** [ruby/setup-ruby#507]
Hello!

I was wondering if there were any way to pass `RUBY_CONFIGURE_OPTS` similar to how ruby-build works:

`RUBY_CONFIGURE_OPTS="--with-jemalloc=$(brew --prefix jemalloc)" asdf install ruby 3.2.2`. From what I understand, this might be a limitation due to what release types are available in the [ruby-builder repo](https://github.com/ruby/ruby-builder/releases)?

Could we consider adding the ability to publish builds for Ubuntu with `jemalloc`?

Thank you!

**Comment by dentarg** [comment]
> Could we consider adding the ability to publish builds for Ubuntu with `jemalloc`?

Seeing https://github.com/ruby/setup-ruby/issues/505#issuecomment-1555046445 this is probably unlikely

I think it is possible to workaround with `LD_PRELOAD`, see https://github.com/docker-library/ruby/issues/182 for lots of comments on that and it looks like [this Heroku buildpack](https://github.com/gaffneyc/heroku-buildpack-jemalloc/blob/1f8d766eba5a1c5978a48a55aeffe5fbd5b7bc4d/bin/compile) also uses that technique.

**Comment by ashwinv11** [comment]
Thanks for the context and for linking me to the other thread! Will try out the `LD_PRELOAD` workaround and report back 👍🏾
