### ISSUE TITLE
Please support ARM64 based build platforms

### ISSUE THREAD

**Issue by rsavage-nozominetworks** [ruby/setup-ruby#513]
As more and more developers are including ARM64 based build platforms, I am surprised and disappointed that this action does not support it yet.

**Comment by MSP-Greg** [comment]
https://github.com/search?q=repo%3Aruby%2Fsetup-ruby+ARM64&type=issues

All Ruby builds used by this action are created on GitHub Actions runners.  At present, they do not offer any ARM64 systems/runners.
