### ISSUE TITLE
Inputs not listed in README documentation

### ISSUE THREAD

**Issue by jared-bloomer** [ruby/setup-ruby#514]
I was unable to locate any information on workflow inputs in the documentation. For example, through just random poking around in various `.js` files in this repo I discovered `bundler` was an input option. It was only through trial and error did I figure out how to use it. Seems like the inputs section of the README is missing and needs to be updated to be in compliance with recommended Github Action Standards. Please consider adding a section to your README that spells out this information. Maybe something simple like this

## Inputs

| Name | Required | Default | Description |
| ---- | -------- | ------- | ----------- |
| working-directory | false | "true" | Default working directory for action |
| ruby-version | false | "2.3.0" | Ruby version |
| bundler-cache | false | "true" | Use bundler cache |
| bundler | false | "1.x.x" | What version of bundler to install |

**Comment by MSP-Greg** [comment]
Maybe it could be mentioned in a different manner in the README, but see the below for more information about inputs and their allowed values:

https://github.com/ruby/setup-ruby/blob/master/action.yml

**Comment by jared-bloomer** [comment]
I see. That is helpful. Kind of hard to find that though. From user experience it would be better if it called out or defined in the README.

**Comment by eregon** [comment]
It's already documented extensively in https://github.com/ruby/setup-ruby#supported-version-syntax
