### ISSUE TITLE
FeatReq: Add support for custom list of gem sources

### ISSUE THREAD

**Issue by erikpaasonen** [ruby/setup-ruby#521]
hi! 👋 

my company wants to block access to rubygems.org and workloads should instead point to a custom source (virtual repo proxy) because $reasons.

I can't run `gem sources --add` ahead of time without the `gem` command.

I tried creating a `~/.gemrc` file with my custom list, but the action didn't seem to use it at runtime (i.e. the action still failed due to the unavailability of rubygems.org).

can you please consider adding support for a custom list of gem sources to override the default rubygems.org source?

**Comment by dentarg** [comment]
Just specify the sources you want to use in your Gemfile?

I guess I'm missing some important piece of info to understand what the issue is :)

Also, if you want functionality in this action, please consider contributing the code yourself, especially if is work commercial use (which "$reasons" sounds like)

**Comment by erikpaasonen** [comment]
We have a mix of self hosted runners and Github hosted runners, and some workloads are deployed on both. Could look into editing the Gemfile on the fly. This request is for the ability to override on a per-call basis, perhaps conditionally omitted by using a GH expression.

I'd love to contribute this but I'm personally lacking in the NodeJS expertise to add a [pre-if](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runspre-if) command, since this action is written as Javascript type. I'll see what help I can drum up.

**Comment by dentarg** [comment]
Not sure this action is the correct place to address this, reading https://guides.rubygems.org/command-reference/#gem-sources it sounds like modifying `~/.gemrc` should work.

Is the problem you are having that this action [installs bundler](https://github.com/ruby/setup-ruby#bundler) before installing your gems? You can try specifying `default` for the `bundler` input if so: https://github.com/ruby/setup-ruby/blob/4f1c6a74a76f6080cfef20ffbd7e540fc4297e7f/action.yml#L17-L23

**Comment by erikpaasonen** [comment]
Thank you for the guidance. Got this working using `~/.gemrc`.
