### ISSUE TITLE
Support for macos-13-arm64 runner

### ISSUE THREAD

**Issue by egarni** [ruby/setup-ruby#530]
Github just introduced m1 mac runner https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/

Currently getting the error `Error: The current runner (macos-13-arm64) was detected as self-hosted because the platform does not match a GitHub-hosted runner image (or that image is deprecated and no longer supported).` when targeting `macos-13-xlarge`

**Comment by eregon** [comment]
See https://github.com/ruby/setup-ruby/pull/494#issuecomment-1743537651 and what follows

**Comment by eregon** [comment]
Done, see https://github.com/ruby/setup-ruby/pull/494#issuecomment-1758099885 and the next comment.
