### ISSUE TITLE
Consider BUNDLE_ONLY in cache key

### ISSUE THREAD

**Issue by r7kamura** [ruby/setup-ruby#531]
BUNDLE_ONLY has been added since bundler 2.3.19.

- https://github.com/rubygems/rubygems/pull/5759

I think this value should be included in the cache key as well as BUNDLE_WITH and BUNDLE_WITHOUT, what do you think?

https://github.com/ruby/setup-ruby/blob/52b8784594ec115fd17094752708121dc5dabb47/bundler.js#L235-L239

**Comment by eregon** [comment]
Yes, that makes sense, could you make a PR for it?

**Comment by r7kamura** [comment]
Thanks for your quick reply. I created the following pull request for this 👌 

- https://github.com/ruby/setup-ruby/pull/532

**Comment by jlurena** [comment]
When will this be tagged?
