### ISSUE TITLE
Latest release dropped support for 3.1.4 on macos 13?

### ISSUE THREAD

**Issue by jonbrooks** [ruby/setup-ruby#534]
### Ensure the following before filing this issue

- [X] I verified it reproduces with the latest version with `- uses: ruby/setup-ruby@v1` (see [Versioning policy](https://github.com/ruby/setup-ruby/blob/master/README.md#versioning))

- [X] I tried to reproduce the issue locally by following the workflow steps (including all commands done by `ruby/setup-ruby`, except for `Downloading Ruby` & `Extracting Ruby`),
and it did not reproduce locally (if it does reproduce locally, it's not a ruby/setup-ruby issue)

### Are you running on a GitHub-hosted runner or a self-hosted runner?

self-hosted runner

### Link to the failed workflow job (must be a public workflow job, so the necessary information is available)

Workflow is private

### Any other notes?

We are running Mac OS 13 arm64, and are using Ruby 3.1.4.

[Version 1.155](https://github.com/ruby/setup-ruby/releases/tag/v1.155.0) would successfully download https://github.com/ruby/ruby-builder/releases/download/toolcache/ruby-3.1.4-macos-latest.tar.gz

Starting with [Version 1.156](https://github.com/ruby/setup-ruby/tree/v1.156.0), it appears that it tries (and fails) to download a ruby version at: https://github.com/ruby/ruby-builder/releases/download/toolcache/ruby-3.1.4-macos-13-arm64.tar.gz

Was it intentional to drop Ruby version 3.1.4 on these systems with this release?

**Comment by eregon** [comment]
https://github.com/ruby/ruby-builder/releases/download/toolcache/ruby-3.1.4-macos-latest.tar.gz is an amd64 binary, not an aarch64. So that never worked on purpose on macos-arm64. But maybe it accidentally did through Rosetta? That would be pretty slow though.
Ruby 3.1 fails to build on macos-arm64: https://github.com/ruby/setup-ruby/pull/494#issuecomment-1758099885

**Comment by eregon** [comment]
> [Version 1.155](https://github.com/ruby/setup-ruby/releases/tag/v1.155.0) would successfully download https://github.com/ruby/ruby-builder/releases/download/toolcache/ruby-3.1.4-macos-latest.tar.gz

How did that work? Until the last release macos-arm64 was not supported and so considered self-hosted and so would never download a prebuilt ruby AFAIK.

**Comment by jonbrooks** [comment]
>How did that work? Until the last release macos-arm64 was not supported and so considered self-hosted and so would never download a prebuilt ruby AFAIK.

Apologies - I must be wrong about that piece.  Maybe it wasn't downloading a prebuilt Ruby - I didn't actually witness it doing that.

**Comment by eregon** [comment]
So maybe someone followed the self-hosted instructions given by setup-ruby and manually installed ruby 3.1.4 on your self-hosted runner(s). That should work as good as it did before.

In any case I'll try to support 3.1.x on macos-arm64.
Any help to figure out why it [fails to build](https://github.com/ruby/ruby-builder/actions/runs/6485390387/job/17611360976) is welcome, e.g. maybe you can run `ruby-build --verbose 3.1.4 ~/tmp/ruby-3.1.4` and report if that works on your macos-arm4 machine and investigate if it doesn't.

**Comment by eregon** [comment]
Fixed: https://github.com/ruby/setup-ruby/pull/494#issuecomment-1759387165
