### ISSUE TITLE
Disrespecting a $RUNNER_TOOL_CACHE in v1.156.0

### ISSUE THREAD

**Issue by astlock** [ruby/setup-ruby#535]
### Ensure the following before filing this issue

- [X] I verified it reproduces with the latest version with `- uses: ruby/setup-ruby@v1` (see [Versioning policy](https://github.com/ruby/setup-ruby/blob/master/README.md#versioning))

- [X] I tried to reproduce the issue locally by following the workflow steps (including all commands done by `ruby/setup-ruby`, except for `Downloading Ruby` & `Extracting Ruby`),
and it did not reproduce locally (if it does reproduce locally, it's not a ruby/setup-ruby issue)

### Are you running on a GitHub-hosted runner or a self-hosted runner?

self-hosted runner

### Link to the failed workflow job (must be a public workflow job, so the necessary information is available)

NA

### Any other notes?

Have a RUNNER_TOOL_CACHE=/Users/administrator/gha-agent/_work/_tool variable on runners, which is respected in v1.155.0 but not in v1.156.0.

```
v1.155.0
Run ruby/setup-ruby@v1.155.0
Modifying PATH
  Entries added to PATH to use selected Ruby:
    /Users/administrator/gha-agent/_work/_tool/Ruby/3.1.2/arm64/bin
Print Ruby version
  /Users/administrator/gha-agent/_work/_tool/Ruby/3.1.2/arm64/bin/ruby --version
  ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin22]
  Took   0.01 seconds
...
```

```
v1.156.0
##[group]Run ruby/setup-ruby@v1
with:
  ruby-version: 3.1.2
  bundler-cache: true
env:
  KEYCHAIN: ...
  ...
Modifying PATH
  Entries added to PATH to use selected Ruby:
    /Users/runner/hostedtoolcache/Ruby/3.2.2/arm64/bin
Error: Error: EACCES: permission denied, mkdir '/Users/runner'
```

```
macOS overview
ProductName:		macOS
ProductVersion:		13.5.2
BuildVersion:		22G91
kern.version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:17:35 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8

```

**Comment by eregon** [comment]
It's expected, it's because macos-arm64 was considered self-hosted runner before and now is considered github-hosted runner.

If you want to use your custom tool-cache you can set `self-hosted: true`: https://github.com/ruby/setup-ruby/blob/9f4cc09ff9bfdbb47651abdbd87ceed9374f4449/action.yml#L33

OTOH if instead you make `/Users/runner/hostedtoolcache` writable then you can use all the prebuilt Rubies on macos-arm64 (those prebuilt Rubies need a fixed path on the filesystem to run).

**Comment by eregon** [comment]
I need to update the docs because the default for `self-hosted` no longer depends on the value of `$RUNNER_TOOL_CACHE` since https://github.com/ruby/setup-ruby/issues/475#issuecomment-1455088592
