### ISSUE TITLE
Option to print Gemfile.lock

### ISSUE THREAD

**Issue by fulldecent** [ruby/setup-ruby#537]
In Ruby projects that publish a Gem, it is customary to NOT check Gemfile.lock into the repo.

Source: https://github.com/github/gitignore/blob/4488915eec0b3a45b5c63ead28f286819c0917de/Ruby.gitignore#L46-L50

It can be helpful to review the Gemfile.lock for debugging. So perhaps this could be an option in this action.

**Comment by eregon** [comment]
You can just `cat Gemfile.lock` as the step after this action, there is no need for an option for this, it would be unnecessary complexity.
Also `bundle install` already prints the installed gems (although that might change in latest Bundler I think).
