### ISSUE TITLE
Node 16 is deprecated on GitHub, use Node 20

### ISSUE THREAD

**Issue by TWiStErRob** [ruby/setup-ruby#539]
### Ensure the following before filing this issue

- [X] I verified it reproduces with the latest version with `- uses: ruby/setup-ruby@v1` (see [Versioning policy](https://github.com/ruby/setup-ruby/blob/master/README.md#versioning))

- [X] I tried to reproduce the issue locally by following the workflow steps (including all commands done by `ruby/setup-ruby`, except for `Downloading Ruby` & `Extracting Ruby`),
and it did not reproduce locally (if it does reproduce locally, it's not a ruby/setup-ruby issue)

### Are you running on a GitHub-hosted runner or a self-hosted runner?

GitHub-hosted runner

### Link to the failed workflow job (must be a public workflow job, so the necessary information is available)

N/A, it was triggered on private, couldn't repro on public, it seems not all runners have the deprecation yet.

### Any other notes?

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, ruby/setup-ruby@v1, actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

![image](https://github.com/ruby/setup-ruby/assets/2906988/8de6d4ff-a8c5-423f-941c-7585657f2d36)

**Comment by eregon** [comment]
Could you make a PR? You just need to change https://github.com/ruby/setup-ruby/blob/master/action.yml

**Comment by TWiStErRob** [comment]
@eregon #540, but other actions increased their major version for this change.
e.g. https://github.com/actions/checkout/releases/tag/v4.0.0

**Comment by TWiStErRob** [comment]
Note: the warning won't show for now: https://github.com/actions/upload-artifact/issues/444#issuecomment-1779785321

**Comment by srallen** [comment]
:wave: I'm still seeing warnings about upgrading to Node 20: 

<img width="787" alt="Screenshot 2024-02-16 at 5 10 57 PM" src="https://github.com/ruby/setup-ruby/assets/5016731/3413f671-0eee-4312-8471-2dad75e4cbc8">

I believe this is due to this action's use of `actions/cache@v3`: https://github.com/ruby/setup-ruby/blob/22fdc77bf4148f810455b226c90fb81b5cbc00a7/package.json#L25 Version 4 for `actions/cache` doesn't appear to actually have breaking changes. Would it be possible for this action to bump to v4 of `actions/cache`?

**Comment by TWiStErRob** [comment]
That's a node package, embedded into [dist](https://github.com/ruby/setup-ruby/blob/master/dist/index.js). I don't think GHA can see that.

Are you sure there's no actions/cache@v3 in your workflow or one of the composite actions?

**Comment by srallen** [comment]
@TWiStErRob I found v3 of action/cache in another 3rd party composite action that I missed the first time through trying to find the source of the warning I was seeing. Thanks for taking the time to respond.
