### ISSUE TITLE
Branches and Tagging Don't Match Github Recommendations

### ISSUE THREAD

**Issue by wagenet** [ruby/setup-ruby#55]
Right now, `v1` is a branch, which works, but there really should be a `v1` tag pointing to the latest v1 release:

> Move the major version tag (v1, v2, etc.) to point to the Git ref of the current release. For more information, see "Git basics - tagging."
> https://help.github.com/en/actions/building-actions/about-actions#versioning-your-action

**Comment by eregon** [comment]
A moving tag is a `git` anti-pattern IMHO.
This has been discussed here: https://github.com/actions/toolkit/issues/214
I think upstream decisions went wrong here, and it's unclear to me why `v1` was ever a tag for some GitHub Actions.

A branch is much safer, idiomatic and disallows non-linear pushes, etc.
So I don't plan to change this, and there is already automation bumping the `v1` branch on release.

The README is fairly clear about this:
> This action follows semantic versioning with a moving v1 branch. This follows the recommendations of GitHub Actions.

Whatever relies on `v1` being a tag should accept a branch too.
