### ISSUE TITLE
BUNDLED_WITH from Gemfile.lock not being honored

### ISSUE THREAD

**Issue by aglover-zendesk** [ruby/setup-ruby#550]
### Ensure the following before filing this issue

- [X] I verified it reproduces with the latest version with `- uses: ruby/setup-ruby@v1` (see [Versioning policy](https://github.com/ruby/setup-ruby/blob/master/README.md#versioning))

- [X] I tried to reproduce the issue locally by following the workflow steps (including all commands done by `ruby/setup-ruby`, except for `Downloading Ruby` & `Extracting Ruby`),
and it did not reproduce locally (if it does reproduce locally, it's not a ruby/setup-ruby issue)

### Are you running on a GitHub-hosted runner or a self-hosted runner?

self-hosted runner

### Link to the failed workflow job (must be a public workflow job, so the necessary information is available)

N/A, private workflow

### Any other notes?

While using `setup-ruby` with all of the default options (no options specified in the `with` fields), `setup-ruby` is installing `bundler ~>2` instead of the version specified in the BUNDLED_WITH section of the Gemfile.lock file. Logs from the workflow:

```
Installing Bundler
  Using Bundler 2 from Gemfile.lock BUNDLED WITH 2.4.22
  /home/runner/.rubies/ruby-2.7.1/bin/gem install bundler -v ~> 2 --no-document
  ERROR:  Error installing bundler:
  	The last version of bundler (~> 2) to support your Ruby & RubyGems was 2.4.22. Try installing it with `gem install bundler -v 2.4.22`
  	bundler requires Ruby version >= 3.0.0. The current ruby version is 2.7.1.83.
```

Strangely, it appears to log the correct, desired version from the Gemfile.lock (`Using Bundler 2 from Gemfile.lock BUNDLED WITH 2.4.22`) but in the `gem install` command you can see it is not specifying the correct version (` /home/runner/.rubies/ruby-2.7.1/bin/gem install bundler -v ~> 2 --no-document`).

I'm confident that `setup-ruby` is installing bundler v2.5 because [v2.5 just released today](https://github.com/rubygems/rubygems/blob/master/bundler/CHANGELOG.md) and dropped support for Ruby 2.7, which is what got me started on this issue. So it appears to be installing bundler 2.5 despite seeing a BUNDLED_WITH version in the Gemfile.lock

Note that this issue was initially discovered in v1.48.0 of setup-ruby but also reproduced on v1.62.0 (latest release). 

It's possible this is due to a change in default behavior at some point, but I didn't see anything in the releases between 1.48.0 and 1.62.0 that would indicate that. we've worked around this in the meantime by using

```yaml
with:
  bundler: 2.4.22
```

but wanted to raise this with y'all in case it's a real issue

**Comment by VSPPedro** [comment]
I faced the same probleI faced the same problem. The solution is to ensure that you have the correct version of the RubyGem installed for your ruby. For instance:

Example:

```
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          rubygems: 3.4.22
```

**Comment by dentarg** [comment]
Works here https://github.com/dentarg/actions-test/actions/runs/7227967069/job/19696581968#step:3:26

Can you double check your workflows?

**Comment by aglover-zendesk** [comment]
thanks for testing @dentarg , going to assume it's something with the workflow or our private runners then. closing the issue
