### ISSUE TITLE
Support Ruby 3.3

### ISSUE THREAD

**Issue by bmulholland** [ruby/setup-ruby#552]
Only the RC is listed

**Comment by reaper** [comment]
+1 detected ruby is the RC1 one

<img width="503" alt="Screenshot 2023-12-25 at 20 08 16" src="https://github.com/ruby/setup-ruby/assets/82464/c4827ba2-6856-4d6d-99c8-f7b1d90f53d7">

**Comment by eregon** [comment]
Done now
