### ISSUE TITLE
An error occurred while installing google-protobuf (3.25.1), and Bundler cannot continue

### ISSUE THREAD

**Issue by xiaoyouPrince** [ruby/setup-ruby#558]
### Ensure the following before filing this issue

- [X] I verified it reproduces with the latest version with `- uses: ruby/setup-ruby@v1` (see [Versioning policy](https://github.com/ruby/setup-ruby/blob/master/README.md#versioning))

- [X] I tried to reproduce the issue locally by following the workflow steps (including all commands done by `ruby/setup-ruby`, except for `Downloading Ruby` & `Extracting Ruby`),
and it did not reproduce locally (if it does reproduce locally, it's not a ruby/setup-ruby issue)

### Are you running on a GitHub-hosted runner or a self-hosted runner?

GitHub-hosted runner

### Link to the failed workflow job (must be a public workflow job, so the necessary information is available)

https://github.com/xiaoyouPrince/xiaoyouPrince.github.io/actions/runs/7343823910/job/19994881328

### Any other notes?

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # submodules: true
          # If using the 'assets' git submodule from Chirpy Starter, uncomment above
          # (See: https://github.com/cotes2020/chirpy-starter/tree/main/assets)

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

**Comment by xiaoyouPrince** [comment]
Sorry maybe this is a network error.  after many tries, it successfully.   
https://github.com/xiaoyouPrince/xiaoyouPrince.github.io/actions/runs/7343823911/job/19994888730

**Comment by xiaoyouPrince** [comment]
i just found the theme author has knows the issue, as 
https://github.com/cotes2020/jekyll-theme-chirpy/discussions/1428

**Comment by eregon** [comment]
Any failure during `bundle install` is basically never the fault of this action.

**Comment by xiaoyouPrince** [comment]
Thanks for answering, it is not the action's fault, is something else.
