### ISSUE TITLE
macos-14-arm64 detected as self-hosted

### ISSUE THREAD

**Issue by ZacSweers** [ruby/setup-ruby#568]
### Ensure the following before filing this issue

- [X] I verified it reproduces with the latest version with `- uses: ruby/setup-ruby@v1` (see [Versioning policy](https://github.com/ruby/setup-ruby/blob/master/README.md#versioning))

- [X] I tried to reproduce the issue locally by following the workflow steps (including all commands done by `ruby/setup-ruby`, except for `Downloading Ruby` & `Extracting Ruby`),
and it did not reproduce locally (if it does reproduce locally, it's not a ruby/setup-ruby issue)

### Are you running on a GitHub-hosted runner or a self-hosted runner?

GitHub-hosted runner

### Link to the failed workflow job (must be a public workflow job, so the necessary information is available)

https://github.com/slackhq/circuit/actions/runs/7716099695/job/21032136995?pr=1165#step:4:9

**Comment by mbibosch** [comment]
#567 is aiming to fix this

**Comment by eregon** [comment]
Released as https://github.com/ruby/setup-ruby/releases/tag/v1.171.0
