### ISSUE TITLE
head version for windows platform is uncompleted build

### ISSUE THREAD

**Issue by hsbt** [ruby/setup-ruby#570]
### Ensure the following before filing this issue

- [X] I verified it reproduces with the latest version with `- uses: ruby/setup-ruby@v1` (see [Versioning policy](https://github.com/ruby/setup-ruby/blob/master/README.md#versioning))

- [X] I tried to reproduce the issue locally by following the workflow steps (including all commands done by `ruby/setup-ruby`, except for `Downloading Ruby` & `Extracting Ruby`),
and it did not reproduce locally (if it does reproduce locally, it's not a ruby/setup-ruby issue)

### Are you running on a GitHub-hosted runner or a self-hosted runner?

GitHub-hosted runner

### Link to the failed workflow job (must be a public workflow job, so the necessary information is available)

https://github.com/ruby/rake/actions/runs/7780963597/job/21214533251?pr=542#step:5:27

### Any other notes?

@MSP-Greg `head` version for Windows platform like `windows-latest` is not complete to build bundled gems.

```
Failure: test_dot_rake_files_can_be_loaded_with_dash_r(TestRakeFunctional): <"Ignoring syslog-0.1.2 because its extensions are not built. Try: gem pristine syslog --version 0.1.2\n"> was expected to be empty.
```

Above failure shows that `syslog` didn't build with ruby-head. It may be fixed you add `--without-ext=+,syslog` option to `configure`.

**Comment by MSP-Greg** [comment]
@hsbt

Thanks for the reminder.  JFYI, ruby-loco master builds are mingw, ucrt, & mswin.  RubyInstaller2 builds the head build.

Ping @larskanis

**Comment by MSP-Greg** [comment]
@hsbt It seems that `--without-ext=+,syslog` does not work with bundled gems...

**Comment by eregon** [comment]
Could you file the issue at https://github.com/oneclick/rubyinstaller2 instead?
There is nothing to change in setup-ruby to fix this.

**Comment by hsbt** [comment]
Okay, I leave from this issue. I don't have spare time for 3rd party build.
