### ISSUE TITLE
Unknown version 3.3 for ruby on ubuntu-22.04

### ISSUE THREAD

**Issue by KleberDevMan** [ruby/setup-ruby#579]
Error: Unknown version 3.3 for ruby on ubuntu-22.04
![image](https://github.com/ruby/setup-ruby/assets/38785907/33d0b7d4-4d5f-44d1-a36e-9a11ee01c953)

Someone can help me?

**Comment by eregon** [comment]
You're using an ancient version of setup-ruby, you should update it.
