### ISSUE TITLE
Enable use from other Actions

### ISSUE THREAD

**Issue by reitzig** [ruby/setup-ruby#58]
Sometimes, we do not care about installing Ruby per se: we want some tool that happens to use Ruby. One example is building a static website with Hugo and Asciidoc -- which happens to depend on asciidoctor as an external dependency, despite neither Hugo devs nor page creators seeing a single line of Ruby.

So, we want to install asciidoctor and not care about how it's done, e.g. through [this action I just wrote](https://github.com/reitzig/actions-asciidoctor). Unfortunately, since actions can't call each other, every user has to repeat the call of `ruby/setup-ruby`.

A recommended workaround seems to be for actions to factor out their core functionality into functions that can be imported and called from other actions.

**Comment by dentarg** [comment]
There was a discussion about this in https://github.com/ruby/setup-ruby/pull/33

**Comment by eregon** [comment]
Would the approach mentioned in https://github.com/ruby/setup-ruby/pull/33#issuecomment-636010670 work for you?

**Comment by reitzig** [comment]
@dentarg @eregon Thanks for the pointer!

That would probably _work_ but I don't think it's already in the nicest form possible. Engaging there.

**Comment by dentarg** [comment]
This seems to be on the roadmap for GitHub Actions: https://github.com/actions/runner/issues/438

**Comment by eregon** [comment]
I think with https://github.com/ruby/setup-ruby/pull/33#issuecomment-640048355 that's all that's really needed to use this action from other actions.

I'd like to close this issue.
Feel free to open other issues if you have specific issues.
I'd rather not have to also maintain an `npm` package unless there is a clear reason using https://raw.githubusercontent.com/ruby/setup-ruby/v1/dist/index.js doesn't work.

**Comment by reitzig** [comment]
FWIW, https://github.com/actions/runner/issues/646 seems to be working towards a first-class solution.
