### ISSUE TITLE
Support non `runner` user on self-hosted runners

### ISSUE THREAD

**Issue by fkorotkov** [ruby/setup-ruby#583]
### Ensure the following before filing this issue

- [X] I verified it reproduces with the latest version with `- uses: ruby/setup-ruby@v1` (see [Versioning policy](https://github.com/ruby/setup-ruby/blob/master/README.md#versioning))

- [X] I tried to reproduce the issue locally by following the workflow steps (including all commands done by `ruby/setup-ruby`, except for `Downloading Ruby` & `Extracting Ruby`),
and it did not reproduce locally (if it does reproduce locally, it's not a ruby/setup-ruby issue)

### Are you running on a GitHub-hosted runner or a self-hosted runner?

self-hosted runner

### Link to the failed workflow job (must be a public workflow job, so the necessary information is available)

https://github.com/cirruslabs/actions-playground/actions/runs/8781520697/job/24093712039

### Any other notes?

Self-mosted macOS runners not always use `runner` as the user name. Right now `runner` user name is hard coded:

https://github.com/ruby/setup-ruby/blob/6bd3d993c602f6b675728ebaecb2b569ff86e99b/common.js#L267-L269

Can probably be fixed similar to https://github.com/actions/setup-python/pull/708

**Comment by fkorotkov** [comment]
Current workaround if you have "admin" user is to run the following first to pre-create `/Users/runner`:

```yaml
- name: Ruby Workaround
  run: sudo mkdir -p /Users/runner && sudo chown -R admin:admin /Users/runner
```

**Comment by eregon** [comment]
See https://github.com/ruby/setup-ruby/pull/584#issuecomment-2068993404, it's not fixable.
