### ISSUE TITLE
Missing Ruby 3.3.1 on Windows

### ISSUE THREAD

**Issue by vinistock** [ruby/setup-ruby#586]
The changes in https://github.com/ruby/setup-ruby/commit/70da3bbf44ac06db1b0547ce2acc9380a5270d1e added support for 3.3.1, but not for Windows. This makes Windows CI fail for projects using 3.3.1 in their `.ruby-version` https://github.com/Shopify/ruby-lsp/actions/runs/8833375834/job/24252541255.

**Comment by MSP-Greg** [comment]
All the Ruby release builds used in setup-ruby are built in https://github.com/oneclick/rubyinstaller2 / https://github.com/oneclick/rubyinstaller2-packages.

With the multiple releases that recently occurred, it may be a few days...

**Comment by eregon** [comment]
This is expected, you can file an issue at https://github.com/oneclick/rubyinstaller2 if you'd like.
Nothing we can do here until then.
There will be an automatic PR within 24 hours of a new rubyinstaller2 release.

**Comment by eregon** [comment]
The new releases are at https://github.com/oneclick/rubyinstaller2/releases
but https://raw.githubusercontent.com/oneclick/rubyinstaller.org-website/master/_data/downloads.yaml hasn't been updated yet.
I suppose it's just a matter of time, so I'll wait for that.
(FYI cc @larskanis, thank you for your work!)

**Comment by larskanis** [comment]
I just updated the downloads.yaml.

**Comment by eregon** [comment]
https://github.com/ruby/setup-ruby/releases/tag/v1.175.1
