### ISSUE TITLE
Download link is invalid for macos-latest (macos-13) with Ruby 2.5

### ISSUE THREAD

**Issue by Fryguy** [ruby/setup-ruby#601]
### Ensure the following before filing this issue

- [X] I verified it reproduces with the latest version with `- uses: ruby/setup-ruby@v1` (see [Versioning policy](https://github.com/ruby/setup-ruby/blob/master/README.md#versioning))

- [X] I tried to reproduce the issue locally by following the workflow steps (including all commands done by `ruby/setup-ruby`, except for `Downloading Ruby` & `Extracting Ruby`),
and it did not reproduce locally (if it does reproduce locally, it's not a ruby/setup-ruby issue)

### Are you running on a GitHub-hosted runner or a self-hosted runner?

GitHub-hosted runner

### Link to the failed workflow job (must be a public workflow job, so the necessary information is available)

https://github.com/ManageIQ/rbvmomi2/actions/runs/9180932157/job/25246498930

### Any other notes?

I'm not sure why macos-latest points to macos-13, but because of that it generates an invalid download link to   https://github.com/ruby/ruby-builder/releases/download/toolcache/ruby-2.5.9-macos-13-arm64.tar.gz

```
Run ruby/setup-ruby@v1
  with:
    ruby-version: 2.5
    bundler-cache: true
Modifying PATH
  Entries removed from PATH to avoid conflicts with default Ruby:
    /opt/homebrew/lib/ruby/gems/3.0.0/bin
    /opt/homebrew/opt/ruby@3.0/bin
  Entries added to PATH to use selected Ruby:
    /Users/runner/hostedtoolcache/Ruby/2.5.9/arm64/bin
Downloading Ruby
  https://github.com/ruby/ruby-builder/releases/download/toolcache/ruby-2.5.9-macos-13-arm64.tar.gz
  Took   0.34 seconds
Error: Error: Unexpected HTTP response: 404
    at /Users/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:8702:25
    at Generator.next (<anonymous>)
    at fulfilled (/Users/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:8612:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by Fryguy** [comment]
I thought this might be related to #568 (and possibly #588, but that was edited away), but I can't tell if that PR should have fixed it.

**Comment by hsbt** [comment]
`macos-latest` is `macos-14` today. `setup-ruby` didn't provide Ruby 2.5 for `macos-14` that is Apple Silicon.

**Comment by Fryguy** [comment]
@hsbt I'm a little confused, because I just ran with `macos-latest` 2 hours ago and it's giving me macos-13?

**Comment by Fryguy** [comment]
@hsbt - oh you're right, the underlying runner is [macos-14-arm64](https://github.com/ManageIQ/rbvmomi2/actions/runs/9182412018/job/25251205270#step:1:8), however, the URl being generated is saying macos-13:  https://github.com/ruby/ruby-builder/releases/download/toolcache/ruby-2.5.9-macos-13-arm64.tar.gz

I do see there is a https://github.com/ruby/ruby-builder/releases/download/toolcache/ruby-2.5.9-macos-latest.tar.gz build available, but that's not the URL being generated by setup-ruby

**Comment by dentarg** [comment]
This is the logic used by setup-ruby: https://github.com/ruby/setup-ruby/blob/7dc18ff0ca6e3630d3f29d2a85ebf6cc27ae9d6c/ruby-builder.js#L115-L116

This is the motivation behind it: https://github.com/ruby/setup-ruby/pull/567#issuecomment-1919266892

Your job is running on `Image: macos-14-arm64` ([log](https://github.com/ManageIQ/rbvmomi2/actions/runs/9180932157/job/25246498930#step:1:8)) but there are no Ruby 2.5 built for any macOS using arm64, it is too old: https://github.com/ruby/setup-ruby/commit/5cfe23c062c0aac352e765b1b7cc12ea5255ccc4

**Comment by dentarg** [comment]
You need to use `macos-13` if you want to test with Ruby 2.5: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories

**Comment by Fryguy** [comment]
Thanks @dentarg - let me give that a try

**Comment by Fryguy** [comment]
Thank you!  That worked - I thought it was a bug that 14 was downloading 13, but I see now that pinning to macos-13 works.  Thanks again!

**Comment by eregon** [comment]
Yeah the URLs can be confusing, if would be nice to clarify then but that's a lot of work and would need duplicate files for a long time, so not realistic I'm afraid.

The real confusion and problem IMO is GitHub changed macos-latest from an amd64 to a arm64 runner, that's really surprising, IMO the arch should be part of the image name (and probably it will need to be when there is linux-aarch64)

**Comment by Fryguy** [comment]
For future readers, here is the change i made in my repo to get it working: https://github.com/ManageIQ/rbvmomi2/commit/e7ee943594a98f26836e4c49dcf9c9b064a46cb1

**Comment by eregon** [comment]
Looking at the error message we should improve that so it says 2.5 is not available on macos-arm, I'll reopen to track that

**Comment by eregon** [comment]
I added a clear error message in https://github.com/ruby/setup-ruby/commit/d046db60e330fabc5f3aa2535500c8cc3fb26b07 and https://github.com/ruby/setup-ruby/commit/68b705993a229bc26951e27288e9374376f2ee44 (fixup).
