### ISSUE TITLE
Bundle step does not seem to respect .bundle/config files in the CWD

### ISSUE THREAD

**Issue by ducharmemp** [ruby/setup-ruby#612]
### Ensure the following before filing this issue

- [X] I verified it reproduces with the latest version with `- uses: ruby/setup-ruby@v1` (see [Versioning policy](https://github.com/ruby/setup-ruby/blob/master/README.md#versioning))

- [X] I tried to reproduce the issue locally by following the workflow steps (including all commands done by `ruby/setup-ruby`, except for `Downloading Ruby` & `Extracting Ruby`),
and it did not reproduce locally (if it does reproduce locally, it's not a ruby/setup-ruby issue)

### Are you running on a GitHub-hosted runner or a self-hosted runner?

GitHub-hosted runner

### Link to the failed workflow job (must be a public workflow job, so the necessary information is available)

N/A private runner. See logs in description

### Any other notes?

I'm opening this mainly for documentation purposes if this can't be addressed, but this stumped me for a bit before I read through the action code

Given the following action setup:
```yaml
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.1"
          bundler-cache: true
          working-directory: ${{ matrix.folder }} 
```

And a local `bundle config --local gemfile ../other-dir`

I get the following soft error: 
```
> bundle install
Could not determine gemfile path, skipping "bundle install" and caching
```

This is due to the fact that the ruby action tries to utilize the environment variable to determine the Gemfile path, but that value might not be known until bundler boots up and loads the config. The action code seems to scan for the Gemfile/Gemfile.lock path first then bails out if it couldn't find it. I can set the environment variable myself but the bundler config file is just yaml, which makes it awkward to deal with.

To answer the question that I'm anticipating:
> Why are you doing this

We have a set of rails engines in our monolith that we'd like to utilize the same lock versions, and so we'd like to force all engines to utilize a single Gemfile while allowing each engine to run commands as if they were developing an independent gem (think rubocop/rspec executions).

If this is something that's out of scope for this action, I'm ok with closing it. I mainly wanted to document this for other people that might hit this particular issue.

**Comment by eregon** [comment]
Where do you run `bundle config --local gemfile ../other-dir`? I don't see that in your workflow snippet.

**Comment by eregon** [comment]
Does it work if you set `BUNDLE_GEMFILE` as [documented](https://github.com/ruby/setup-ruby?tab=readme-ov-file#matrix-of-gemfiles)?

**Comment by ducharmemp** [comment]
> Where do you run bundle config --local gemfile ../other-dir? I don't see that in your workflow snippet.

Apologies, I should have clarified. `bundle config --local gemfile ../other-dir` is run on my local machine and added to my git repo via `git add .bundle/config` (note that this is usually gitignored, we removed the ignore entry for testing).

So to add more color with a directory tree:

```ruby
my_engine/
    .bundle/config. <-- contains the BUNDLE_GEMFILE entry
other-dir/
    Gemfile
    Gemfile.lock
```

> Does it work if you set BUNDLE_GEMFILE as [documented](https://github.com/ruby/setup-ruby?tab=readme-ov-file#matrix-of-gemfiles)?

It would and does work with the environment variable, yes, I've used that in other contexts and CI setups. However, it was a bit surprising that I couldn't leverage my existing bundle config. Again, might be out of scope for this action but I wanted to have this as documentation in the form of an issue at least

**Comment by eregon** [comment]
I see, right that's quite tricky behavior as we'd need to call `bundle config gemfile` or so to find the value (seems problematic for several reasons), or read the `.bundle/config` file ourselves (given it's YAML not so easy).
It's also a bit surprising to have the config in one "working dir" and the Gemfile in another, although clearly Bundler supports that.

This feels out of scope of the action because it seems too complicated to implement and the workaround seems easy enough. So I'd like to close this as "not planned".
We could document this in the README, but it sounds to explain it without adding more confusion, so maybe just having this issue is best.
