### ISSUE TITLE
It does work with `2.2.17`, but doesn't work with `2.1.4`. I'm not going to bisect that further, but that's the fix - you need to use a more recent Bundler on Windows than you do on other platforms, and it needs to be at least I guess `2.2` or so.

### ISSUE THREAD

**Issue by KewinTien** [ruby/setup-ruby#615]
It does work with `2.2.17`, but doesn't work with `2.1.4`. I'm not going to bisect that further, but that's the fix - you need to use a more recent Bundler on Windows than you do on other platforms, and it needs to be at least I guess `2.2` or so.

I don't know if that needs to be documented, or tested for, or something like that.

_Originally posted by @chrisseaton in https://github.com/ruby/setup-ruby/issues/209#issuecomment-889064123_

**Comment by eregon** [comment]
https://github.com/ruby/setup-ruby/issues/209#issuecomment-889070062
