### ISSUE TITLE
Error: Unavailable version 24.0.1 for truffleruby on windows-2022

### ISSUE THREAD

**Issue by johnnyshields** [ruby/setup-ruby#619]
Looks like latest `truffleruby` is not supported on `windows-latest`

```
Error: Error: Unavailable version 24.0.[1](https://github.com/SAML-Toolkits/ruby-saml/actions/runs/9839748987/job/27162485606?pr=687#step:3:1) for truffleruby on windows-2022
          You can request it at https://github.com/ruby/setup-ruby/issues
          Cause: Unexpected HTTP response: 404
    at D:\a\_actions\ruby\setup-ruby\v1\dist\index.js:6[5](https://github.com/SAML-Toolkits/ruby-saml/actions/runs/9839748987/job/27162485606?pr=687#step:3:6)032:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async body (D:\a\_actions\ruby\setup-ruby\v1\dist\index.js:395:14)
```

Here's the failing build for reference: https://github.com/SAML-Toolkits/ruby-saml/actions/runs/9839748987/job/27162485606?pr=687

**Comment by MSP-Greg** [comment]
It looks like TruffleRuby has never been available on Windows, at least in GitHub Actions?

See the following file, which is where setup-ruby looks for 'none MRI' Windows Rubies:

https://github.com/ruby/ruby-builder/releases/tag/toolcache

**Comment by eregon** [comment]
Yeah, it just needs a better error.
