### ISSUE TITLE
Feature request: infer the ruby version from the Gemfile's `ruby`

### ISSUE THREAD

**Issue by searls** [ruby/setup-ruby#621]
In the event the user hasn't configured `ruby-version`, it'd be really slick if the action inspected the version range passed to `ruby` in `Gemfile` and then installed the latest available version of Ruby that satisfied the version.

Thought of this because my action doesn't specify `ruby-version`, but my Gemfile does:

```ruby
source "https://rubygems.org"

ruby "3.3.3"
```

As a result, my builds are failing with "Your Ruby version is 3.3.4, but your Gemfile specified 3.3.3", which seems avoidable.

**Comment by eregon** [comment]
Parsing the Gemfile seems too difficult (it is arbitrary Ruby code), so I think that's not a good way to approach it.

If you want to deduplicate where the version is specified, `.ruby-version` is the best place to store it, and then you can e.g. `File.read("#{__dir__}/.ruby-version")` in the Gemfile.

**Comment by dentarg** [comment]
In later Bundler versions it is even supported natively: https://mattbrictson.com/blog/bundler-ruby-file

**Comment by abitrolly** [comment]
> Parsing the Gemfile seems too difficult (it is arbitrary Ruby code), so I think that's not a good way to approach it.

Looks like `setup-ruby` doesn't support all version syntaxes either https://github.com/ruby/setup-ruby#supported-version-syntax so a least `ruby "3.3.3"` syntax could be supported to avoid `File.read("#{__dir__}/.ruby-version")` kludge.

**Comment by eregon** [comment]
@abitrolly As @dentarg said, there is a good way to do this in Gemfile:
```ruby
ruby file: ".ruby-version"
```

This is the best solution, it tells both Ruby installers/switchers and Bundler the right version.

**Comment by abitrolly** [comment]
@eregon the best would be to use `Gemfile` `ruby` version directly, like Heroku does https://devcenter.heroku.com/articles/ruby-versions#selecting-a-version-of-ruby

There is no need to treat the `Gemfile` as a Ruby file - regexp/split string parsing can cover 80% of the need.

**Comment by ntkme** [comment]
I don't think heroku parse it as text file or ruby file, it very likely just run command `bundle platform --ruby`, which returns like below:

```
$ bundle platform --ruby
ruby 4.0.2
```

```
$ bundle platform --ruby
No ruby version specified
```

**Comment by eregon** [comment]
Does any Ruby version switcher (RVM, rbenv, chruby, asdf, mise, ...) use the Gemfile to pick the Ruby version?
I don't think so, hence I don't think setup-ruby should either, at least not automatically.

TBH I think having the Ruby version in the Gemfile is bad practice, it's too late, you already need Ruby to read that file.
The engine & engine_version parts sound weird to me: https://bundler.io/man/gemfile.5.html#ENGINE, that's such a verbose and inconvenient way to specify things, notably the first version becomes redundant then with the `engine_version` enforcing a given RUBY_VERSION anyway.

I have no idea why Heroku does it that way, maybe legacy reasons?

**Comment by eregon** [comment]
Asked another way, what does it give you to specify `ruby "a.b.c"` in the Gemfile?
Couldn't you just have that in `.ruby_version` and remove the line entirely from the Gemfile?
Then it's no duplication and far more standard.

**Comment by abitrolly** [comment]
> Does any Ruby version switcher (RVM, rbenv, chruby, asdf, mise, ...) use the Gemfile to pick the Ruby version?

Yes. https://rvm.io/workflow/projects#project-file-gemfile

> I have no idea why Heroku does it that way, maybe legacy reasons?

There is no sign that Heroku supports `.ruby-version` or ever supported that. It does this to lock the environment to avoid gem bugs between Ruby versions.
