### ISSUE TITLE
Windows - switch to MSYS2 bash shell ?

### ISSUE THREAD

**Issue by MSP-Greg** [ruby/setup-ruby#63]
I've got the MSYS2 bash shell running as the default in my fork.

Using Reline, I set up a [workflow](https://github.com/MSP-Greg/reline/actions/runs/129361313/workflow) where all jobs ran tests both using pwsl (PowerShell Core) and MSYS2 bash.  All jobs (Ubuntu, macOS, Win) passed .

Bundler's tests will only run using bash, and they also pass, see https://github.com/MSP-Greg/rubygems/actions/runs/131762536

The one issue is we need to re-arrange things so there is some code that runs for all Rubies on Windows, as it needs to run for Windows JRuby jobs.

The code is in the commit https://github.com/MSP-Greg/ruby-setup-ruby/commit/b2da215d2df

Thoughts?

**EDIT:**

Haven't implemented it yet, but this issue is about ENV['Path'] handling.  I think the best way to handle it is below:

1. Remove system Ruby from Path 
2. Add msys2PathEntries to Path
3. Install Ruby
4. Add build specific entries (MSYS for Ruby 2.3 and earlier, MSVC for mswin)
5. Add Ruby bin folder

**Comment by eregon** [comment]
So the change is to use `core.addPath()`  instead of `core.exportVariable()` where possible and that automatically selects the MSYS2 bash when MSYS2 is `core.addPath()`-ed ? (https://github.com/actions/runner/issues/497#issuecomment-640909822)

Looks good from a quick look, I'll look more at it later.
Would probably be helpful if it's as a PR, so it's easier to comment on specific lines.

**Comment by MSP-Greg** [comment]
Essentially.  I ended looking at both Toolkit/core code and the runner C# code.

I would state that when dealing with `Path`, `core.exportVariable()` should be the first call, and only used if one needs to remove items.  After that, items should only be added via `core.addPath()`, which is just string concat'ing, so multiple items can be added at once.

The core code passes the info to the C# runner via `process.stdout.write()`, so it's the similar to the script commands one can use (most or all start with `::`)...

It was also messed up by the call to vcvars.bat in the mswin build code, which modifies `Path`.

Any the last run used the MSYS2 bash shell for everything Windows except 2.2 & 2.3, which use the MSYS bash shell.  MSYS2 in the path for all the commands it has available, and its `tar` is now used.

> Would probably be helpful if it's as a PR

I need to adjust the workflow, rebase, squash, etc.  I'll submit later today/tonite (I'm -0500, US CDT).  I just wanted to see if you had any issues, but I didn't expect any.

My main goal was to see if people could use either Bash or PowerShell Core code for scripting with **all platforms**.

**Comment by eregon** [comment]
> My main goal was to see if people could use either Bash or PowerShell Core code for scripting with **all platforms**.

Yes, that would be great!

**Comment by MSP-Greg** [comment]
See 'Add envPreInstall, common.setupPath, use MSYS2 bash for Windows bash', https://github.com/ruby/setup-ruby/commit/6ead459c & #64

Ok to close...

**Comment by eregon** [comment]
This seems to work fine now, thanks!
