### ISSUE TITLE
When action removes gempath `bin` directory it fails to re-add it later

### ISSUE THREAD

**Issue by LPLabrys99** [ruby/setup-ruby#632]
### Ensure the following before filing this issue

- [X] I verified it reproduces with the latest version with `- uses: ruby/setup-ruby@v1` (see [Versioning policy](https://github.com/ruby/setup-ruby/blob/master/README.md#versioning))

- [X] I tried to reproduce the issue locally by following the workflow steps (including all commands done by `ruby/setup-ruby`, except for `Downloading Ruby` & `Extracting Ruby`),
and it did not reproduce locally (if it does reproduce locally, it's not a ruby/setup-ruby issue)

### Are you running on a GitHub-hosted runner or a self-hosted runner?

self-hosted runner

### Link to the failed workflow job (must be a public workflow job, so the necessary information is available)

N/A

### Any other notes?

Hi there,

I have a job which runs fine using the `ruby/setup-ruby` action on Github hosted runners. However when I run the job on a self-hosted runner the job fails due to one of the Gem entrypoints not being available on the system `PATH`.

Having looked through the job logs, I can see that the action removes some paths from the `PATH` environment variable so that it can install a different version of Ruby without clashes. The action creates a new entry in the path for the new version of Ruby, but not for the new gems. The end result is that when I run `pod ...` the command fails with a "not found" error.

```
Modifying PATH
  Entries removed from PATH to avoid conflicts with default Ruby:
    /opt/homebrew/lib/ruby/gems/3.2.0/bin
    /opt/homebrew/opt/ruby@3.2/bin
  Entries added to PATH to use selected Ruby:
    /Users/runner/hostedtoolcache/Ruby/3.3.1/arm64/bin
```

This appears to be a bug. Surely the action should also create a PATH entry for the `gems/.../bin` directory if it's going to remove the system gems from the environment PATH?

This happens on version `1.199.0`.

Sorry but I can't post a link to the failed job - it's a closed source project.

Thanks

**Comment by eregon** [comment]
Gem executables either end up in the same directory as where the `ruby` executable is (when using `gem install`), because the action doesn't set GEM_HOME and expects nothing else to set it, or somewhere under `vendor/bundle` when using `bundle install`, in which case it must be executed with `bundle exec foo`.

**Comment by eregon** [comment]
Using any executable from `/opt/homebrew/lib/ruby/gems/3.2.0/bin` would be wrong as that would then run on Ruby 3.3.1, that makes no sense.

**Comment by eregon** [comment]
Probably you want to `gem install cocoapods` or add it to your Gemfile if you want to use `pod` with Ruby 3.3.1.
