### ISSUE TITLE
Docs: Please specify exactly what goes inside .ruby-version

### ISSUE THREAD

**Issue by fulldecent** [ruby/setup-ruby#640]
Here is what everybody is currently putting in their .ruby-version files:

https://github.com/search?q=path%3A**%2F.ruby-version&type=code&ref=advsearch&p=4

And there is no consensus of any discernible format there.

**Comment by rgaufman** [comment]
Mine has this:

```
$ cat .ruby-version
3.3.5
```

**Comment by eregon** [comment]
It's clearly specified what setup-ruby accepts here: https://github.com/ruby/setup-ruby?tab=readme-ov-file#supported-version-syntax

**Comment by fulldecent** [comment]
Got it, thank you.

Many people are using like `ruby-2.3.0@cesium_rails` `ruby-1.9.3-p484` `ruby-2.1.*` `jruby-head`

This seems to be some off-label usage or their usage is just broken.
