### ISSUE TITLE
macos-15-arm64 detected as self-hosted

### ISSUE THREAD

**Issue by jvanderwee** [ruby/setup-ruby#647]
### Ensure the following before filing this issue

- [X] I verified it reproduces with the latest version with `- uses: ruby/setup-ruby@v1` (see [Versioning policy](https://github.com/ruby/setup-ruby/blob/master/README.md#versioning))

- [X] I tried to reproduce the issue locally by following the workflow steps (including all commands done by `ruby/setup-ruby`, except for `Downloading Ruby` & `Extracting Ruby`),
and it did not reproduce locally (if it does reproduce locally, it's not a ruby/setup-ruby issue)

### Are you running on a GitHub-hosted runner or a self-hosted runner?

GitHub-hosted runner

### Link to the failed workflow job (must be a public workflow job, so the necessary information is available)

N/A

### Any other notes?

macOS 15 images just released: https://github.com/actions/runner-images/releases/tag/macos-15%2F20240923.103

**Comment by eregon** [comment]
Right, it's listed at https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources as in Beta now.

I think we can just use the existing Ruby builds from older macOS versions. Maybe even relax to allow any version >= the version we build on.
