### ISSUE TITLE
No "available interpreter-os association" is visible on the action?

### ISSUE THREAD

**Issue by stdedos** [ruby/setup-ruby#650]
i.e. on https://github.com/ruby/setup-ruby/blob/f321cf5a4d1533575411f8752cf25b86478b0442/ruby-builder-versions.json I don't see which interpreter is available on which OS.

e.g. even though `truffleruby+graalvm-21` supposedly exists, it does not work in my action (https://github.com/stdedos/interception/actions/runs/11123894333/job/30908313355)

- Should you create a matrix? (ie like https://github.com/actions/setup-python/issues/15#issuecomment-525410806)
- (For both repositories), should that be (a) automatically done, and (b) give some "permalink-like" url to "that matrix"?

**Comment by eregon** [comment]
In general it's every version is available on all platforms on which it can be built.
The full list is at https://github.com/ruby/ruby-builder/releases/tag/toolcache FWIW.
There are some known version-platform combinations which do not work: https://github.com/ruby/setup-ruby/blob/c04af2bb7258bb6a03df1d3c1865998ac9390972/index.js#L173-L195

Regarding `truffleruby+graalvm-21` that's just really old and I didn't build it on newer runners.
I would suggest to only test the latest release of truffleruby (with just `ruby-version: truffleruby`).
`truffleruby+graalvm` is basically redundant in CI (unless you need interop with Java or other languages).

Maintaining a matrix would be too high overhead.

**Comment by stdedos** [comment]
> The full list is at [ruby/ruby-builder@`toolcache` (release)](https://github.com/ruby/ruby-builder/releases/tag/toolcache) FWIW.

That is amazing already 😁 

Would you consider mentioning it here? https://github.com/ruby/setup-ruby/blob/c04af2bb7258bb6a03df1d3c1865998ac9390972/README.md?plain=1#L39-L57

> The combinations of the available versions and runners can be seen here: https://github.com/ruby/ruby-builder/releases/tag/toolcache

(_tl;dr that's what I'm asking here_)

**Comment by eregon** [comment]
Ah yes, sure, PR welcome
