### ISSUE TITLE
Make DefaultToolCachePath configurable

### ISSUE THREAD

**Issue by joaopedrocg27** [ruby/setup-ruby#661]
Hello!

Would it be possible to make DefaultToolCachePath configurable? We are using self-hosted runners with a different user

![image](https://github.com/user-attachments/assets/1610323a-d3c1-4393-aa39-4dcbfd0b9799)

https://github.com/ruby/setup-ruby/blob/master/common.js#L300

**Comment by eregon** [comment]
Not possible, see https://github.com/ruby/setup-ruby?tab=readme-ov-file#using-self-hosted-runners

**Comment by joaopedrocg27** [comment]
> Not possible, see https://github.com/ruby/setup-ruby?tab=readme-ov-file#using-self-hosted-runners

I read that's but why? Is it a ruby wide thing? Why can't it be set to /Users/root for example?

**Comment by eregon** [comment]
>  This is necessary since the Ruby builds embed the install path when built and cannot be moved around.

And if you try to move CRuby around it just fails to start.

There are more details if you look for enable-load-relative in the issue tracker.
