### ISSUE TITLE
macOS 15 support

### ISSUE THREAD

**Issue by austinlouden** [ruby/setup-ruby#670]
macOS 15 is now generally available for GitHub-hosted runners, and the `macos-latest` runners will soon switch to macOS 15. [More details here](https://github.com/github/roadmap/issues/986).

MacOS 15 runners currently fail with following error, e.g. `macos-15-xlarge`:
```
Error: The current runner (macos--arm64) was detected as self-hosted because the platform does not match a GitHub-hosted runner image (or that image is deprecated and no longer supported).
```

Is it possible to add explicit support for `macos-15-*` runners?

**Comment by eregon** [comment]
It's already supported since https://github.com/ruby/setup-ruby/issues/647
