### ISSUE TITLE
Add MacOS 15 support 

### ISSUE THREAD

**Issue by lodibrahim** [ruby/setup-ruby#671]
Description
As macOS 15 is now available, ensuring that the ruby/setup-ruby action supports this version would be beneficial. This feature would enable developers using macOS 15 to continue utilizing the action seamlessly in their CI workflows.

Rationale
Compatibility: Ensures the action remains functional and compatible with the latest macOS release.
Future-proofing: Proactively supports users upgrading to macOS 15.
Improved Developer Experience: Avoids potential issues or workarounds for developers who rely on this action in their GitHub Actions pipelines.

Suggested Implementation
Update the action's configuration or scripts to recognize and support macOS 15.
Test the action on macOS 15 runners to ensure all functionality works as expected.
Update documentation to reflect macOS 15 support.

**Comment by MSP-Greg** [comment]
See 17f5c914a0f3, macoos-15 has been available since late September

Please post more information.  As to docs, see #672

**Comment by eregon** [comment]
Maybe https://github.com/ruby/setup-ruby/commit/9a9fe58c47b8bca3b707c7a46d0c67c4a3fe6d89 helps clarify it's already supported?
