### ISSUE TITLE
clear bundler-cache

### ISSUE THREAD

**Issue by aep-sunlife** [ruby/setup-ruby#674]
With bundler-cache set explicitly to `true`, the bundler-audit executable pinned in my Gemfile silently fails to provision and appear in PATH.

https://github.com/rubysec/bundler-audit

As a workaround, I am skipping the bundler-cache option and running `bundle install` manually in my GitHub Actions.

**Comment by eregon** [comment]
We need more info if you would like to have this investigated. Please use the bug report template.
