### ISSUE TITLE
Error: Unknown version 3.4 for ruby on windows-2022

### ISSUE THREAD

**Issue by st0012** [ruby/setup-ruby#680]
### Ensure the following before filing this issue

- [X] I verified it reproduces with the latest version with `- uses: ruby/setup-ruby@v1` (see [Versioning policy](https://github.com/ruby/setup-ruby/blob/master/README.md#versioning))

- [X] I tried to reproduce the issue locally by following the workflow steps (including all commands done by `ruby/setup-ruby`, except for `Downloading Ruby` & `Extracting Ruby`),
and it did not reproduce locally (if it does reproduce locally, it's not a ruby/setup-ruby issue)

### Are you running on a GitHub-hosted runner or a self-hosted runner?

GitHub-hosted runner

### Link to the failed workflow job (must be a public workflow job, so the necessary information is available)

https://github.com/ruby/rdoc/actions/runs/12528436389/job/34943029817?pr=1259

**Comment by eregon** [comment]
https://github.com/ruby/setup-ruby?tab=readme-ov-file#supported-versions

> Only release versions published by [RubyInstaller](https://rubyinstaller.org/downloads/archives/) are available on Windows.

So this is expected until RubyInstaller releases 3.4

**Comment by st0012** [comment]
Ah sorry I missed that.

**Comment by ashmaroli** [comment]
RubyInstaller has shipped [RubyInstaller-3.4.1-1](https://github.com/oneclick/rubyinstaller2/releases/tag/RubyInstaller-3.4.1-1)

**Comment by MSP-Greg** [comment]
@ashmaroli

Thanks.  See 'bot' code at https://github.com/ruby/ruby-builder/blob/master/.github/workflows/check-new-windows-versions.yml

It should run in a few minutes (19:00 UTC)

**Comment by eregon** [comment]
https://github.com/ruby/setup-ruby/releases/tag/v1.207.0

**Comment by ashmaroli** [comment]
Thank you :)
