### ISSUE TITLE
Add Ruby 2.1 support

### ISSUE THREAD

**Issue by meineerde** [ruby/setup-ruby#70]
I'd like to test a gem on Ruby 2.1 to ensure legacy compatibility. I understand that this Ruby version is not supported upstream anymore (as is Ruby 2.2). However, since Ruby 2.1 was shipped with some older operating systems (notably Debian 8 Jessie), I'd still like to support it with my code if possible, and obviously need to test this.

In fact, adding support to ruby/setup-ruby is rather straight forward. I have a WIP branch for that at [meineerde/setup-ruby@feature/ruby-2.1](https://github.com/meineerde/setup-ruby/tree/feature/ruby-2.1). For Windows builds, this alone is enough. For macOS and Ubuntu, there would still need to be builds generated in [ruby/ruby-builder](https://github.com/ruby/ruby-builder).

Is this something you would be interested in?

**Comment by eregon** [comment]
My personal thoughts:
Debian 8 Jessie is really old (2015), there's been two Debian releases since then.
Are you sure you want to keep supporting such old systems riddled with security issues and unfixed bugs?

Concretely I don't really mind if building 2.1 is easy enough on GH Actions.

**Comment by meineerde** [comment]
In my specific case, I'm developing a gem for [application logging](https://github.com/meineerde/rackstash) where I want to be able to support as many systems as possible in order to help people update.  With complex legacy systems, it's often not easy to update and you have a very long tail of older running systems (and often not by choice but because of various external constraints).

As Ruby matures as an language and eco-system, I'd like to help keep the basics supportable as long as possible (but not longer). I that means supporting some older Rubies I'm all in. That doesn't mean we should recommend to people to use those older versions if they have a choice of course :)

**Comment by eregon** [comment]
OK, let's see if it builds: https://github.com/ruby/ruby-builder/actions

Which specific version should we support?
Since 2.1.9 and 2.1.10 (last 2.1 release) [are the same](https://github.com/ruby/ruby/compare/v2_1_9...v2_1_10), and RubyInstaller only has 2.1.9, I'd say 2.1.9.

**Comment by eregon** [comment]
2.1.9 builds are done now in ruby-builder.

**Comment by eregon** [comment]
Released as https://github.com/ruby/setup-ruby/releases/tag/v1.40.0
