### ISSUE TITLE
Permission error when testing a gem with a binary

### ISSUE THREAD

**Issue by DannyBen** [ruby/setup-ruby#77]
I am in the process of converting my `actions/setup-ruby` to `ruby/setup-ruby` and encountered one difference for the worse in `ruby/setup-ruby`.

I have an rspec test suite that runs its own binary file, located in the `bin` folder:

```ruby
it "errors gracefully" do
  expect(`bin/radio playlist init hello`).to match_approval('bin/premium_error')
end
```

This [causes a permission error](https://github.com/DannyBen/audio_addict/runs/993054375) when using the Ruby-maintained action (the [failing YAML](https://github.com/DannyBen/audio_addict/blob/1742e66ff4aaa199eb0ca8ca1509e3e6cf76dee5/.github/workflows/test.yml)):

```
  1) bin/radio error handling errors gracefully
     Failure/Error: expect(`bin/radio playlist init hello`).to match_approval('bin/premium_error')

     Errno::EACCES:
       Permission denied - bin/radio
     # ./spec/audio_addict/bin_errors_spec.rb:11:in ``'
     # ./spec/audio_addict/bin_errors_spec.rb:11:in `block (2 levels) in <top (required)>'
```

And for comparison, [it works fine](https://github.com/DannyBen/audio_addict/runs/993070889) when using the GitHub-developed Ruby action (the [passing YAML](https://github.com/DannyBen/audio_addict/blob/f88c059e42c35e3658da27d8561fec740ae1fd84/.github/workflows/test.yml)).

**Comment by eregon** [comment]
https://github.com/DannyBen/audio_addict/blob/master/bin/console doesn't have executable permissions.

I'm not sure how it worked before though, but either way it should have executable permissions if it's meant to be executed like an exectuable.

**Comment by eregon** [comment]
Interesting:
```
gem install bundler
bundle config path vendor/bundle
bundle install --jobs 4 --retry 3
```
will actually make `bin/radio` executable (I can see it locally with `git status`).
Not sure if that's a bug of Bundler or intended.

I don't think this action should modify files under `bin`, but rather that `bin/radio` should be `chmod +x bin/radio`.
It's going to be annoying locally anyway if git status is not clean after `bundle install`.

The cache only restores `vendor/bundle` and other executables are in `vendor/bundle/ruby/2.6.0/bin` (same before).
The reason it differs is if the cache is available then `bundle check` is run instead of `bundle install`, and that doesn't seem to make the file executable.
That's an important optimization to save time, so I think we should keep it.

This behavior also happens without `bundle config path` FWIW.

**Comment by DannyBen** [comment]
Not only it worked before, it works **still**. in:

- Local environment (RVM)
- Travis CI
- GitHub maintained `actions/setup-ruby`

It only fails when using this action.

I know I can probably `chmod +x` it in the git index, but I still believe that the evidence points to this action not behaving properly.

**Comment by eregon** [comment]
You can of course use `ruby/setup-ruby` and not use `bundler-cache: true`, that'd still work.

`bundler-cache: true` inevitably needs to make some (IMHO reasonable) assumptions, and one of them is that `bundle install` makes no changes except under the path it's instructed to.
Maybe I'll change my mind if we have other cases, but here I would say it's odd to not have the executable bit on something meant to be executed.

**Comment by DannyBen** [comment]
Thanks. I will close this issue, but maybe open another one - since I still see differences (failures) when using this action. It seems that the `bundle install` command works differently here and in the Github-maintained action - [error here](https://github.com/DannyBen/audio_addict/pull/36/checks?check_run_id=993182623) - I will see if its a problem I understand myself or not.

**Comment by DannyBen** [comment]
> ... and one of them is that bundle install makes no changes except under the path it's instructed to

And yes, absolutely reasonable assumption.
