### ISSUE TITLE
Minify dist, bring back eslint?

### ISSUE THREAD

**Issue by MSP-Greg** [ruby/setup-ruby#80]
Before updating to the new @actions/cache code (v1.0.2), the dist/index.js file was ~ 600K.  After the update it's about ~ 2M.  Using `ncc build index.js -o dist -m` drops it to about 935K.  Might be something to consider.

Also, since minifying can make debugging more difficult, maybe return to using eslint?

**Comment by MSP-Greg** [comment]
Re eslint, there are at least a few repos in actions using.  Since I'm typo prone, I'll probably continue to use it locally...

Ok to close?

**Comment by eregon** [comment]
Yeah I'd say for now size doesn't seem a problem.
Re `eslint` if it helps, maybe we can do something to run it more easily.
But it seemed mostly useless to me when it was enabled (I'm using IntelliJ which is quite good at editing JS).
