### ISSUE TITLE
JRuby - "JRUBY_HOME or JRUBY_PARENT_CLASSPATH are not set"

### ISSUE THREAD

**Issue by MSP-Greg** [ruby/setup-ruby#85]
While working on Puma, JRuby, and Ubuntu 20.04, it wouldn't compile.  Might the following msg indicate an issue?

"JRUBY_HOME or JRUBY_PARENT_CLASSPATH are not set"

I don't know, but you'd know in your sleep...

See: https://github.com/MSP-Greg/puma/runs/1083079974?check_suite_focus=true#step:5:15

**Comment by eregon** [comment]
cc @headius @enebo
(I am not a reference regarding JRuby, please don't ask me JRuby questions)

**Comment by MSP-Greg** [comment]
Sorry.  Bad assumption.  BTW, have a good day (or evening)...

**Comment by MSP-Greg** [comment]
I just ran Puma CI again against Ubuntu 20.04.  Running both jruby & jruby-head against the 'with ssl' & 'without ssl' workflows.

All four jobs compiled, three jobs passed testing, the fourth locked up on testing, but we've had intermittent issues with that in Puma JRuby CI.

Hence, the compile issue seems to have solved itself.  Not sure if it was Actions or JRuby.

Regardless, closing.
