### ISSUE TITLE
Add support for Amazon Linux 2

### ISSUE THREAD

**Issue by navarroaxel** [ruby/setup-ruby#89]
Add support for more Linux distributions like `Amazon Linux 2`. Maybe using the `Ruby Version Manager`.

ref: https://github.com/ruby/setup-ruby/issues/88#issuecomment-694832806

**Comment by eregon** [comment]
Let's keep the discussion in #88 for now since I think all self hosted that do not correspond to GitHub runner/virtual environment fall in the same category.

**Comment by navarroaxel** [comment]
@eregon I don't get you. The README says explicitly `this actions works for hosted runners`.

Do you have a working example?

**Comment by eregon** [comment]
That was added in https://github.com/ruby/setup-ruby/pull/67.
Originally it said no supported for self-hosted.
We probably need to precise the wording there to say "only if exactly the same virtual environment as for GitHub-hosted runners".
