### ISSUE TITLE
Any possibility for ARM (Raspberry Pi) support?

### ISSUE THREAD

**Issue by dogweather** [ruby/setup-ruby#90]
I found that `setup-ruby` downloads an x86 binary when run on a Raspberry Pi self-hosted runner. Is there a way to add ARM binaries here or to `ruby-builder`?

**Comment by dentarg** [comment]
I don't think it will be possible until https://github.com/github/roadmap/issues/95

I think you will have to compile on ARM yourself until then

**Comment by dogweather** [comment]
Thanks! So this project's scope isn't really the whole `ruby` organization, it's more like `setup-github-ruby`?

**Comment by eregon** [comment]
In short this action does not support self-hosted runners, because it's not possible to precompile for all variants of them.

**Comment by dogweather** [comment]
How about if I do the ARM equivalent of what you're doing for X86: create precompiled binaries in a repo in the same layout?

**Comment by eregon** [comment]
Yes, you could fork https://github.com/ruby/ruby-builder and make your own builds, I think that's a good solution for self-hosted.
And we can add an input in this action to use an alternative source for releases / built Rubies. We'll need to figure out a way to list versions of such an external repository, though.

Interesting, it seems the GHA runner just got pre-release support for ARM: https://github.com/actions/runner/releases/tag/v2.273.5

If GitHub also adds GitHub-hosted ARM runners, I could try making ARM builds in ruby/ruby-builder too (although I expect older Ruby releases or ruby installers might not support ARM yet).
Without GitHub-hosted ARM runners, I don't know how I would run these builds, so it seems difficult.

Also as usual, a built Ruby is often not portable across OS, etc, so depending on which Raspberry Pi and which OS & OS version a build might or not work. If you make your own builds then of course you can guarantee the exact same environment.

**Comment by eregon** [comment]
BTW I wonder if any other `setup-*` action supports self-hosted runners and how.
I guess they don't support it, or they expect the software (here Ruby) to be already installed on disk.

**Comment by dogweather** [comment]
Once I get the build script working, I could donate the Raspberry Pi compute resource for creating the ARM binaries. I.e., I own several new Raspi's which are running the GitHub self-hosted runner software. It'd be no problem to set up another instance of it and register it with this repo as an `ARM`-tagged runner.

And yep, I found that `setup-python` has the same X86 assumptions. In that case, though, it's a little easier because the various ARM Linuxes come with Python 3 pre-installed. So it was easy for me to make [a basic Python ARM build script](https://github.com/dogweather/raspberry-pi-python-github-runner/blob/main/.github/workflows/python-test.yml).

**Comment by eregon** [comment]
> In that case, though, it's a little easier because the various ARM Linuxes come with Python 3 pre-installed.

Isn't there a Ruby package too on Debian-based Linux for ARM64?
That of course provides only 1 Ruby version, but it might be the most convenient way to get started for self-hosted.
