### ISSUE TITLE
ruby 2.7.2

### ISSUE THREAD

**Issue by FireFart** [ruby/setup-ruby#93]
Ruby 2.7.2 was released:
https://www.ruby-lang.org/en/news/2020/10/02/ruby-2-7-2-released/

**Comment by eregon** [comment]
PR at https://github.com/ruby/setup-ruby/pull/92

**Comment by eregon** [comment]
See https://github.com/ruby/setup-ruby/pull/92#issuecomment-703264088

Reopening because 2.7.2 is not yet available on Windows, and I plan to wait for that for a `ruby/setup-ruby` release.

**Comment by CiTroNaK** [comment]
I've encountered with this today

```
Run ruby/setup-ruby@v1.45.0
Using 2.7.2 as input from file .ruby-version
Error: Unknown version 2.7.2 for ruby on ubuntu-18.04
        available versions for ruby on ubuntu-18.04: 2.1.9, 2.2.10, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.4.7, 2.4.9, 2.4.10, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.5.6, 2.5.7, 2.5.8, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.6.6, 2.7.0, 2.7.1, head, debug
        File an issue at https://github.com/ruby/setup-ruby/issues if would like support for a new version
```

**Comment by lxxxvi** [comment]
Can confirm @CiTroNaK 's input on `ubuntu-18.04` just now.

**Comment by eregon** [comment]
It's explained in https://github.com/ruby/setup-ruby/pull/92#issuecomment-703265045.

2.7.2 is not available on Windows, and I plan to wait for that to make a release and bump `v1`.
That way we don't end up with `2.7` resolving to different versions based on the platform.

Until then you can try 2.7.2 on Linux & macOS by using: `- uses: ruby/setup-ruby@master`.
Of course, that is less stable than `@v1`, but it seems inevitable for such cases as this one.

**Comment by deivid-rodriguez** [comment]
It seems it's available now: https://github.com/oneclick/rubyinstaller2/releases/tag/RubyInstaller-2.7.2-1.

**Comment by eregon** [comment]
Windows build added, and release is done: https://github.com/ruby/setup-ruby/releases/tag/v1.47.0
(and `v1` is automatically updated to the latest release).
