### ISSUE TITLE
[misc] ubuntu-latest will be 20.04, macOS-11.0 Big Sur

### ISSUE THREAD

**Issue by MSP-Greg** [ruby/setup-ruby#94]
You've probably seen them, but just in case:

https://github.com/actions/virtual-environments/issues/1816 - Ubuntu-latest workflows will use Ubuntu-20.04

Other than the changed OpenSSL 'security_level', not much of a change between 19.04 and 20.04.  I have suggested that workflows use the numeric style rather than 'latest'...

https://github.com/actions/virtual-environments/issues/1814 - macOS 11.0 (Big Sur) is available as a preview

Not knowledgeable re macOS.  I have used a 10.15 Ruby build with 11.0.  They don't mention whether they will be removing 10.15 or not.  Then again, they mentioned that windows-2016 would be removed a long time ago...

**Comment by eregon** [comment]
I didn't, thanks for the notice.
`ubuntu-latest` changing to 20.04 shouldn't affect anything for this action.

OTOH when `macos-latest` changes to Big Sur, we'll need to be more careful if builds on Catalina don't run there. Probably they will. I guess we should test on macOS Big Sur to make sure the action work, and find out whether we can reuse builds from Catalina or not. Probably versioning all OS for builds is safer for the future, although building for more platforms is some overhead (especially for nightly builds).

**Comment by MSP-Greg** [comment]
> we should test on macOS Big Sur to make sure the action work

I've run Ruby 2.7 and JRuby on Big Sur in my Puma fork, both passed CI, so Puma compiled and tested ok.

> Probably versioning all OS for builds is safer for the future

True, but a PITA

**Comment by MSP-Greg** [comment]
@eregon

Big Sur just broke, seeing an error logged from here of 'Unknown ImageOS macos11'.

Not sure of the cause, the code below has a regex that matches against `ENV['ImageOS']`. 
 'macos-10.15' has an env value of `macos1015`, but currently  'macos-11.0' is `macos11`.  Hence, the regex below fails, and throws the above error...

https://github.com/ruby/setup-ruby/blob/ad1ebae995ccc3584a094574eafc5826942ec8d4/common.js#L55-L58

**Comment by eregon** [comment]
I see, will fix. I was thiking we should test on `macos-11.0`, well, this is a good reason for it.

**Comment by eregon** [comment]
Fixed and tested in https://github.com/ruby/setup-ruby/releases.

TruffleRuby needs new builds for macos-11.0 though:
https://github.com/ruby/setup-ruby/issues/109
