### ISSUE TITLE
Ruby 2.7.1 Not Found

### ISSUE THREAD

**Issue by ostenbom** [ruby/setup-ruby#99]
Hi there,

Amazing to see that 2.7.2 is available through here already, but we haven't yet managed to update across our org yet, and so are still on 2.7.1 in most places.

Yesterday, we started getting `Error: Version 2.7.1 not found` errors across our actions builds even though I can see that 2.7.1 is still in your list of [ruby-builder-versions](https://github.com/ruby/setup-ruby/blob/master/ruby-builder-versions.js#L10)

Do you have any ideas why this might be happening already? Would be great if minors were kept around for a bit longer if possible.

Our setup is:

```
- uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
```

Where `.ruby-version` contains `2.7.1`

Thanks!

**Comment by eregon** [comment]
That message comes from https://github.com/actions/setup-ruby/blob/5f29a1cd8dfebf420691c4c9a0e832e2fae5a526/src/main.ts#L18, which means you were using `actions/setup-ruby` and not this action, which is `ruby/setup-ruby`.
2.7.1 works fine with this action.
